### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by david-nadaraia** [GtkSharp/GtkSharp#1]
is MacOS supported? I installed dotnet CLI template and I get this error when try to run application:

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libglib-2.0-0.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at GLib.Marshaller.g_malloc(UIntPtr size)
   at GLib.Marshaller.StringToPtrGStrdup(String str)
   at GLib.Global.set_ProgramName(String value)
   at Gtk.Application.Init()
   at gtk_sandbox.Program.Main(String[] args) in /Users/davidnadaraia/tmp/gtk-sandbox/Program.cs:line 11
```

GTK+3 is already installed on my mac...

**Comment by cra0zy** [comment]
Long story short, I'll probably get it working in February for Mac, I need to change how the native functions are getting called. .NET Core does not implement .dll.config mapping files (https://github.com/dotnet/coreclr/issues/930), so I had to temporarily improvise and see if by some miracle they decide to change their mind...

**Comment by cra0zy** [comment]
Half way there, the generator has been fixed, now all I have to do is fix the manual function calling.

**Comment by david-nadaraia** [comment]
Thanks for update. Does it also apply to Linux as well or just MacOS?

**Comment by cra0zy** [comment]
Applies to all the platforms, I'm replacing how native functions are called and removing all `[DllImport` from the code.

Tho Linux currently does work.

**Comment by cra0zy** [comment]
Devel branch now has completely revamped native functions calling and is working on Mac, the new nuget packages will be published later today / tomorrow.

![screen-shot-2018-01-17-at-3 15 40-pm](https://user-images.githubusercontent.com/6773302/35072756-44282ef8-fbe6-11e7-8ec9-4ff8007c1d73.png)

**Comment by qmfrederik** [comment]
FYI - A new API, `NativeLibrary`, is planned in .NET Core which should make working with native (unmanaged) libraries much easier. See dotnet/corefx#17135 for details.

If you think that's something that would be useful to you, would you mind upvoting that issue in the corefx repo? Thanks!

**Comment by cra0zy** [comment]
I don't think that API would be that useful. Remapping dllimport on the other hand would be amazing.
