### ISSUE TITLE
macOS: ImageMenuItem image not showing

### ISSUE THREAD

**Issue by KenjutsuGH** [GtkSharp/GtkSharp#102]
My setup:

* macOS 10.13.6 
* Visual Studio Community 2019 for Mac Version 8.2.2 (build 21)
*  gtk+3 3.24.10 installed via brew

I create a project with `dotnet new gtkapp -o Menu01` and then I use Glade to add a `GtkMenuBar` to **mainWindow.glade** I then build using `dotnet build Menu01.csproj` and run with `dotnet run`.

The program runs and shows the menu, but none of the menu images/icons are showing.

**Comment by cra0zy** [comment]
Gtk uses theme settings in regard to showing images in menus/buttons/etc. For button there is an "AlwaysShowImages" property, something similar probably exists for the menu item.

You can also set the Gtk Settings with this property.
