### ISSUE TITLE
LibHandySupport

### ISSUE THREAD

**Issue by badcel** [GtkSharp/GtkSharp#104]
What do you think about adding bindings for Libhandy in your project?

https://gitlab.gnome.org/Community/Purism/libhandy

**Comment by cra0zy** [comment]
For now I only plan on maintaining the bindings for the core libs, tho I do plan on writing my own gir to C# generator and at that point I'll try to support many more libs. (unless the mono guys decide to do it)

**Comment by badcel** [comment]
If I can help you out just ping me. I like to help pushing C# for linux.
