### ISSUE TITLE
Text dragging to another app does not seem to work on Windows

### ISSUE THREAD

**Issue by thytrherfvsefasfd443sf** [GtkSharp/GtkSharp#106]
I tested dragging some text from TreeView to another application using the following code.

	treeview.EnableModelDragSource(Gdk.ModifierType.Button1Mask, null, Gdk.DragAction.Copy);
	Gtk.Drag.SourceAddTextTargets(treeview);
	treeview.DragDataGet += (o, args) =>
	{
		args.SelectionData.Text = "Hello";
	};

It worked on Linux, but it did not work on Window. The mouse pointer had the text being dragged, but when I moved the mouse pointer on another application like Notepad or WordPad, the application did not show any feedback (If I drag text from one WordPad to another WordPad, the cursor follows the mouse pointer, but in this case, no such thing), and dropping had no effect.

I installed Gtk using MSYS2, and the version is mingw-w64-x86_64-gtk3-3.24.8-1.  .NET Core version is 2.2.401. GtkSharp version is 3.22.24.38. Windows version is Windows 10 (1903).

**Comment by cra0zy** [comment]
This is not a fault of the binding as such I will close this.

**Comment by thytrherfvsefasfd443sf** [comment]
If I may ask a question, do you think it is a bug of the Windows port of GTK? Or did I use drag and drop incorrectly? If it is the former, I will give up, but if it is the latter, I will try some other codes.

**Comment by cra0zy** [comment]
I haven't played with darg and drop between apps so I wouldn't know how that part works. The most I have done regarding that is dragging something into my app, not the other way around.
