### ISSUE TITLE
StatusIcon and notification messages

### ISSUE THREAD

**Issue by mferraricloudsurfers** [GtkSharp/GtkSharp#107]
I'm using StatusIcon object and works good on Mac and Windows. What I need to do is show notification messages as balloon text similarly to StatusIcon in Windows.Forms.
I there any way to have a similar behaviour with GtkSharp?

**Comment by cra0zy** [comment]
There is no way that I know of.

On a related note the StatusIcon has been deprecated and removed in Gtk 4.
