### ISSUE TITLE
Support webkit 

### ISSUE THREAD

**Issue by danielmeza** [GtkSharp/GtkSharp#109]
We can implement webkit support in order to use webview

**Comment by mikkeljohnsen** [comment]
@danielmeza You should look more at: https://gitlab.com/xiliumhq/chromiumembedded/cefglue
But it is not so easy to setup with Gtk3. I'm still struggling with it.

**Comment by knuxbbs** [comment]
This looks promising: https://blog.stevensanderson.com/2019/11/18/2019-11-18-webwindow-a-cross-platform-webview-for-dotnet-core/

**Comment by danielmeza** [comment]
@mikkeljohnsen there is any possibility to run this on top of .net core rather that mono? so we can use https://blog.stevensanderson.com/2019/11/18/2019-11-18-webwindow-a-cross-platform-webview-for-dotnet-core/ 

thanks @knuxbbs

**Comment by badcel** [comment]
I started an alternative implementation of GObject Libraries. The main purpose is to provide a nice C# api, and **not** just a wrapper around C-Libraries, so it feels like home if you are using it and porting your windows app to linux.

It does include first code for GTK and WebKitGTK (including communication from / to the browser). 

Any help is appreciated: https://github.com/GirCore/gir.core
