### ISSUE TITLE
Should there be an "OnForall" in the Container class?

### ISSUE THREAD

**Issue by zur003** [GtkSharp/GtkSharp#110]
In the Gnome documentation for the Gtk3 ContainerClass, it states;

> For implementations of GtkContainer the virtual method GtkContainerClass.forall() is always required, since it's used for drawing and other internal operations on the children.

However, although all the other virtual methods of GtkContainer appear in the GtkSharp Gtk.Container class (e.g., "OnFocusChildSet" for "set_focus_child"), I don't see a counterpart for "forall". Am I missing something here?

**Comment by nguyenkien** [comment]
This library missing many methods for many classes.

**Comment by Css-IanM** [comment]
It seems to be implemented as a delegate. 
https://github.com/GtkSharp/GtkSharp/blob/187ea11809d4e656deba522b2d3ecb3ea3b165dc/Source/Libs/GtkSharp/Container.cs#L127

**Comment by lytico** [comment]
used in
        static ForallDelegate ForallOldCallback;
        static ForallDelegate ForallCallback;

but it is never set or used

**Comment by harry-cpp** [comment]
Fixed in #150, props to @lytico.
