### ISSUE TITLE
Pixbuf.ScaleSimple causes a memory leak

### ISSUE THREAD

**Issue by dmsch** [GtkSharp/GtkSharp#112]
A scaled image does not get released from memory when disposed.

**Code to reproduce the issue:**

```C#
        static void Main(string[] args)
        {
            int count = 0;
            while (true)
            {
                using (var source = new Pixbuf("image.png"))
                using (var scaled = source.ScaleSimple(100, 100, InterpType.Bilinear))
                {
                    Console.WriteLine("scaled image " + ++count);
                }
                
                System.Threading.Thread.Sleep(250);
            }
        }
```

My Platform:
- .NET Core 3.0.100
- GtkSharp 3.22.24
- Ubuntu 18.04.3 LTS

**Comment by dmsch** [comment]
Workaround: the memory leak does not happen when using Pixbuf.Scale instead of Pixbuf.ScaleSimple

**Comment by pedrohex** [comment]
Hi @dmsch , 
Indeed Scale does not retain any object and no memory leaks occur, however, ScaleSimple exists for a good reason.
Cannot understand how to make a similar ScaleSimple using Scale. Do you have any examples or good documentation on this ?

**Comment by dmsch** [comment]
Hi @pedrohex 
that's how I am using Scale now:

```C#
private Pixbuf ScaleSimple(Pixbuf pixbuf, int width, int height)
{
      var scaled = new Pixbuf(pixbuf.Colorspace, pixbuf.HasAlpha, pixbuf.BitsPerSample, width, height);
      pixbuf.Scale(scaled, 0, 0, width, height, 0, 0, width/(double)pixbuf.Width, height/(double)pixbuf.Height, InterpType.Bilinear);
      return scaled;
}
```

**Comment by pedrohex** [comment]
thank you @dmsch. My function was pretty much like yours except in a drawingArea.Drawn event (must dispose the new pixbuf with using or dispose). The problem was with the cairo context paint, instead of the X, Y be 0,0 , i was sending the pixbuf size :\  lost about 3h because of this :P thanks again ;)

**Comment by zii-dmg** [comment]
Doesn't reproduces on current code. I think issue can be closed.
Tested with:
* .NET Core 5.0.4
* Windows 10 20H2

**Comment by jcbritobr** [comment]
It Happens yet, but with less memory. The issue still exists. We needs to reopen.
![image](https://user-images.githubusercontent.com/6579862/111386967-c6463c80-868b-11eb-8ac1-9d163b4ad8c8.png)
