### ISSUE TITLE
Gtk.Widget.DeleveEvent is not executed

### ISSUE THREAD

**Issue by VladislavAntonyuk** [GtkSharp/GtkSharp#113]
This example doesn't work:
http://docs.go-mono.com/index.aspx?link=E%3AGtk.Widget.DeleteEvent

OS: Windows 10
GTKSharp 2.12

**Comment by Css-IanM** [comment]
Considering the Version of GTKSharp you reference, this is the wrong repository for your issue. You want the mono version.

**Comment by VladislavAntonyuk** [comment]
I will attach a small repro project

**Comment by cra0zy** [comment]
@Css-IanM is right, you want https://github.com/mono/gtk-sharp
