### ISSUE TITLE
Include Evince/Edocument

### ISSUE THREAD

**Issue by Css-IanM** [GtkSharp/GtkSharp#121]
Would it be a reasonable request to include Evince/Edocument libs for usage with PDF. I have a use case for this but i'm unsure if this is the place for it, but i can see how an argument could be made that it is the right place. I'm just wondering everyone's thoughts are on this.

**Comment by cra0zy** [comment]
Ugh, I am barely able to help around with the current lib, I don't think I would be able to maintain one more. That being said as long as it has gir files you can try generating wrappers for it.
