### ISSUE TITLE
Assembly Name confuses bindings if non-standard components of GTK

### ISSUE THREAD

**Issue by Dadoum** [GtkSharp/GtkSharp#125]
I use Gnome Docking Library by GSharpKit, and when I reference it, it directly say me that all classes from GtkSharp are referenced in another assembly, gtk-sharp

**Comment by cra0zy** [comment]
GtkSharp is a for of gtk-sharp, it has the same names and methods as it. You would need to compile GSharpKit against GtkSharp if you want to use it with it.
