### ISSUE TITLE
Support for css

### ISSUE THREAD

**Issue by cpt1971** [GtkSharp/GtkSharp#127]
Hi,

I've been trying all sorts of various combinations of:

provider = new CssProvider();
provider.LoadFromData("GtkWindow {color:red; background-color:blue;}");
Gtk.StyleContext.AddProviderForScreen(Gdk.Screen.Default, provider, 800); 

But I still can't get the Window to be a different colour.

Any examples for css styling for Window and Buttons etc would be much appreciated.

I'm currently using Windows 10 and dotnet core 3.1

Many thanks,
Chris

**Comment by badcel** [comment]
Hey, I made the border of a button red with a separate CSS file and adding the CSS class to the style context:

Part 1: https://github.com/badcel/BindingSharp/blob/master/BindingSharp/Gtk/WidgetExtension.cs

Part 2: https://github.com/badcel/BindingSharp/blob/master/BindingSharp/Gtk/BindStyleContextToNotifyDataErrorInfo.cs

CSS: https://github.com/badcel/BindingSharp/blob/master/BindingSharp/Resources/invalid.css

Tested on Linux.

**Comment by harry-cpp** [comment]
Assuming you read some c code for it and you know what you wanna do, here is a snippet from one of my projects:

```c#
var provider = new CssProvider();

var data = " .launcher_box { background-color: @theme_base_color; border-style: solid; border-width: 1px; border-color: @borders; border-radius: 0.25em 0.25em; }";
provider.LoadFromData(data);

Gtk.StyleContext.AddProviderForScreen(Gdk.Screen.Default, provider, 800);

_boxRecents.StyleContext.AddClass("linked");
_boxRecents.StyleContext.AddClass("launcher_box");
```

**Comment by harry-cpp** [comment]
> CSS: https://github.com/badcel/BindingSharp/blob/master/BindingSharp/Resources/invalid.css

@badcel Any reason you did not use `destructive-action`?

See: https://wiki.gnome.org/HowDoI/Buttons

**Comment by badcel** [comment]
@harry-cpp  Thank you I didn't know of it

**Comment by cpt1971** [comment]
Thank you all very much for your help. I got it working using both the C# and C++ examples. Ultimately I'm looking to write a wrapper around GtkSharp which can be used cross platform for PowerShell v7.
