### ISSUE TITLE
EntryCompletion - MatchSelected & CursorOnMatch events 

### ISSUE THREAD

**Issue by awittaker** [GtkSharp/GtkSharp#128]
I'm trying to use the [match-selected](https://developer.gnome.org/gtk3/stable/GtkEntryCompletion.html#GtkEntryCompletion-match-selected) & [cursor-on-match](https://developer.gnome.org/gtk3/stable/GtkEntryCompletion.html#GtkEntryCompletion-cursor-on-match) signals in:
[GtkSharp Samples -> Entry -> Completion Entry](https://github.com/GtkSharp/GtkSharp/blob/1a76bf56cb5b50ab554a89512accec6bb3d2c97c/Source/Samples/Sections/Widgets/EntrySection.cs#L113-L150)

I've added these lines, but they are not firing...
```
completion.MatchSelected += (sender, e) => ApplicationOutput.WriteLine(sender, "MatchSelected");
completion.CursorOnMatch += (sender, e) => ApplicationOutput.WriteLine(sender, "CursorOnMatch");
```

NB: If I derive from EntryCompletion I can successfully override OnMatchSelected

What am I missing?

Cheers.

**Comment by harry-cpp** [comment]
90% sure you need to make an actual method and add `[GLib.ConnectBefore]` attribute to it.

**Comment by awittaker** [comment]
Confirmed thanks Harry as tested below.

How do I determine when I need to use `[GLib.ConnectBefore] `?

`completion.MatchSelected += CompletionOnMatchSelected;` 
...
```
[GLib.ConnectBefore]
private void CompletionOnMatchSelected(object o, MatchSelectedArgs args)
{
    ApplicationOutput.WriteLine(o, "MatchSelected");
}
```

**Comment by harry-cpp** [comment]
> How do I determine when I need to use `[GLib.ConnectBefore] `?

When you want to hook up an event before some other default behavior happens.
