### ISSUE TITLE
GDK Seat API not working

### ISSUE THREAD

**Issue by volte** [GtkSharp/GtkSharp#131]
A lot of the keyboard and pointer related APIs from before GTK 3.20 have been marked deprecated (both in GTK+ and GtkSharp) in favour of the [GDK Seat API](https://developer.gnome.org/gdk3/stable/GdkSeat.html). However, when I try to use the seat functions, I find that the resulting seat object is always null and generally the program crashes soon after. The old deprecated APIs like `Window.GetPointer` still appear to work fine, so they can be used as a workaround.

Stepping through some of the internals, the problem seems to be that in (for example) the Display.DefaultSeat implementation, the `ObjectManager.CreateObject` is called on the raw pointer returned by `gdk_display_get_default_seat` which looks up the corresponding type to construct and comes up with `Gdk.SeatDefault`. That class is a subclass of `Opaque`, not of `Object`, but it gets coerced with `as Object` anyway, resulting in a null reference being returned.

Here's a minimal example of reproducing the issue - just click on the window that appears. I've tried this on both the earliest and the latest version of GtkSharp available on NuGet with no difference. 

I'm using Windows 10 and .NET Core 3.0.

```
using System;
using Gdk;
using Application = Gtk.Application;
using Window = Gtk.Window;

class Program {
  [STAThread]
  static void Main(string[] args) {
    Application.Init();

    var window = new Window("Test");
    window.Show();

    window.ButtonPressEvent += (o, eventArgs) => {
      var defaultSeat = Display.Default.DefaultSeat;
      var eventSeat = eventArgs.Event.Device.Seat;

      Console.WriteLine($"defaultSeat == {defaultSeat}");
      Console.WriteLine($"eventSeat == {eventSeat}");
    };

    Application.Run();
  }
}
```

Output:
```
defaultSeat ==
eventSeat ==
Exception code=0xc0000005 flags=0x0 at 0x00007FFB2D04A839. Access violation - attempting to read data at address 0x0000000000000000
Marshaling button-press-event signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt64(IntPtr ptr, Int32 ofs)
   at System.Runtime.InteropServices.Marshal.ReadIntPtr(IntPtr ptr)
   at GLib.GType.ValFromInstancePtr(IntPtr handle)
   at GLib.ObjectManager.GetTypeOrParent(IntPtr obj)
   at GLib.ObjectManager.CreateObject(IntPtr raw)
   at GLib.Object.GetObject(IntPtr o, Boolean owned_ref)
   at GLib.Object.GetObject(IntPtr o)
   at Gdk.Display.get_DefaultSeat()
   at Program.<>c.<Main>b__0_0(Object o, ButtonPressEventArgs eventArgs) in C:\temp\GtkTest\GtkTest\Program.cs:line 15
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at Gtk.Application.Run()
   at Program.Main(String[] args) in C:\temp\GtkTest\GtkTest\Program.cs:line 22
```

**Comment by awittaker** [comment]
I tested this in PyGObject... it's also reporting that `gdk_display_get_default_seat` is returning a GdkSeatDefault... but it does seem to behave as a GdkSeat.
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
from gi.repository import Gdk

class MyWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title="Hello World")

        self.button = Gtk.Button(label="Click Here")
        self.button.connect("clicked", self.on_button_clicked)
        self.add(self.button)

    def on_button_clicked(self, widget):
        seat = self.get_display().get_default_seat()
        kb = seat.get_keyboard()
        print(str(type(seat)) + " --- " + str(type(kb)))


win = MyWindow()
win.connect("destroy", Gtk.main_quit)
win.show_all()
Gtk.main()
```
Output:
`<class '__gi__.GdkSeatDefault'> --- <class 'gi.repository.GdkX11.X11DeviceXI2'>`

**Comment by awittaker** [comment]
It appears that GdkSeatDefault is a child GType of GdkSeat.
Digging through the Gdk source, I found that GdkSeat has this flag set:
[G_TYPE_FLAG_ABSTRACT](https://developer.gnome.org/gobject/stable/gobject-Type-Information.html#GTypeFlags)

The gdk_display_get_default_seat() call is returning a GdkSeatDefault, so the GetTypeOrParent() call in [ObjectManger.CreateObject()](https://github.com/GtkSharp/GtkSharp/blob/1a76bf56cb5b50ab554a89512accec6bb3d2c97c/Source/Libs/GLibSharp/ObjectManager.cs#L33-L50) is returning the GdkSeatDefault Type...
```
		public static GLib.Object CreateObject (IntPtr raw)
		{
			if (raw == IntPtr.Zero)
				return null;

			Type type = GetTypeOrParent (raw);
                        ...
```
However if I hack GetTypeOrParent() to force the return of the _parent_ of GdkSeatDefault, we get a Gdk.Seat successfully.

I suspect that the GType.LookupType call in 
[ObjectManger.GetTypeOrParent](https://github.com/GtkSharp/GtkSharp/blob/1a76bf56cb5b50ab554a89512accec6bb3d2c97c/Source/Libs/GLibSharp/ObjectManager.cs#L70-L84) should not be recognizing GdkSeatDefault as a valid type (so the parent is returned instead)...
```
		static Type GetTypeOrParent (IntPtr obj)
		{
			IntPtr typeid = GType.ValFromInstancePtr (obj);
			if (typeid == GType.Invalid.Val)
				return null;

			Type result = GType.LookupType (typeid);
                         ...
```
