### ISSUE TITLE
Memory Leak caused by not removing Glib TimeoutHandlers from dictionary

### ISSUE THREAD

**Issue by midmohan** [GtkSharp/GtkSharp#135]
The FinalizerInfo class generated by OpaqueGen.cs doesnt remove the TimeoutHandler Ids added to the static dictionary **private static IDictionary<uint, SourceProxy> source_handlers** in Source.cs .
This would lead to the memory growing continuously with each source_handler added. Could see it filling up GBs in matter of few hours when used with Gstreamer pipelines and objects created with Gstreamer-Sharp bindings for C#

Raising a PR also. Can somebody point out if there is any workaround for this. 

Would the one refereed below be useful?
https://github.com/GtkSharp/GtkSharp/issues/82

**Comment by midmohan** [comment]
![Gsttimeout](https://user-images.githubusercontent.com/27757402/74650485-c2d73d80-5179-11ea-8807-08d00e35ebe7.JPG)

**Comment by sdroege** [comment]
See https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/issues/35 and https://github.com/GLibSharp/GtkSharp/pull/45

**Comment by knocte** [comment]
So can we apply a similar fix to https://github.com/GLibSharp/GtkSharp/pull/45/files in this repo?

**Comment by knocte** [comment]
Closed because of a fix or...?

**Comment by knocte** [comment]
Putting the link here https://github.com/GtkSharp/GtkSharp/pull/136

**Comment by harry-cpp** [comment]
Oh, it was never linked, didn't notice it, thanks.
