### ISSUE TITLE
browser widget

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [GtkSharp/GtkSharp#137]
do you guys have a browser widget it's needed in ryujinx project for an offline applet for games for manuals and accepting *Licensing Agreements

**Comment by harry-cpp** [comment]
Duplicate of: https://github.com/GtkSharp/GtkSharp/issues/109

TLDR. No Webkit 2 support on Windows :/ Technically I can setup a repo with webkit 1, but than Linux distros are missing a package for it. I really have no good solution.
