### ISSUE TITLE
Platform detection fails when running with mono from Linux

### ISSUE THREAD

**Issue by borgdylan** [GtkSharp/GtkSharp#14]
When targeting net461 to run on Mono, P/Invokes are trying to access kernel32.dll. Things seem to be alright if running on .NET Core 2.0. Is the P/Invoke code doing detection based on runtime?

**Comment by cra0zy** [comment]
> Is the P/Invoke code doing detection based on runtime?

It's using RuntimeInformation.IsOSPlatform, I'll look into this right now.

**Comment by cra0zy** [comment]
Build bot is cooking a new release, it should be done in around half an hour.

**Comment by cra0zy** [comment]
You can, for the most part, safely ignore the warnings, some functions do not exist on other platforms, and some functions do not exist on lower versions of Gtk. The warnings are still useful if bugs are found so I left them on.
