### ISSUE TITLE
Build for net45

### ISSUE THREAD

**Issue by elmar69** [GtkSharp/GtkSharp#140]
How can GtkSharp libs be used in an net45 project?

**Comment by harry-cpp** [comment]
I don't plan on supporting older versions of .NET Framework.

**Comment by harry-cpp** [comment]
PS. If you have any reason why you thing I should, feel free to add them in here.

**Comment by VisualMelon** [comment]
This would be of utility to the OxyPlot project, as it would allow us to keep NET Framework 4.5.1 support if/when we switch to this library (https://github.com/oxyplot/oxyplot-gtksharp/pull/10).

I have a [branch with 4.5.1](https://github.com/VisualMelon/GtkSharp/tree/net451) support, though I'm not sure whether or not I've broken the packages (can't get them to work out of myget). I haven't properly tested it (I don't know how) but I've not noticed any regressions. The only net451 specific code change is to include the nuget version of `ValueTuple` in the example project. I'm more than happy to work on this further if it helps.

**Comment by hol430** [comment]
Bump. Any update on this? I'm happy to help if I can. I can't find any tests in this repo, but I've had a play with the sample application on the net45 branch and haven't noticed any problems.
