### ISSUE TITLE
Probably invalid signature for Gtk.Application.SetAccelsForAction

### ISSUE THREAD

**Issue by amka** [GtkSharp/GtkSharp#142]
Hello! I'm not sure of it but it looks like `SetAccelsForAction` method has invalid signature in case of its parameters: `accels` has to be a string array instead of just `string`. I tried to add it to my app and got nothing then crash.

According to [Valadoc]( https://valadoc.org/gtk+-3.0/Gtk.Application.set_accels_for_action.html) it is an  array. Correct me if I'm wrong.

Thanks!

**Comment by awittaker** [comment]
I found a few like this recently - I'll investigate.
EG:
#132 Change GtkWidget.ListActionPrefixes() to return string[]
