### ISSUE TITLE
"Double click" the exe

### ISSUE THREAD

**Issue by xidod** [GtkSharp/GtkSharp#143]
If I build a simple hello world app with `dotnet publish` I can open the window only from terminal with `./app`.
I build the app on linux and i tried with Exe output and also WinExe.

I'm missing something?

**Comment by amka** [comment]
You may use [dotnet-wrap](https://github.com/Hubert-Rybak/dotnet-warp) to create one-file executable or just set
```bash
chmod +x ./app
```
and then run it with double-click.

**Comment by xidod** [comment]
I've already done `chmod +x app` but nothing change.
dotnet is installed correctly because if I run the app from command line works.

@amka if I can ask you, in what distribution you can run the app with double click?

**Comment by amka** [comment]
Yikes!
I use ElementaryOS 5.1 and tried in both GNOME and Pantheon.
It works like a charm from Nautilus and Files.

For example .cproj file from one I've tested it:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GtkSharp" Version="3.22.25.*" />
  </ItemGroup>

</Project>
```
Just run a `dotnet publish` and then start the app with a double-click.

**Comment by xidod** [comment]
Found the problem :)
It seems dotnet want a global installation for this kind of stuff to /usr/share/dotnet
My dotnet installation is $HOME/dotnet
Thanks for your time @amka
