### ISSUE TITLE
libhandy support

### ISSUE THREAD

**Issue by archanox** [GtkSharp/GtkSharp#144]
Is it at all possible to incorporate libhandy into GtkSharp projects?

https://gitlab.gnome.org/Community/Purism/libhandy
https://source.puri.sm/Librem5/libhandy

**Comment by harry-cpp** [comment]
Duplicate of https://github.com/GtkSharp/GtkSharp/issues/104

**Comment by badcel** [comment]
Hey I'm currently working on an alternative implementation of several gir libraries (including libhandy). 

For libhandy there ist currently only one example class (pagination). Adding new API ist very easy.

If you are interested take a look: https://github.com/GirCore/gir.core

Any help is welcome.
