### ISSUE TITLE
add gtksharpglue

### ISSUE THREAD

**Issue by lytico** [GtkSharp/GtkSharp#146]
gtksharpglue is missing.
code is here:
https://github.com/mono/gtk-sharp/tree/master/gtk/glue

how to deal with it?

1. add as library; but then GtkSharp is not "standalone" any more
2. reimplement as managed code

your suggestions?

**Comment by harry-cpp** [comment]
Its not missing, it got removed/reimplemented, there should be no more calls left to any glue library.

**Comment by lytico** [comment]
thanks for the hint!

i guess changes are here?:
https://github.com/GtkSharp/GtkSharp/commit/90bbc67f3c771ac1b72275c1ac47c60752d165a6

**Comment by harry-cpp** [comment]
Partially, there were more commits I think, generator used to make some glue code as well iirc.

**Comment by lytico** [comment]
is there any place to document api differences and hints https://github.com/mono/gtk-sharp vs https://github.com/GtkSharp/GtkSharp?

**Comment by harry-cpp** [comment]
gtk-sharp supports Gtk 3.0, while GtkSharp supports Gtk 3.22, just by that there are already a lot of API differences present, I don't thing it would be a good idea to try and keep any type of backwards compatibility or api difference table.

**Comment by lytico** [comment]
i have a sort of "Porting Guide" in mind
and willing to contribute that

i am trying to port
https://github.com/mono/xwt
to GtkSharp, and there are a lot of low-level adoptions to make.

currently i'm stuck with the problem, how to subclass Gtk.Container
as in GtkSharp Gtk.Container Forall is not virtual

**Comment by harry-cpp** [comment]
Feel free to implement that method fully on the managed side if you need it.

**Comment by lytico** [comment]
i felt so free:
![grafik](https://user-images.githubusercontent.com/1479980/78315678-ffaa9880-755d-11ea-9d4b-5b56d4b93801.png)

took me hours; example is from:
https://github.com/mono/gtk-sharp/commits/2.99.3/sample/PolarFixed.cs

code is here, but i think i test it harder before committing:

https://github.com/lytico/GtkSharp/blob/lytico_customcontainer/Source/Libs/GtkSharp/Sandbox/Container.Forall.cs
