### ISSUE TITLE
No error crash when trying to create Image

### ISSUE THREAD

**Issue by Kangaroux** [GtkSharp/GtkSharp#147]
If I run the following code the app closes unexpectedly with exit code 0:

```C#
using Gtk;

class GtkTest
{
    static void Main()
    {
        Application.Init();

        var window = new Window("Hello");
        var img = new Image("myimage.png");

        window.Add(img);
        window.ShowAll();

        Application.Run();
    }
}
```

If I try and assign the Pixbuf manually it still crashes with no error:

```C#
var img = new Image();
img.Pixbuf = new Gdk.Pixbuf("myimage.png");
```

And if I try passing it the image data directly it also crashes:

```C#
var img = new Image();
var data = System.IO.File.ReadAllBytes("myimage.png");
img.Pixbuf = new Gdk.Pixbuf(data);
```

If the image file doesn't exist, it works as expected. I tried different image extensions thinking it was a problem specifically with the png I was trying but I got the same results.

Ubuntu 19.10, GNOME X11, .NET 3.0

**Comment by harry-cpp** [comment]
I am unable to reproduce your issue, can you give me the image you were trying to use?

**Comment by Kangaroux** [comment]
This is the png I was trying. I also tried a different image (jpg).

![note_1](https://user-images.githubusercontent.com/2302541/78318633-41721980-7533-11ea-98d6-b1bae519f409.png)

**Comment by Kangaroux** [comment]
Out of curiosity, can you upload your `bin/` that includes the DLLs?

**Comment by Kangaroux** [comment]
I created a new project and it works there. Cleaning the `bin/` and `obj/` folders in the broken project didn't fix it. The `.csproj` file is identical (except for a `ManagedBass` reference which shouldn't have an effect).

New, working project:

```
$ dotnet list package
Project 'xxx' has the following package references
   [netcoreapp3.0]: 
   Top-level Package      Requested   Resolved  
   > GtkSharp             3.22.25.*   3.22.25.74
```

Old project:

```
$ dotnet list package
Project 'yyy' has the following package references
   [netcoreapp3.0]: 
   Top-level Package      Requested   Resolved  
   > GtkSharp             3.22.25.*   3.22.25.74
   > ManagedBass          2.0.4       2.0.4     
   > ManagedBass.Fx       2.0.1       2.0.1
```

I'll close this for now and reopen if I run into the same issue.

**Comment by Kangaroux** [comment]
I found the culprit.

It was only crashing while in VScode. `gdb` revealed a segfault due to a missing file.

There are some ENV vars that VScode injects into the terminal. I'm not sure what or where these are getting injected. However, the issue appears to be with the ENV var `GDK_PIXBUF_MODULE_FILE`. If I unset that ENV var it works fine. Considering that var isn't set at all in a normal terminal window and it works fine, I'm going to assume that unsetting it does no harm.
