### ISSUE TITLE
Unable to run basic template project on Linux

### ISSUE THREAD

**Issue by draek** [GtkSharp/GtkSharp#149]
Ive setup a new Ubuntu 20.04 machine with a clean install.

I am able to build, but when I run the application I get:

/snap/dotnet-sdk/current/dotnet /home/user/RiderProjects/GtkApplication/GtkApplication/bin/Debug/netcoreapp3.0/GtkApplication.dll
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at GtkApplication.Program.Main(String[] args) in /home/user/RiderProjects/GtkApplication/GtkApplication/Program.cs:line 11

Process finished with exit code 134.

Yet I am able to run this same new project in Windows with GTK installed through the instructions on this github wiki.

Funny how it doesn't seem to work in Linux. I have gtk3 dev packages installed, I have glade 3.22, the works. But it doesnt seem to find the GTK libraries?

Oh for the record, I tested this with Rider and manually using dotnet command line.

**Comment by badcel** [comment]
Could you execute the following command and report the output to show the current cache of the dynamic linker?
`ldconfig -p | grep libgtk-3`

and in the folder of your app, could you run the following command to start the app and show which libraries it tries to load?
`LD_DEBUG=libs dotnet run 2>&1 >/dev/null | grep libgtk`

**Comment by draek** [comment]
Ok, so the first command shows:
	libgtk-3.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgtk-3.so.0
	libgtk-3.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libgtk-3.so

The second one I had some trouble with what you gave me but I believe the output we are looking for is:

      8168:	find library=libgtk-3.so.0 [0]; searching
      8168:	 search path=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu:/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gnu		(RPATH from file /snap/dotnet-sdk/69/dotnet)
      8168:	  trying file=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu/libgtk-3.so.0
      8168:	  trying file=/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu/libgtk-3.so.0
      8168:	  trying file=/snap/core18/current/lib/x86_64-linux-gnu/libgtk-3.so.0
      8168:	 search cache=/etc/ld.so.cache
      8168:	  trying file=/lib/x86_64-linux-gnu/libgtk-3.so.0
      8168:	
      8168:	find library=libgdk-3.so.0 [0]; searching
      8168:	 search path=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu:/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gnu		(RPATH from file /snap/dotnet-sdk/69/dotnet)
      8168:	  trying file=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu/libgdk-3.so.0
      8168:	  trying file=/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu/libgdk-3.so.0
      8168:	  trying file=/snap/core18/current/lib/x86_64-linux-gnu/libgdk-3.so.0
      8168:	 search cache=/etc/ld.so.cache
      8168:	  trying file=/lib/x86_64-linux-gnu/libgdk-3.so.0

And:

      8168:	/snap/core18/current/lib/x86_64-linux-gnu/libm.so.6: error: version lookup error: version `GLIBC_2.29' not found (required by /lib/x86_64-linux-gnu/libgtk-3.so.0) (fatal)
      8168:	find library=libgtk-3-0.dll [0]; searching
      8168:	 search path=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu:/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gnu		(RPATH from file /snap/dotnet-sdk/69/dotnet)
      8168:	  trying file=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu/libgtk-3-0.dll
      8168:	  trying file=/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu/libgtk-3-0.dll
      8168:	  trying file=/snap/core18/current/lib/x86_64-linux-gnu/libgtk-3-0.dll
      8168:	 search cache=/etc/ld.so.cache
      8168:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      8168:	  trying file=/lib/x86_64-linux-gnu/libgtk-3-0.dll
      8168:	  trying file=/usr/lib/x86_64-linux-gnu/libgtk-3-0.dll
      8168:	  trying file=/lib/libgtk-3-0.dll
      8168:	  trying file=/usr/lib/libgtk-3-0.dll
      8168:	
      8168:	find library=libgtk-3.so.0 [0]; searching
      8168:	 search path=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu:/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gnu		(RPATH from file /snap/dotnet-sdk/69/dotnet)
      8168:	  trying file=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu/libgtk-3.so.0
      8168:	  trying file=/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu/libgtk-3.so.0
      8168:	  trying file=/snap/core18/current/lib/x86_64-linux-gnu/libgtk-3.so.0
      8168:	 search cache=/etc/ld.so.cache
      8168:	  trying file=/lib/x86_64-linux-gnu/libgtk-3.so.0
      8168:	
      8168:	find library=libgdk-3.so.0 [0]; searching
      8168:	 search path=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu:/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gnu		(RPATH from file /snap/dotnet-sdk/69/dotnet)
      8168:	  trying file=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu/libgdk-3.so.0
      8168:	  trying file=/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu/libgdk-3.so.0
      8168:	  trying file=/snap/core18/current/lib/x86_64-linux-gnu/libgdk-3.so.0
      8168:	 search cache=/etc/ld.so.cache
      8168:	  trying file=/lib/x86_64-linux-gnu/libgdk-3.so.0

Then finally:

      8168:	/snap/core18/current/lib/x86_64-linux-gnu/libm.so.6: error: version lookup error: version `GLIBC_2.29' not found (required by /lib/x86_64-linux-gnu/libgtk-3.so.0) (fatal)
      8168:	find library=libgtk-3.0.dylib [0]; searching
      8168:	 search path=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu:/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gnu		(RPATH from file /snap/dotnet-sdk/69/dotnet)
      8168:	  trying file=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu/libgtk-3.0.dylib
      8168:	  trying file=/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu/libgtk-3.0.dylib
      8168:	  trying file=/snap/core18/current/lib/x86_64-linux-gnu/libgtk-3.0.dylib
      8168:	 search cache=/etc/ld.so.cache
      8168:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      8168:	  trying file=/lib/x86_64-linux-gnu/libgtk-3.0.dylib
      8168:	  trying file=/usr/lib/x86_64-linux-gnu/libgtk-3.0.dylib
      8168:	  trying file=/lib/libgtk-3.0.dylib
      8168:	  trying file=/usr/lib/libgtk-3.0.dylib
      8168:	
      8168:	find library=gtk-3.dll [0]; searching
      8168:	 search path=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu:/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu:/snap/core18/current/lib/x86_64-linux-gnu		(RPATH from file /snap/dotnet-sdk/69/dotnet)
      8168:	  trying file=/snap/dotnet-sdk/69/lib/x86_64-linux-gnu/gtk-3.dll
      8168:	  trying file=/snap/dotnet-sdk/69/usr/lib/x86_64-linux-gnu/gtk-3.dll
      8168:	  trying file=/snap/core18/current/lib/x86_64-linux-gnu/gtk-3.dll
      8168:	 search cache=/etc/ld.so.cache
      8168:	 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
      8168:	  trying file=/lib/x86_64-linux-gnu/gtk-3.dll
      8168:	  trying file=/usr/lib/x86_64-linux-gnu/gtk-3.dll
      8168:	  trying file=/lib/gtk-3.dll
      8168:	  trying file=/usr/lib/gtk-3.dll

Then at the end:

System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at GtkApplication.Program.Main(String[] args) in /home/philippe/RiderProjects/GtkApplication/GtkApplication/Program.cs:line 11
/

There's a few blocks that show something wrong finding GLIBC 2.29 it seems??

**Comment by draek** [comment]
Also if it helps:

ldd (Ubuntu GLIBC 2.31-0ubuntu6) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by badcel** [comment]
Are you using something related to snap?

Is it working if you just create a minimal project like:

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GtkSharp" Version="3.22.25.74" />
  </ItemGroup>

</Project>
`

**Comment by draek** [comment]
Oh I'm not doing anything with Snap. Snap is used to install almost everything in Ubuntu now, including dotnet core. Thats why you are seeing that. Are you asking if i can run a Dot Net Core project that is created from CLI? yes I am able to. Its only once I try and run the app with GtkSharp that I get the above errors.

In this case i am running the plain GtkSharp template using the dotnet CLI as a project.

**Comment by harry-cpp** [comment]
Snap sandboxes stuff it runs, so of course native libraries will not be found as snap apps don't have access to the host system.

Closing as this is not an issue on our side.

**Comment by draek** [comment]
Thanks for pointing that our Harry-cpp, I have removed the snap installation of dotnet and I have installed dotnet 3.1 sdk manually using the Microsoft bash script.

This worked in fixing the issue. Snap is very bad choice for Ubuntu.

**Comment by badcel** [comment]
If you want to get updates, you could use the Microsoft repository:

https://docs.microsoft.com/de-de/dotnet/core/install/linux-package-manager-ubuntu-1910

**Comment by draek** [comment]
So unfortunately the 19.10 repo does not work with 20.04 Focal Fossa. There is an incompatibility with something that doesn't let it install yet. I assume that packages for this release will be coming soon. Until then I will need to  do it this way until proper packages come out. Thanks for all your help getting to the root of this.

**Comment by gitfoxi** [comment]
I have the same issue. Except I'm on a Mac.

I can run just fine if I build with msbuild and run mono, but when I build and run with dotnet core:

Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at GtkDotNetCore.Program.Main(String[] args) in /Users/m/repos/slt_prod_v14/Easy/Astris/PingAstrisApp/GtkDotNetCore/Program.cs:line 11

**Comment by gitfoxi** [comment]
brew install gtk+3

fixes it

**Comment by lytico** [comment]
https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Mac

if you want to use sourceview:

brew install gtksourceview4
