### ISSUE TITLE
Gdk.Screen: SizeChanged, CompositedChanged, MonitorsChanged are signals

### ISSUE THREAD

**Issue by lytico** [GtkSharp/GtkSharp#152]
https://developer.gnome.org/gdk3/stable/GdkScreen.html#GdkScreen-size-changed

but they are implemented as methods:

Source/Libs/GdkSharp/GdkSharp-api.xml

```
    <object name="Screen" cname="GdkScreen" parent="GObject">
      <class_struct cname="GdkScreenClass">
     ...
        <method vm="size_changed" />
        <method vm="composited_changed" />
        <method vm="monitors_changed" />

```

in https://github.com/mono/gtk-sharp it's declared as follow:
gdk/gdk-api.raw

```
<object name="Screen" cname="GdkScreen" parent="GObject">
      <class_struct cname="GdkScreenClass">
      ...

        <method signal_vm="size_changed" />
        <method signal_vm="composited_changed" />
        <method signal_vm="monitors_changed" />
```

Should i change this manually, or is GdkSharp-api.xml generated somehow?

**Comment by harry-cpp** [comment]
The `-api.xml` files are generated, but I have no intention on using the generator for Gtk 4+ so feel free to modify it by hand.

https://www.mono-project.com/docs/gui/gtksharp/gapi/

**Comment by lytico** [comment]
done with: https://github.com/GtkSharp/GtkSharp/pull/157
