### ISSUE TITLE
No NullReferenceException thrown after Application.Init (CPU goes into overdrive)

### ISSUE THREAD

**Issue by NogginBops** [GtkSharp/GtkSharp#155]
I have a problem in my code where null pointer/reference exceptions don't get thrown after calling `Application.Init()`.

The smallest reproducible sample is:
```cs
static void Main(string[] args)
{
    Application.Init();
    ((object)null).ToString();
}
```
Expected behavior is throwing a `NullReferenceException`.
But what happens instead what happens is that the CPU usage spikes (on all cores).
![image](https://user-images.githubusercontent.com/3778357/79288487-2bffd680-7ec7-11ea-85a3-ab998b4a1a1b.png)
I've marked with red where the exception should happen (but instead it starts to use a lot of CPU).

When the program goes into this state I can't really do anything other than close the program. Pausing in the debugger locks up visual studio and it becomes unresponsive. So I can't really figure out what the CPU is doing and what it is stuck at.

This problem only happens when I run the program in the visual studio debugger. If I run the program with `Debugger -> Start Without Debugging` I get the following output:
```
Exception code=0xc0000005 flags=0x0 at 0x00007FFDA90FA859. Access violation - attempting to read data at address 0x0000000000000000
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at LogikUI.Program.Main(String[] args) in .\Program.cs:line 25
```

It doesn't matter if I surround the null reference access with:
```cs
try {
    ((object)null).ToString();
} catch (NullReferenceException) 
{
    // Print something
}
```
I don't ever get to the `catch` if I'm in the debugger, but if I run the code as described above without the debugger I get the exception and it gets caught properly.

This seems like a really weird problem and I'm not entirely sure what could cause this. I tried to source dive a little bit into `Application.Init` but I couldn't find anything super obvious.

Is this a known issue? Are there any workarounds?

**Comment by hol430** [comment]
This issue should now be fixed if you target latest GtkSharp.
