### ISSUE TITLE
Pango.FontFamily.Faces crashes

### ISSUE THREAD

**Issue by cwensley** [GtkSharp/GtkSharp#159]
The `Pango.FontFamily.Faces` API crashes or corrupts memory on Windows or macOS, which makes testing hard.

This is used [here](https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/Drawing/FontFamilyHandler.cs#L17)

**Comment by harry-cpp** [comment]
It should work on Windows last time I checked, not on macOS tho.
