### ISSUE TITLE
GSettings Schemas are not included in GtkSharp.Win32

### ISSUE THREAD

**Issue by Nihlus** [GtkSharp/GtkSharp#16]
In order for applications that depend on gsettings schemas to run on Windows, compiled schemas must be bundled with the application or installed on the system. 

These files are not included in the binary package.

**Comment by cra0zy** [comment]
As stated in the README, the nugets only provide the wrapper, you should install Gtk into your system: https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Windows

Also if you are talking about the nuget package named "GtkSharp.Win32", it's not owned by us.

**Comment by Nihlus** [comment]
Ah, I see.

**Comment by cra0zy** [comment]
PS. Feel free to open up a feature request issue on providing native dependency for Windows in the nugets, if there is actual demand for it I don't mind setting it up.

**Comment by Nihlus** [comment]
That would be great, honestly! Since GTK is typically already in place on Linux systems, it would be a real boon to have a native dependency package for Windows.
