### ISSUE TITLE
How to hook up Forall delegate

### ISSUE THREAD

**Issue by Dadoum** [GtkSharp/GtkSharp#160]
I have a class that inherits Container, and I want add a ForallCallback.

Under gtk-sharp 2.x, it is made like this:
```cs
public override void Forall(Callback callback)
{
    base.Forall(callback);
}
```

Under GtkSharp 3.X, I can't since Delegate is private.

**Comment by harry-cpp** [comment]
Should be implemented in #150, however the nuget release does not have the last few changes.
