### ISSUE TITLE
Packaging GTK# application problem

### ISSUE THREAD

**Issue by zejtin** [GtkSharp/GtkSharp#163]
GTK# is working pretty fine with me on all platforms :) but I have issue on creating packaged binaries (tar) application on Linux, I'm using latest MonoDevelop.
It fails no matter what configuration I select, while it works from Monodevelop without problems.

Am I missing something here? Except for TAR.GZ, is there a way to build to DEB or RPM?

**Comment by harry-cpp** [comment]
This isn't really an issue with GtkSharp so I'll close it, but feel free to post more questions in here and I'll respond if I know the answer.

As for how to publish your app, assuming you are targeting `netcoreapp` you'll want to run a command like:
```
dotnet publish -r linux-x64
```
which will output a framework independent binary, which you can zip or package up however you want. Also test out trimming your output application as described in the links bellow.

Publishing app docs: https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli
Trim docs: https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained

**Comment by zejtin** [comment]
Thanks for the answer! Somehow I did not get the notification :/

But this is the command for .Net Core runtime I'm using Mono as my runtime, don't have Core installed at all on Linux.

I've followed this tutorial here for adding GTK to Xamarin.Forms project:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/gtk?tabs=windows 

Thanks in advance
