### ISSUE TITLE
Is there any plan to port glade-sharp on .net core? 

### ISSUE THREAD

**Issue by deveshbahuguna** [GtkSharp/GtkSharp#169]
I have been working on .net core project with UI on gtk sharp 
but i could not find  a way to create UI in glade or xml file.
Thus below are my questions:
1) Are there any plans to port glade-sharp for .net core?
2) Will there be a release for gtk 4.0 or gtk 3.9 in future if possible could one provide the
estimate as well.

Thanks

**Comment by harry-cpp** [comment]
I have no idea what glade-sharp is, so no to that.

As for using .glade files, that is already supported, just checkout the default templates, they even have item templates: https://www.nuget.org/packages/GtkSharp.Template.CSharp/

I'm gonna get to GtkSharp 4 once I'm done with some MonoGame related stuff.

**Comment by deveshbahuguna** [comment]
Thanks for your earlier reply but if possible
Can you provide some rough estimation like  it would be ready at end of 2020 or mid 2021

One more thing...Can I also contribute to this project?..If so how?

**Comment by nguyenkien** [comment]
Check this out:
https://github.com/GtkSharp/GtkSharp/tree/develop/Source/Templates/GtkSharp.Template.CSharp/content/GtkSharp.Window.CSharp

**Comment by harry-cpp** [comment]
> Thanks for your earlier reply but if possible
> Can you provide some rough estimation like it would be ready at end of 2020 or mid 2021

No ETA

> One more thing...Can I also contribute to this project?..If so how?

If you are able to fix any existing issues, that would be helpful.

> Check this out:
> https://github.com/GtkSharp/GtkSharp/tree/develop/Source/Templates/GtkSharp.Template.CSharp/content/GtkSharp.Window.CSharp

Or even better, just install the template (there is also MonoDevelop / VS Mac extension in the Releases on GitHub, I think I forgot to write it down in the README):
```
# install template
dotnet new -i GtkSharp.Template.CSharp

# create gtk app
dotnet new gtkapp

# make a gtk widnow or whatnot
dotnet new gtkwindow -n HelloWindow
```

**Comment by lytico** [comment]
glade-sharp source is here:

https://github.com/mono/gtk-sharp/tree/gtk-sharp-2-12-branch/glade

and glade source is here:

https://gitlab.gnome.org/GNOME/glade

**Comment by jcbritobr** [comment]
You can use latest glade wiht msys2. Just install it and you are done.
pacman -S mingw-w64-x86_64-glade

I do my gui works with net core and glade together in windows 10. Works fine.
![image](https://user-images.githubusercontent.com/6579862/103541010-7708b200-4e79-11eb-9a36-d8aad1c6d0ae.png)
