### ISSUE TITLE
Create a native dependency package for Windows

### ISSUE THREAD

**Issue by Nihlus** [GtkSharp/GtkSharp#17]
Currently, the setup process for GTK on Windows is not very kind to end users. It would be great to have an official nuget package which bundles the native dependencies and related files (GSettings schemas and the like) for quick and easy inclusion in C# projects.

There's already an unofficial package on nuget (GtkSharp.Win32), but having an official one would be more preferable.

**Comment by Nihlus** [comment]
After talking with the maintainer of GtkSharp.Win32, they also suggested a feature request for Mac binaries.

**Comment by rivanfebrian123** [comment]
Hi everyone! This issue could be a reason why we've to develop our own framework. Check[ this proposal ](https://github.com/rivanfebrian123/Litesy) out!

**Comment by cra0zy** [comment]
C# already has a way of dealing with native deps, well .NET Core does.

Also this reminds me, I know what I did wrong in my PR, should be able to fix it up a bit later today and merge it \o/

**Comment by Dremor** [comment]
Any news on this PR ?

**Comment by r-ml** [comment]
I suppose 4675d0fa82b28e31c46f85163d922e9b5ef7f281 addresses this...?

I used the sample `gtkapp` modified with `<PackageReference Include="GtkSharp" Version="3.22.25.49" />`, targeting `netcoreapp3.0`, built it on linux using `dotnet publish -c Release -r win10-x64`to try if it ran on a windows machine that doesn't have gtk installed. It failed. \
Am I doing something wrong?

**Comment by cra0zy** [comment]
You need an icon theme, a gtk theme and a schema file, template gtk app should work without those

**Comment by cra0zy** [comment]
Okey, I've just pushed an even better version of it, during the build it will install the needed gtk deps to localappdata/Gtk/3.24 if they are not found there. For publishing I am doing nothing as you should actually choose which files from there you wanna include.
