### ISSUE TITLE
GtkContainerClass::add not implemented for...

### ISSUE THREAD

**Issue by Dadoum** [GtkSharp/GtkSharp#170]
I can't create custom containers since Add is not virtual, so I can't override it.

**Comment by hol430** [comment]
Hi @Dadoum I agree this is kind of strange, but what you can do is override the (virtual) OnAdded method defined in class Container. [This](https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Samples/Sections/Widgets/CustomWidgets/PolarFixed.cs) is an example custom container in the sample project in this repo.

**Comment by Dadoum** [comment]
Yes I fixed it by not invoking the base method
