### ISSUE TITLE
Bad type for WindowAttr.EventMask

### ISSUE THREAD

**Issue by na2axl** [GtkSharp/GtkSharp#171]
Hello there,

I don't know if it is intended, but I've just seen that there is an error with the type of the field `EventMask` in the `WindowAttr` struct. The type is `int` instead of `Gdk.EventMask` (which I think give more sense).

**Comment by zii-dmg** [comment]
There is `Gdk.EventMask Mask` property, it is typed wrapper for `int EventMask` field.

**Comment by na2axl** [comment]
Ok @zii-dmg I see. When I've found the EventMask field I've not searched for another one. But I think having two fields/properties doing the same thing can be a little confusing.
Thanks for the clarification :-)
