### ISSUE TITLE
Update Windows build of Gtk to fix Visual Studio debugger

### ISSUE THREAD

**Issue by AustinWise** [GtkSharp/GtkSharp#172]
When building on Windows, a copy of GTK is downloaded from here:

https://github.com/GtkSharp/Dependencies/blob/master/gtk-3.24.md

The version of GLib included in this package has a [bug](https://gitlab.gnome.org/GNOME/glib/-/issues/2025) that prevents the Visual Studio debugger from catching `NullReferenceException`s. It would be very convenient if this version of GLib was updated to at lest 2.62.6 to get the fix.

Updating GLib should also fix #155.

**Comment by hol430** [comment]
This issue should now be fixed if you target latest GtkSharp.

**Comment by AustinWise** [comment]
@hol430 Thanks, that fixed the problem.
