### ISSUE TITLE
Unable to build and run Samples project

### ISSUE THREAD

**Issue by rnewton5** [GtkSharp/GtkSharp#181]
I am currently unable to build and run the Samples project.

Here's my current setup.
```
Windows 10, 
dotnet --version -> `3.1.201`
gtk installed through MSYS2
"C:\msys64\mingw64\bin" has been added to PATH
```

steps to recreate:
```
git clone git@github.com:GtkSharp/GtkSharp.git
cd GtkSharp/Source/Samples/
dotnet restore
dotnet build
```

The dotnet restore is successful, but the build yields 65 errors.
The output of `dotnet build` can be viewed here: https://pastebin.com/cqknTMBe

Note: I am able to generate a build a project using `dotnet new gtkapp`.

**Comment by badcel** [comment]
Did you build the GtkSharp project, too? The Sample project references the GTKSharp DLLs, which must be successfully build locally.

**Comment by rnewton5** [comment]
@badcel , Thanks for your quick reply! after running the build.ps1 script I am able to successfully build the sample project.

However, running the project throws an exception in the SourceView constructor.

```
Exception thrown: 'System.DllNotFoundException' in GtkSourceSharp.dll
Exception thrown: 'System.TypeInitializationException' in GtkSourceSharp.dll
An unhandled exception of type 'System.TypeInitializationException' occurred in GtkSourceSharp.dll
The type initializer for 'GtkSource.SourceView' threw an exception.
```

any thoughts?

**Comment by badcel** [comment]
There are new bindings for SouceView. Did you install the bindings for GtkSourceView in MSYS?. It should work regarding to this comment: https://github.com/GtkSharp/GtkSharp/pull/173#issuecomment-657913124

**Comment by rnewton5** [comment]
That was it. I am able to run the sample project with no issue at this point. 

I'm going to close this issue now.
Thanks for your help!
