### ISSUE TITLE
Pixbuf memory leak

### ISSUE THREAD

**Issue by JakubKaliszewski** [GtkSharp/GtkSharp#186]
When I use:
```csharp
Gtk.Application.Invoke (delegate
{
    _rawImage.Pixbuf = new Pixbuf(image.ToBytes(".bmp"), image.Width, image.Height);   
});
```
I have huge memory leak. 

My solution is PixbufLoader:
```csharp
Gtk.Application.Invoke (delegate
{
    PixbufLoader loader = new PixbufLoader();
    loader.Write(image.ToBytes(".bmp"));
    _rawImage.Pixbuf = loader.Pixbuf;
    loader.Close();
});
```

**Comment by na2axl** [comment]
There are too much memory leaks when using Pixbuf, there is also an old issue with `Pixbuf.ScaleSimple()` at #112

**Comment by harry-cpp** [comment]
Had to revert the fix as it was causing issues, so reopening this issue.

**Comment by harry-cpp** [comment]
Actually seems the issue might be gone with all the newest changes that happened so I guess I'll re close it.

Open it up if you manage to repro it.
