### ISSUE TITLE
[GtkSourceSharp Nuget] libgtksourceview-4.so.o not found

### ISSUE THREAD

**Issue by mennodeij** [GtkSharp/GtkSharp#188]
I'm trying to use [this NuGet package](https://www.nuget.org/packages/GtkSourceSharp/) on a CentOS 8 distro, but I get the following error
```
System.TypeInitializationException: The type initializer for 'GtkSource.LanguageManager' threw an exception. ---> 
System.DllNotFoundException: GtkSource: libgtksourceview-4-0.dll, libgtksourceview-4.so.0, libgtksourceview-4.0.dylib, gtksourceview-4.dll
```
I do have libgtksourceview-3.0.so.1:
```
> locate libgtksourceview
/usr/lib64/libgtksourceview-3.0.so.1
/usr/lib64/libgtksourceview-3.0.so.1.8.0
```

It looks like gtksourceview-4 is rather new, and not available on any distro except Fedora, http://rpmfind.net/linux/rpm2html/search.php?query=gtksourceview4

It would be nice if this package depended on gtksourceview3, do you think that could be realized?

Many thanks 🙂

**Comment by lytico** [comment]
available for:

https://packages.debian.org/sid/libgtksourceview-4-0

https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/libgtksourceview-4-dev_4.6.0-1_amd64.deb.html 

https://packages.msys2.org/package/mingw-w64-x86_64-gtksourceview4

https://www.archlinux.de/packages/extra/x86_64/gtksourceview4

just to mention the mail distris

**Comment by mennodeij** [comment]
in CentOS 8 there is no such package

**Comment by lytico** [comment]
indeed.
build from sources?

**Comment by mennodeij** [comment]
I've tried that. All kinds of dependies missing on the target machine, like ninja, meson to begin with. Tried pip-install into userspace to get those. Total failure & can't configure the build system with meson. It would be **so much easier** if GtkSourceSharp depended on existing gtksourceview3 instead of gtksourceview4.

**Comment by lytico** [comment]
do you need GtkSourceSharp? or just need to use GktSharp?

**Comment by mennodeij** [comment]
Yes I'm using the sourceview control.

**Comment by lytico** [comment]
maybe here:
http://rpmfind.net/linux/RPM/fedora/30/x86_64/g/gtksourceview4-4.2.0-1.fc30.i686.html

**Comment by lytico** [comment]
don't know if all requirements are on centos 8

**Comment by harry-cpp** [comment]
Gonna close this as this is not on our side.

**Comment by mennodeij** [comment]
I'm sorry but I have to say I'm a bit disappointed here. You're depending on a quite new package that is not in most linux distros, effectively offloading the onto consumers of your framework the burden of getting theirs systems updated. Compound this with the fact that in typical corporate settings updating to the packages that are not on the update stream is not considered sensible policy, and here we are.
