### ISSUE TITLE
What is the relationship between this project and Maui?

### ISSUE THREAD

**Issue by jor1196** [GtkSharp/GtkSharp#189]
Hi, lately I saw Xamarin.Forms now become Maui to fully integrate with .net. Will this project also be linked to Maui?

**Comment by lytico** [comment]
until now, there is no relationship.

i made a first (non working) spike of Maui based on GtkSharp:

https://github.com/lytico/maui/tree/lytico_gtksharp/System.Maui.Platform.GTK

and made this proposal:

https://github.com/dotnet/maui/issues/71

**Comment by lytico** [comment]
starting now, there is relationship:

https://github.com/jsuarezruiz/maui-linux

is based on gtksharp

**Comment by lytico** [comment]
and, there is an implemention of Microsoft.Maui.Graphics.Skia based on gtksharp

https://github.com/dotnet/Microsoft.Maui.Graphics/pull/69

**Comment by lytico** [comment]
and, there will be soon an implementation of  Microsoft.Maui.Graphics - Native based on gtksharp:
https://github.com/dotnet/Microsoft.Maui.Graphics/pull/74
