### ISSUE TITLE
MatchSelected event doesn't fire

### ISSUE THREAD

**Issue by Kejardon** [GtkSharp/GtkSharp#190]
I'm attempting to have a ComboBox with an Entry and an EntryCompletion. Most interactions work (although the UI is a little different for dropdown vs. completion), with the main exception that EntryCompletion can't seem to set the ComboBox's ActiveIter - it only seems to affect the text. I tried to use MatchSelected to manually set ActiveIter, but the MatchSelected event is never fired.

Here's a simplified example. Complet_MatchSelected is never called, but otherwise this mostly works how I'd expect.
[GtkNoEvent.zip](https://github.com/GtkSharp/GtkSharp/files/5163123/GtkNoEvent.zip)

The rest isn't directly part of this issue but I'd appreciate feedback on this too:
Relatedly, I will need to figure something out for a user just typing the full name of an option instead of using the EntryCompletion. It'd be nice if there's a way to grab the best match from EntryCompletion, since it will have already done the filtering I want, but I didn't see a way to do that from a glance. The only thing coming to mind is to repeat its filtering manually when there's an indication the user is done typing to select an option (which might make MatchSelected redundant anyways).

**Comment by hol430** [comment]
Hi @Kejardon, for the first problem, adding a `[GLib.ConnectBefore]` attribute to the Complet_MatchSelected function causes it to receive the event (for me anyway).

As for the second part- you could always just trap the `Changed` event of the Entry and use [EntryCompletion.ComputePrefix()](https://developer.gnome.org/gtk3/stable/GtkEntryCompletion.html#gtk-entry-completion-compute-prefix), which as I understand it computes the best match in the ITreeModel for a given prefix, and you just pass in the text in the entry as the prefix. E.g.

```csharp
_selector.Entry.Changed += Entry_Changed;
...
private void Entry_Changed(object sender, EventArgs e)
{
    string match = _selector.Entry.Completion.ComputePrefix(_selector.Entry.Text);
    Console.WriteLine($"Best match is {match}");
}
```

Unsure of how this would go if you have a huge number of items in the tree model.

**Comment by Kejardon** [comment]
Whoops. ConnectBefore does make it work how I expected. I vaguely remember running into this sort of problem before too, I just completely forgot about it. Thanks for the reminder. It's honestly a headscratcher to me that Gtk# changes that.

I don't think I want to use Changed, I'd rather wait until there's an indication the user is *done* (probably Activated and/or FocusOut). I'll try out ComputePrefix though, thanks for the suggestion.
