### ISSUE TITLE
What is the difference with https://github.com/mono/gtk-sharp ?

### ISSUE THREAD

**Issue by Tux1** [GtkSharp/GtkSharp#20]
What is the difference with https://github.com/mono/gtk-sharp ?

**Comment by cra0zy** [comment]
These are the major differences, probably should thing about adding this to the readme or some sort of FAQ:

|                | Gtk Version | Target Framework  | Extra        |
| -------------- | ----------: | ----------------: | -----------: |
| mono/gtk-sharp | Gtk 3.0     | .Net Framework    |              |
| GtkSharp       | Gtk 3.22    | .NET Standard 2.0 | No glue libs |
