### ISSUE TITLE
GetBorder from IScrollable

### ISSUE THREAD

**Issue by Dadoum** [GtkSharp/GtkSharp#200]
GetBorder have an argument "border", it should be a reference.
What says Gtk documentation:
```c
gboolean
gtk_scrollable_get_border 
(
     GtkScrollable *scrollable,
     GtkBorder *border  [out caller-allocates]
);
```

**Comment by lytico** [comment]
i see it here:

Source/Libs/GtkSharp/**Generated**/Gtk/IScrollable.cs : 

```c#
#region Autogenerated code
	public partial interface IScrollable : GLib.IWrapper {

		bool GetBorder(Gtk.Border border);
		Gtk.Adjustment Hadjustment {
			get; set;
		}
```

so what you are missing?

**Comment by lytico** [comment]
as GtkBorder is struct
could be an **out** parameter

but current implementation should work too, only a question of creating some GtkBorder-values too much

**Comment by lytico** [comment]
should also be changed in
IScrollableImplementor
