### ISSUE TITLE
Can I use GtkSharp with Mono and Monodevelop IDE?

### ISSUE THREAD

**Issue by moon672** [GtkSharp/GtkSharp#205]
I am Ubuntu and using Mono and Monodevelop for C#. I was wondering if it is possible to create GtkSharp (not GtkSharp 2) project just with Mono and Monodevelop, without using dotnet core and without rebuilding from source.

Edit: I reckon there is GtkSharp plugin for Monodevelop in the release page, will it work with Mono or I need to install dotnet core?

**Comment by jcbritobr** [comment]
Why not use net 5, glade, vscode and gtksharp? You will get the latest gtk version support and RAD.

**Comment by lytico** [comment]
GtkSharp is .netstandard2, so it works with all versions supporting netstandard2:

https://docs.microsoft.com/en-us/dotnet/standard/net-standard
for mono, this means you need mono version 5.4 or higher.

as of monodevelop:
versions >= 7.8 supports .netstandard

but you have no support for glade in monodevelop.

**Comment by lytico** [comment]
> GtkSharp plugin for Monodevelop

Monodevelop plugins targets .net framework, so its working with mono, but not with .netcore

**Comment by harry-cpp** [comment]
The GtkSharp MonoDevelop addin targets .NET Core by default, you can change the target framework to .NET Framework if you want.

It also provides automatic opening using Glade when you try to open any of the .glade files.
