### ISSUE TITLE
CairoSharp-api.xml is missing some enums

### ISSUE THREAD

**Issue by hol430** [GtkSharp/GtkSharp#207]
From the [cairo docs](https://developer.gnome.org/cairo/stable/cairo-cairo-t.html):

```c
typedef enum _cairo_line_join {
    CAIRO_LINE_JOIN_MITER,
    CAIRO_LINE_JOIN_ROUND,
    CAIRO_LINE_JOIN_BEVEL
} cairo_line_join_t;
```

```c
typedef enum _cairo_line_cap {
    CAIRO_LINE_CAP_BUTT,
    CAIRO_LINE_CAP_ROUND,
    CAIRO_LINE_CAP_SQUARE
} cairo_line_cap_t;
```

These types don't appear in the CairoSharp-api.xml file , but they seem to have been added manually in [LineJoin.cs](https://github.com/GtkSharp/GtkSharp/tree/master/Source/Libs/CairoSharp/LineJoin.cs) and [LineCap.cs](https://github.com/GtkSharp/GtkSharp/tree/master/Source/Libs/CairoSharp/LineCap.cs). For most people this probably doesn't make a difference, but I'm generating bindings for a library which references these two types, and I'm getting warnings from the code generator along the lines of `Unknown type cairo_line_cap_t on parameter cap_style`. Adding these two types into the -api.xml file fixes the problem.

It seems kind of intentional to me, the way that these two types have been manually implemented (rather than outputted by the code generator) but if you think this is an accident, let me know and I can PR a "fix".

**Comment by lytico** [comment]
it seems that most part of cairo is manually implemented.

generally, all types are "c#ished", so if added to api-xml, it wouldn't make a difference in the result.

see eg:
https://github.com/GtkSharp/GtkSharp/blob/a0f6a044d7bae9d3727372c7be23d75ed3e5abcf/Source/Libs/AtkSharp/AtkSharp-api.xml#L10-L14

becomes 

```
#region Autogenerated code
	[GLib.GType (typeof (Atk.CoordTypeGType))]
	public enum CoordType {

		Screen,
		Window,
	}

	internal class CoordTypeGType {
		[UnmanagedFunctionPointer (CallingConvention.Cdecl)]
		delegate IntPtr d_atk_coord_type_get_type();
		static d_atk_coord_type_get_type atk_coord_type_get_type = FuncLoader.LoadFunction<d_atk_coord_type_get_type>(FuncLoader.GetProcAddress(GLibrary.Load(Library.Atk), "atk_coord_type_get_type"));

		public static GLib.GType GType {
			get {
				return new GLib.GType (atk_coord_type_get_type ());
			}
		}
	}
#endregion
```

**Comment by hol430** [comment]
Thanks - yeah, that's pretty much what I did locally to work around the problem. For reasons that aren't entirely clear to me, adding these enums into the api file doesn't cause them to be generated, but it doesn't really matter since they've been manually implemented anyway. (I notice that mono's gtk-sharp repo has also manually implemented most of the cairo bindings.)

Anyway, let me know if you're happy to have these enums in the -api.xml file and I can make a PR. Otherwise, this issue could probably be closed.

**Comment by lytico** [comment]
i think it isn't worth the effort. A clean solution would be to generate cairo-classes like all others, and to have everything in the api.xml-file.
BUT see: https://github.com/GtkSharp/GtkSharp/issues/166#issuecomment-754850482
so maybe there will be that way implemented in a future version of gtksharp.
