### ISSUE TITLE
[Question] What's the difference between this and mono/gtk-sharp?

### ISSUE THREAD

**Issue by bmitc** [GtkSharp/GtkSharp#209]
I see in this repository's README that this is a fork from [mono/gtk-sharp](https://github.com/mono/gtk-sharp). What is the reason for the fork and separate development?

I am researching solutions for developing a cross-platform graphics and GUI toolkit with SkiaSharp, F#, and .NET 5, and so I need a solution for displaying a SkiaSharp canvas in a Window.

Thanks for any help!

**Comment by jcbritobr** [comment]
This is just a binding for gtk libraries. If you use either mono or net5 gtk libraries, you will be using only interfaces above this libraries.
Now, about you question about skia, I think you can subclass a widget object and do some changes on it.

**Comment by lytico** [comment]
> What is the reason for the fork and separate development?
Differences can be seen with the following table:

|               | Target framework   | Target Gtk Version                                 | Extra notes                   |
|:--------------|:-------------------|:---------------------------------------------------|:------------------------------|
| GtkSharp      | .NET Standard 2.0  | Gtk 3.22                                           | Does not need glue libraries. |
| mono/gtksharp | .NET Framework 4.5 | Gtk 2 (also Gtk 3.0 but never officially released) |                               |

so, as this is .netstandard2, you can use it in .net5-solutions.

> I need a solution for displaying a SkiaSharp canvas in a Window.

SkiaSharp references this fork, see: https://github.com/mono/SkiaSharp/blob/e8869d17a62dc4ca985a55a63cd2a90f4a15f5f5/source/SkiaSharp.Views/SkiaSharp.Views.Gtk3/SkiaSharp.Views.Gtk3.csproj#L11
 so you can use https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views/SkiaSharp.Views.Gtk3/SKDrawingArea.cs
to display a SkiaSharp canvas

**Comment by bmitc** [comment]
Thanks! I realize that these are just bindings, but somehow I missed that table which was what I was looking for.

Thank you for the references to SkiaSharp using this library. I didn't realize they had views for GtkSharp, as SkiaSharp.Views is described as having "platform-specific views", and I want to be writing .NET 5 libraries and applications.
