### ISSUE TITLE
new Pixbuf(byte[] buffer) leaks memory

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [GtkSharp/GtkSharp#210]
If I execute the following code:

```csharp
var graphicsContent = File.ReadAllBytes("image.png");

for (int i=0; i<100; i++)
{
      var pixbuf =  new Pixbuf(graphicsContent);
      pixbuf.Dispose()
}
```

I have a giant memoryleak. I also tried the stream variant, same problem!
The only variant that did not leak was specifying a filename.

Looking into the code I found a workaround which does not leak.

```csharp
var graphicsContent = File.ReadAllBytes("image.png");

for (int i=0; i<100; i++)
{
   var pixbufLoader = new PixbufLoader(graphicsContent);
   pixbufLoader.Dispose()
}
```

As the PixbufLoader class has a member "Pixbuf" I used this alternative in my code to reference Pixbuf and everything is fine.

I would appreciate someone having a look at this issue, because others might suffer from this too!
It took me quit sometime to find the memoryleak as it was hidden in a lot of code around it.
I seems like a problem in the dispose routine in the Pixbuf class.

**Comment by harry-cpp** [comment]
Seems like the issue has been fixed with some of the newest changes to the destroy/dispose system so gonna close this.
