### ISSUE TITLE
Could not find 'ExposeEvent' 

### ISSUE THREAD

**Issue by renjuashokan** [GtkSharp/GtkSharp#211]
I was using mono gtk# 2 version, on upgrading to this GtkSharp, I could not find 'ExposeEvent' associated with Windows or DrawingArea. 
Can someone point out to me what I'm missing here?

**Comment by lytico** [comment]
ExposeEvent is replaced by

`protected override bool OnDrawn (Context g)`

**Comment by renjuashokan** [comment]
@lytico  the mentioned `OnDrawn` is for DrawingArea right? 
But for Window this can't be used, right?

Please pardon me for asking naive questions.

**Comment by lytico** [comment]
@renjuashokan 

`protected override bool OnDrawn (Context g)` is declared on `Gtk.Widget`

`Gtk.DrawingArea` is a subclass of `Gtk.Widget`, therefore it inherits  `OnDrawn (Context g)`

`Gtk.Window` is a subclass of `Gtk.Bin`, which is a subclass of `Gtk.Container`, which is a subclass of `Gtk.Widget`,  therefore it inherits  `OnDrawn (Context g)`

**Comment by PlatinumLucario** [comment]
Also @lytico, just out of curiosity, how differently is ``OnDrawn`` implemented compared to ``OnExpose``? And how different is ``ExposeEvent`` compared to ``Drawn``?

**Comment by lytico** [comment]
sorry, i can't find the gtk2 docs any more. seems they are removed.
gkt3 draw:
https://docs.gtk.org/gtk3/signal.Widget.draw.html

main difference is that OnDrawn has a Cairo.Context as paramter, whereas OnExpose you need to get the Cairo.Context with a helper method.
see (OnExpose): https://www.mono-project.com/docs/tools+libraries/libraries/Mono.Cairo/cookbook/

like this:
```
 protected override bool OnExposeEvent (Gdk.EventExpose args)
    {
    using (Context g = Gdk.CairoHelper.Create (args.Window)){
```
