### ISSUE TITLE
CssProvider LoadFromResource is not working as expected.

### ISSUE THREAD

**Issue by renjuashokan** [GtkSharp/GtkSharp#212]
I have a CSS file as an embedded resource in cs project.

```
<ItemGroup>
		<EmbeddedResource Include="gladefiles/test.glade" />
		<EmbeddedResource Include="cssfiles/main.css" />
	</ItemGroup>
```

For printing resources added code like below

```
           var assemblyName = new AssemblyName("TestGTKUI");
            var resources = string.Join(Environment.NewLine, Assembly.Load(assemblyName).GetManifestResourceNames());
            Console.WriteLine("List of Manifest Resource Names");
            Console.WriteLine("======================");
            Console.WriteLine(resources);
```

In the console, I can see this
```
List of Manifest Resource Names
======================
TestGTKUI.gladefiles.test.glade
TestGTKUI.cssfiles.main.css
```

But when I try to load CSS file with the function

```
var cssProvider = new CssProvider();
cssProvider.LoadFromResource("TestGTKUI.cssfiles.main.css");
```

I'm getting the following error,

`(TestGTKUI:74984): Gtk-WARNING **: 15:40:57.993: Theme parsing error: <broken file>:1:0: Failed to import: The resource at ?/TestGTKUI.cssfiles.main.css? does not exist`

I really want to use an embedded resource, since I don't want to ship css files while shipping.
Can someone point out to me what is the error?

The project can be found from [here](https://github.com/renjuashokan/TestGTKUI/tree/main/TestGTKUI)  (only 2 cs files )

**Comment by TheForgetTime** [comment]
Please set the logical name of the embedded resource.

e.g.
```xml
    <ItemGroup>
        <EmbeddedResource Include="**\*.glade">
          <LogicalName>%(Filename)%(Extension)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
```

**Comment by TheForgetTime** [comment]
@harry-cpp Loading css from embedded resources is indeed not feasible

Even though I set the logical name

```
(GtkDemo:369470): Gtk-WARNING **: 17:41:04.308: Theme parsing error: <broken file>:1:0: 
Failed to import: 
    The resource located in "/main.css" does not exist
```

**Comment by zii-dmg** [comment]
Method is using GTK (GResource) resources, not .NET embedded resources. Other similar methods is manually written to use .NET resources but not this.

**Comment by lytico** [comment]
indeed, quite a different thing:

https://developer.gnome.org/gtk3/stable/GtkCssProvider.html#gtk-css-provider-load-from-resource says that the argument is
resource_path  is a **`GResource`** resource path

and **`GResource`** is: https://developer.gnome.org/gio/stable/GResource.html

**`GResources`** have to compiled with an external tool: https://developer.gnome.org/gio/stable/glib-compile-resources.html

so, using` CssProvider.LoadFromResource `seems a very complicated stuff

to solve your problem, you could easier:

read the resource as **`string`** with common .net - methods

and use **`CssProvider.LoadFromData(string data)`**

**Comment by lytico** [comment]
btw, maybe we should refactor the ` CssProvider.LoadFromResource` with a pattern like in Builder:

https://github.com/GtkSharp/GtkSharp/blob/cd47acba85bff2723433606c87834f1e36160818/Source/Libs/GtkSharp/Builder.cs#L177-L192

and 

https://github.com/GtkSharp/GtkSharp/blob/cd47acba85bff2723433606c87834f1e36160818/Source/Libs/GtkSharp/Builder.cs#L362-L377

**Comment by renjuashokan** [comment]
Hi I'm using the latest package for gtksharp

```
<ItemGroup>
    <PackageReference Include="GtkSharp" Version="3.24.24.34" />
  </ItemGroup>
```

I'm still getting the error

`(TestGTKUI:32404): Gtk-WARNING **: 11:19:23.845: Theme parsing error: <broken file>:1:0: Failed to import: The resource at ?/TestGTKUI.cssfiles.main.css? does not exist`

**Comment by zii-dmg** [comment]
There is pull request #238 to fix this. I don't know why maintainers are not merging it.
@harry-cpp

**Comment by harry-cpp** [comment]
@zii-dmg Merge conflicts, both before and after your rebase :D

**Comment by harry-cpp** [comment]
Oh no, wait, if I have selected rebase and merge, and it does not allow it, but it does allow it if I just do a normal merge as you merged develop into your fork... ha...
