### ISSUE TITLE
Glib.Cancelable.Current blocks the app on Windows if MSYS2 Glade was started before it

### ISSUE THREAD

**Issue by michaelkruglos** [GtkSharp/GtkSharp#219]
### Problem
Running GtkSharp application on Windows blocks until glade is closed.
The issue seems to be related to `app.Register(GLib.Cancellable.Current);` in the `Main` generated by the `dotnet new` template.

### Steps to reproduce
 * Use Windows
 * Create a new project using `dotnet new gtkapp`
 * Open the project in Visual Studio (Community 2019, maybe happens with other versions)
 * Open MSYS2 console and run glade
 * Go to Visual Studio and click `Run`
 * The application window will not show up until you close glade
 * Removing the line `app.Register(GLib.Cancellable.Current);`, generated by `dotnet new gtkapp` makes the problem go away.

### Source code for reference
```csharp
        [STAThread]
        public static void Main(string[] args)
        {
            Application.Init();

            var app = new Application("org.GtkPlayground.GtkPlayground", GLib.ApplicationFlags.None);
            app.Register(GLib.Cancellable.Current);

            Console.WriteLine("Start");
            var win = new MainWindow();
            app.AddWindow(win);

            win.Show();
            Application.Run();
        }
```

**Comment by lytico** [comment]
https://github.com/GtkSharp/GtkSharp/blob/aa1095a02de2dc90c5fc59855bc21d23a0646e79/Source/Templates/GtkSharp.Template.CSharp/content/GtkSharp.Application.CSharp/Program.cs

has to be refactored to this pattern:
https://github.com/GtkSharp/GtkSharp/issues/242#issuecomment-825815208

**Comment by lytico** [comment]
@michaelkruglos can you try this pattern and see if works?:

```csharp

        [STAThread]
        public static void Main(string[] args)
        {
            Application.Init();

            var app = new Application("org.GtkPlayground.GtkPlayground", GLib.ApplicationFlags.None);

            app.Startup += (_, _) => {
                var win = new MainWindow ();
                app.AddWindow (win);
                win.ShowAll();
            }
                
            app.Activated += (_, _) => {
                app.Windows[0].Present();
            };
           
            ((GLib.Application) app).Run ();

        }

```
