### ISSUE TITLE
Cant update for new gtksharp templates

### ISSUE THREAD

**Issue by jcbritobr** [GtkSharp/GtkSharp#222]
Dotnet 5.0 cli always shows the message thats an update for new templates is available. But when i run the command below, the package is not updated.
Checked in source code, and I think is needed to update templates to the new  3.24.24.4 version.

```
An update for template pack GtkSharp.Template.CSharp::3.22.25.128 is available.
install command: dotnet new -i GtkSharp.Template.CSharp::3.22.25.128
```

Im running on win 10 64 pro, dotnet 5.0 cli.

**Comment by jcbritobr** [comment]
I did the fix, but can't push in this server for code review. What I need todo to help with code?

**Comment by harry-cpp** [comment]
There are already correct templates published: https://www.nuget.org/packages/GtkSharp.Template.CSharp/3.24.24.4

The warning you are seeing is actually a bug with dotnet new template system, it will show you that update warning even if no update is available, plus gives the wrong command I see XD.
