### ISSUE TITLE
toggle_refs_notify: assertion failed after upgrade to version 3.24.24.4

### ISSUE THREAD

**Issue by saskathex** [GtkSharp/GtkSharp#223]
After updating to current version 3.24.24.4 from previous version 3.22.25.128 a have an issue when destroying widgets/objects.

I get the following output on the console and the app crashes:

```
GLib-GObject:ERROR:../glib-2.66.4/gobject/gobject.c:3210:toggle_refs_notify: assertion failed: (tstack.n_toggle_refs == 1)
Bail out! GLib-GObject:ERROR:../glib-2.66.4/gobject/gobject.c:3210:toggle_refs_notify: assertion failed: (tstack.n_toggle_refs == 1)
```

My application is pretty simple, but I cannot share it currently. It is basically a master/detail view with a selection on the left side and it fills a Notebook/TabControl on the right side. On each selection all the right side tabs are removed and recreated with new glade UI widgets.

Reverting to previous version and everthing works as expected. I checked the changes and I think it has something to do with the GLibSharp.Object and ToggleRef changes.

**Comment by saskathex** [comment]
I created a stripped project: [https://github.com/saskathex/GObjectRepro.git](url)

Reproduce by:
- Click the button 1 as fast as possible.
- Just click the button1 and 2 alternating.

**Comment by saskathex** [comment]
After reviewing all checkins, I found the solution to my problem. 

With commit https://github.com/GtkSharp/GtkSharp/commit/0daa9853166a886005a6219862da5a4c9ce1c296 it is necessary to replace constructor : base (builder.GetRawObject("name")) or base (builder.GetObject("name").Handle)
with constructor : base (builder.GetRawOwnedObject("name"))

Hope this helps others.

**Comment by zii-dmg** [comment]
Templates should be updated to use `GetRawOwnedObject`. I hope this method is not creating another leak.
