### ISSUE TITLE
The issue Pixbuf.ScaleSimple causes a memory leak #112 still persists

### ISSUE THREAD

**Issue by jcbritobr** [GtkSharp/GtkSharp#226]
I could retest the bug #112  with vmmap and notice clearly that the issue below still happens. Its allocs less memory, but the leak still exists.

https://github.com/GtkSharp/GtkSharp/issues/112 Here are the evidences.
![image](https://user-images.githubusercontent.com/6579862/111388687-7e74e480-868e-11eb-9475-3edc1483055c.png)

**Comment by jcbritobr** [comment]
With more samples, we could see better.
![image](https://user-images.githubusercontent.com/6579862/111387837-2093cd00-868d-11eb-88fd-841b90d088e9.png)

**Comment by zii-dmg** [comment]
Strange, I have different results in VMMap.
Tested with:
* .NET Core 5.0.4
* Windows 10 20H2
* GtkSharp code from github, not nuget package
* Gtk3 3.24.24 x64 (manually downloaded package from msys2)

![vmmap](https://user-images.githubusercontent.com/2846896/111487342-54ccc380-8749-11eb-8278-79346093e7d8.png)

**Comment by jcbritobr** [comment]
> 
> 
> Strange, I have different results in VMMap.
> Tested with:
> 
>     * .NET Core 5.0.4
> 
>     * Windows 10 20H2
> 
>     * GtkSharp code from github, not nuget package
> 
>     * Gtk3 3.24.24 x64 (manually downloaded package from msys2)
> 
>     * Test code from #112 first post
> 
> 
> ![vmmap](https://user-images.githubusercontent.com/2846896/111487342-54ccc380-8749-11eb-8278-79346093e7d8.png)

Just copy the code on the #112 issue, but I had removed sleep(250) to get more samples. Even in your code, the committed memory is gradually getting higher. Its very sutil, but is still there
![image](https://user-images.githubusercontent.com/6579862/111490480-d1e04480-8719-11eb-96b3-b2cd8a8e9f46.png)

**Comment by zii-dmg** [comment]
Ok, I see. But it leaks even with:
```csharp
using (var source = new Pixbuf("image.png"))
{
    Console.WriteLine("count " + ++count);
}
```
Something with glib/gobject memory management? This is magic for me.

**Comment by jcbritobr** [comment]
I think may be somthing with pixbuf.

**Comment by lytico** [comment]
on linux, i can't find a leak.

i merged an example: checkout latest branch develop, run Samples -> Miscellaneous -> PixbufDemo 
start and stop it, as you like. as long as running, it reads a pixbuf from file.

**Comment by jcbritobr** [comment]
> 
> 
> on linux, i can't find a leak.
> 
> i merged an example: checkout latest branch develop, run Samples -> Miscellaneous -> PixbufDemo
> start and stop it, play around as you like.
> as long as running, it reads a pixbuf from file.
> 
> the minimal "leak"s you see is as for eg. the test string gets longer, and other memory allocated by the sample-app.
> the "leak" results are quite coincidentally, depending at the whim of the garbage collector.
> 
> all numbers in bytes.
> 
> example: 3 times started / stoped
> 
> ```
> heatup.ByteLength	6 211 200
> GetTotalMemory at start: 979 592,000
> Leak:	1 184	memAllocated
> GetTotalMemory at start: 979 592	at end: 980 776	Pixbuf created: 3772
> heatup.ByteLength	6 211 200
> GetTotalMemory at start: 980 552,000
> Leak:	392	memAllocated
> GetTotalMemory at start: 980 552	at end: 980 944	Pixbuf created: 1536
> heatup.ByteLength	6 211 200
> GetTotalMemory at start: 980 552,000
> Leak:	200	memAllocated
> GetTotalMemory at start: 980 552	at end: 980 752	Pixbuf created: 3015
> ```
> 
> you can even get a minus "leak" if the gc has breath enough, if you delete the app output, and run again:
> 
> ```
> heatup.ByteLength	6 211 200
> GetTotalMemory at start: 982 736,000
> Leak:	-16	memAllocated
> GetTotalMemory at start: 982 736	at end: 982 720	Pixbuf created: 105
> ```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gdk.Pixbuf.Save(String filename, String type) in C:\Workspace\csharp\github\GtkSharp\Source\Libs\GdkSharp\Pixbuf.cs:line 235
   at Samples.PixbufDemo.OnPressed() in C:\Workspace\csharp\github\GtkSharp\Source\Samples\Sections\Miscellaneous\PixbufSection.cs:line 58
```

**Comment by lytico** [comment]
just a moment, seems that new Pixbuf (typeof(ImageSection).Assembly, "Testpic") doesn't work on windows

**Comment by lytico** [comment]
adjusted

**Comment by jcbritobr** [comment]
Yes, there are no issues with pixbuf.
![image](https://user-images.githubusercontent.com/6579862/111695315-b5bfce80-8811-11eb-8c77-1e2930fa55f8.png)

but I'm sure there is an issue with this code yet. I don't want to be boring. When someone program something like this in video processing, the issue will happen again.
```csharp
        public static void Main(string[] args)
        {
            Console.WriteLine("starting test");
            // Application.Init();
            // new Program();
            // Application.Run();
            int count = 0;
            for (int i = 0; i < 1000000; i++)
            {
                using (var source = new Pixbuf("c:/sample.png"))
                using(var scaled = source.ScaleSimple(100, 100, InterpType.Bilinear))
                {
                    Console.WriteLine($"scaled image {++count}");
                }
            }
        }
```
![image](https://user-images.githubusercontent.com/6579862/111698075-2a483c80-8815-11eb-9b2e-4ffc52d8f261.png)

**Comment by lytico** [comment]
>  I don't want to be boring. 
you don't. no one  is interested in a memory leak.
i'll change the example to ScaleSimple and test it again.

**Comment by jcbritobr** [comment]
> 
> 
> > I don't want to be boring.
> 
> you don't. no one is interested in a memory leak.
> i'll change the example to ScaleSimple and test it again.

The leak is very a very sutil one. Will need some minutes to get it visible.

**Comment by lytico** [comment]
Tested again with 
```
                using(var scaled = source.ScaleSimple(100, 100, InterpType.Bilinear))
                {
                    totalNrOfByteLenths += scaled.ByteLength;
                }
```
in the loop.
No issues found:
![GtkSharp-Pixbuf-MemoryLeak](https://user-images.githubusercontent.com/1479980/111703241-a6567a80-883d-11eb-820a-e5ce4dd8a3f3.PNG)

**Comment by jcbritobr** [comment]
Well, then vmmap is crazy.  :)

**Comment by lytico** [comment]
your test code never does a garbage collection.
as long as the GC has no time (and it hasn't in your loop) and doesn't reach memory limits, it will never give free memory.
anyway, your tool for measuring is not capable to find memory leaks in user code. it measures the overall stuff, so problems within .net are covered too.

try to test your code with
```
	   const int colMod = 100;
            int count = 0;
            for (int i = 0; i < 1000000; i++)
            {
                using (var source = new Pixbuf("c:/sample.png"))
                using(var scaled = source.ScaleSimple(100, 100, InterpType.Bilinear))
                {
                    Console.WriteLine($"scaled image {++count}");
                }
		if (count % colMod == 0) {
			GC.Collect();
			GC.WaitForFullGCComplete ();
			Console.WriteLine ($"{nameof(GC.GetTotalMemory)} {count} % {colMod}: {GC.GetTotalMemory (true):N}");
		}
            }

```

**Comment by jcbritobr** [comment]
I already did a pause in the code. A readline. Memory doesn't return to system.

**Comment by jcbritobr** [comment]
May you test with vmmap?

**Comment by lytico** [comment]
do a gc.collect.
code is not merged, check it out from here: 
https://github.com/lytico/GtkSharp/tree/lytico/issues/226

**Comment by jcbritobr** [comment]
I will try here with gc.collect

**Comment by jcbritobr** [comment]
Its happenning even with gc.collect. Here are the code
```csharp
        public static void Main(string[] args)
        {
            Console.WriteLine("starting test");
            // Application.Init();
            // new Program();
            // Application.Run();
            int count = 0;
            for (int i = 0; i < 1000000; i++)
            {
                using (var source = new Pixbuf("c:/sample.png"))
                using(var scaled = source.ScaleSimple(100, 100, InterpType.Bilinear))
                {
                    Console.WriteLine($"scaled image {++count} with gc.collect");
                }

                GC.Collect();
            }
        }
```

![image](https://user-images.githubusercontent.com/6579862/111706190-a1370280-8820-11eb-882a-10ea2628411b.png)

**Comment by jcbritobr** [comment]
I think vmmap is diffrent from vstudio. And we are looking for two types of diferent memories.

**Comment by lytico** [comment]
dear, i end this now.

Leak:	29.752	totalNrOfByteLenths	56.516 mb
GetTotalMemory at start: 1.051.008	at end: 1.080.760	Pixbuf created: 9480

this is 3 bytes per created pixbuf, one of each 6 211 200 bytes. you might calculate the percentage.

> vmmap is diffrent

yes, it's not able to measure exactly:

![GtkSharp-Pixbuf-MemoryLeak_vnmap](https://user-images.githubusercontent.com/1479980/111707957-4794ff00-8845-11eb-9688-02f5afcafeb0.PNG)

i hitted F5 in vmmap, this are the memory valleys in the graph.
so if a measure is dependent how often i press a key, this is not accurate.

> vstudio profile

i measured with https://www.jetbrains.com/dotmemory, one of the most accurate tools (more accurate than vstudio profile) on the market. if this finds nothing, there is nothing - except in the dotnet runtime itself.

**Comment by lytico** [comment]
anyway, it was an interesting session!

**Comment by jcbritobr** [comment]
I'll return here with the task manager size for 1 hour. ;)

**Comment by lytico** [comment]
as i said, the GC swallows every memory it can get. 
pressure the system with other memory costly stuff (eg. firefird, a lot of open tabs with, let say, some tv soup operas running, then it will free memory. but be aware, not getting into disk swapping sh...!

**Comment by jcbritobr** [comment]
> 
> 
> as i said, the GC swallows every memory it can get.
> pressure the system with other memory costly stuff (eg. firefird, a lot of open tabs with, let say, some tv soup operas running, then it will free memory. but be aware, not getting into disk swapping sh...!

I' ll do a pause in the program and wait if the memory will be collected. Also will run with gc.collect(): Will see memory size.

**Comment by lytico** [comment]
and, for long running tasks, refactor your app with https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.backgroundworker?view=net-5.0 (you don't need a win-app, it also works with console.apps)

**Comment by jcbritobr** [comment]
> 
> 
> and, for long running tasks, refactor your app with https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.backgroundworker?view=net-5.0 (you don't need a win-app, it also works with console.apps)

already is a console
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GtkSharp" Version="3.24.24.*" />
  </ItemGroup>

</Project>
```

**Comment by lytico** [comment]
i referred on the example in https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.backgroundworker?view=net-5.0 , they use winform there (whyever)

**Comment by jcbritobr** [comment]
It was collected when I removed Console.WriteLine(...). Think string was committing memory in app.

```csharp
   public static void Main(string[] args)
        {
            Console.WriteLine("starting test");
            // Application.Init();
            // new Program();
            // Application.Run();

            for (int i = 0; i < 1000000; i++)
            {
                if(i == 999999)
                {
                    Console.ReadLine();
                }
                using (var source = new Pixbuf("c:/sample.png"))
                using(var scaled = source.ScaleSimple(100, 100, InterpType.Bilinear))
                {
                    //Console.WriteLine($"scaled image with gc.collect");
                }

                GC.Collect();
            }
        }
    }
```

**Comment by lytico** [comment]
oh no! 

to be shure, try do to something with scaled, otherwise it's in danger to be optimized.
eg. start a memcounter outside of the loop, at program start, and add the ByteLength to it:
var memcounter = 0;

memcounter += scaled.ByteLength;

and, outside of the loop, at the end of program, just to be shure that memcounter isn't optimized (away):
Console.WriteLine($"{memcounter}");

**Comment by jcbritobr** [comment]
Tryed with another tool. The generations are increasing. Below the code

```csharp

public static void Main(string[] args)
        {
            Console.WriteLine("starting test");
            // Application.Init();
            // new Program();
            // Application.Run();
            int memcount = 0;

            for (int i = 0; i < 1000000; i++)
            {
                if(i == 999999)
                {
                    Console.ReadLine();
                }
                using (var source = new Pixbuf("c:/sample.png"))
                using(var scaled = source.ScaleSimple(100, 100, InterpType.Bilinear))
                {
                    //Console.WriteLine($"scaled image with gc.collect");
                    memcount ++;
                }
            }
        }
```

![image](https://user-images.githubusercontent.com/6579862/111715755-4c50b780-8833-11eb-91f0-745bebada0dd.png)

**Comment by lytico** [comment]
of course. you kicked out   GC.Collect(); from the loop.

**Comment by jcbritobr** [comment]
> 
> 
> of course. you kicked out GC.Collect(); from the loop.

It happens with in same way.

**Comment by badcel** [comment]
I'm not sure if this is already in the code but if the GC gets informed about large amount of unmanaged data being created it should collect references more often without forcing the user to do a manual collection.

See: https://docs.microsoft.com/en-gb/dotnet/api/system.gc.addmemorypressure?view=net-5.0

**Comment by zii-dmg** [comment]
Every GLib.Object is using `ToggleRef` class. Object.Dispose -> ToggleRef.Dispose -> ToggleRef.Free -> ToggleRef.QueueGCHandleFree.

`QueueGCHandleFree` creates timer that frees GCHandles but timeout handler only called when app has GLib message loop. Console app doesn't have one.
https://github.com/GtkSharp/GtkSharp/blob/010116ef0d754614c3a054f9ec4ada0b54e231e7/Source/Libs/GLibSharp/ToggleRef.cs#L140

**Comment by jcbritobr** [comment]
> 
> 
> Every GLib.Object is using `ToggleRef` class. Object.Dispose -> ToggleRef.Dispose -> ToggleRef.Free -> ToggleRef.QueueGCHandleFree.
> 
> `QueueGCHandleFree` creates timer that frees GCHandles but timeout handler only called when app has GLib message loop. Console app doesn't have one.
> 
> https://github.com/GtkSharp/GtkSharp/blob/010116ef0d754614c3a054f9ec4ada0b54e231e7/Source/Libs/GLibSharp/ToggleRef.cs#L140

Thats explain why 'I'm seeing generations growing in my code. :)
