### ISSUE TITLE
Windows: Gdk. Pixbuf.Save(string filename, string type) throws NRE

### ISSUE THREAD

**Issue by lytico** [GtkSharp/GtkSharp#230]
OS: Windows

in 
```
public unsafe bool Save(string filename, string type)
...
gdk_pixbuf_save
...
```
`static d_gdk_pixbuf_save gdk_pixbuf_save` is null.

see: https://github.com/GtkSharp/GtkSharp/issues/226#issuecomment-802243847 with 
https://github.com/GtkSharp/GtkSharp/blob/c4da08592538fc3e9a1b05a95afeac5ee582adc5/Source/Samples/Sections/Miscellaneous/PixbufSection.cs#L58

seems that gdk_pixbuf_save is not found in Library GdkPixbuf (on Win: libgdk_pixbuf-2.0-0.dll)

**Comment by zii-dmg** [comment]
libgdk_pixbuf-2.0-0.dll exports `gdk_pixbuf_save_utf8` on Windows.
Some info about this: https://github.com/haskell-gi/haskell-gi/issues/18.
