### ISSUE TITLE
GException and multithreading

### ISSUE THREAD

**Issue by zii-dmg** [GtkSharp/GtkSharp#236]
Look: https://github.com/mono/gtk-sharp/pull/292
Should we do this also? - cache all exception data in managed variables instead of storing IntPtr.

**Comment by harry-cpp** [comment]
I think we should.

**Comment by zii-dmg** [comment]
According to [docs](https://developer.gnome.org/glib/stable/glib-Error-Reporting.html#GError) `GError::domain` type is `GQuark` which is typedef to `guint32`. But in managed struct `GError` and class `GException` this field/property is `int`. Should this be changed to `uint`?

**Comment by zii-dmg** [comment]
I see many GtkSharp methods with `quark` in name return `int` so I will not change domain to `uint`.
