### ISSUE TITLE
GtkSharp and ProjectReunion: 'GLib.Object' threw an exception when PrintOperation is using

### ISSUE THREAD

**Issue by LeftTwixWand** [GtkSharp/GtkSharp#246]
**Describe the bug:**
I've created a new ProjectReunion solution and trying to use PrintOperation class from the GtkSharp nuget package. But get the error:
```
System.TypeInitializationException: 'The type initializer for 'GLib.Object' threw an exception.'
Inner Exception:
DllNotFoundException: GObject: libgobject-2.0-0.dll, libgobject-2.0.so.0, libgobject-2.0.0.dylib, gobject-2.dll
```
**Stack Trace**
![image](https://user-images.githubusercontent.com/50652041/116540026-4bab4680-a8f2-11eb-94f4-a9797f76a95c.png)

**Steps to reproduce:**

1. Create an empty ProjectReunion app, using [solution template](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion) from marketplace
2. Add GtkShart nuget package
3. Try to create a PrintOperation object

Strange, but at the same time default .NET 5 console application with GtkSharp package working fine. 
I's it a problem of ProjectReunion? Or GtkSharp is not optimized for the new platform?

**NuGet package version:**
Project Reunion 0.5.6
GtkSharp 3.24.24.34

**Environment:** 
Visual Studio 2019 version 16.10.0 Preview 2.1
Windows 10 version 20H2 build 19042

**Comment by lytico** [comment]
do you have gtk installed on your windows system?

https://github.com/GtkSharp/Dependencies

**Comment by LeftTwixWand** [comment]
> do you have gtk installed on your windows system?
> 
> https://github.com/GtkSharp/Dependencies

No. I will try.
