### ISSUE TITLE
Cannot run on macOS

### ISSUE THREAD

**Issue by julian-baumann** [GtkSharp/GtkSharp#249]
Everytime I try to run the program with `dotnet run` or via Visual Studio for mac, I get this error:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at GTK_Test.Program.Main(String[] args) in /Users/julian/Projects/GTK#Test/Program.cs:line 11
```

To ran following commands:
```
brew install gtk+3
brew install gtksourceview4
dotnet new --install GtkSharp.Template.CSharp
dotnet new gtkapp
dotnet run
```

I'm on a M1 MacBook running macOS Big Sur 11.2.3 with .NET 5.0.203
I stumbled across this issue #78 where it is mentioned that it may not work, because MacPorts installs the packages in /opt/local not in /usr/local
Following the Homebrew installation page, homebrew is now also installed on /opt on Apple Silicon macs. https://docs.brew.sh/Installation

Anyone out there having the same issue or any clue on how to fix it?

**Comment by lytico** [comment]
try something like this:
```
                var systemPath = Environment.GetEnvironmentVariable ("Path", EnvironmentVariableTarget.Machine);
                var gtkPath = "/opt/local/gtk... "; // look where gtk is located, and set this path
                Environment.SetEnvironmentVariable ("Path", $"{gtkPath};{systemPath}");
```

**Comment by julian-baumann** [comment]
I tried it with using `/usr/local/Cellar/gtk+3/3.24.29/bin`, `/opt/homebrew/Cellar/gtk+3/3.24.29/bin` and many other paths, but that didn't work. You may have any idea where gtk is located or how to find it?

**Comment by lytico** [comment]
`brew info gtk+3`

gives 

`/usr/local/Cellar/gtk+3/3.24.21`

on my system

**Comment by lihaochen910** [comment]
I can run it on M1 mac. First of all, the gtk you need to install is the x86_64 architecture, because currently dotnet does not support arm64.
```
arch -x86_64 brew install gtk+3
```
Use lipo -info to check which architecture you installed gtk.
```
lipo -info /usr/local/Cellar/gtk+3/3.24.30/lib/libgtk-3.0.dylib
```

**Comment by iMonZ** [comment]
> I can run it on M1 mac. First of all, the gtk you need to install is the x86_64 architecture, because currently dotnet does not support arm64.
> 
> ```
> arch -x86_64 brew install gtk+3
> ```
> 
> Use lipo -info to check which architecture you installed gtk.
> 
> ```
> lipo -info /usr/local/Cellar/gtk+3/3.24.30/lib/libgtk-3.0.dylib
> ```

dotnet added arm support for macOS with dotnet 6

**Comment by mafifi** [comment]
Hi,

Were you able to resolve this whilst having it installed as arm64 under /opt?

**Comment by bstrother1** [comment]
> I can run it on M1 mac. First of all, the gtk you need to install is the x86_64 architecture, because currently dotnet does not support arm64.
> 
> ```
> arch -x86_64 brew install gtk+3
> ```
> 
> Use lipo -info to check which architecture you installed gtk.
> 
> ```
> lipo -info /usr/local/Cellar/gtk+3/3.24.30/lib/libgtk-3.0.dylib
> ```

Followed this suggestion. Did not work. Any solution up for this problem? Is this a compatibility issue?

**Comment by iMonZ** [comment]
> > I can run it on M1 mac. First of all, the gtk you need to install is the x86_64 architecture, because currently dotnet does not support arm64.
> > ```
> > arch -x86_64 brew install gtk+3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Use lipo -info to check which architecture you installed gtk.
> > ```
> > lipo -info /usr/local/Cellar/gtk+3/3.24.30/lib/libgtk-3.0.dylib
> > ```
> 
> Followed this suggestion. Did not work. Any solution up for this problem? Is this a compatibility issue?
Gtk3 is old have you tried using gtk4?

**Comment by bstrother1** [comment]
Wouldn't work. This is for https://github.com/unoplatform/uno/issues/8296 . Talking to the dev it seems as though dependencies from the Uno project require gtk+3.

**Comment by KenjutsuGH** [comment]
Has anyone been able to get this working on a **M1 base Mac**? Nothing I try is working

**Comment by bstrother1** [comment]
> I am using x86_64 GtkSharp on M1.

So am I. Still not working.

**Comment by bstrother1** [comment]
If there is a tried and true way of doing this it would be very beneficial to a lot of people to have documentation step-by-step on what the devs expect you to do. Going through countless steps from random stackoverflow posts and hitting dead ends isn’t beneficial to anyone.

**Comment by lihaochen910** [comment]
> I can currently run the x86_64 GtkSharp on M1 mac. First of all, the gtk you need to install is the x86_64 architecture, because currently dotnet does not support arm64. Install gtk+3 using -x86_64 brew
> 
> ```
> arch -x86_64 brew install gtk+3
> ```
> 
> Check your dotnet sdk path, the arm64 and x86_64 .NET6 SDKs have been installed in my computer arm64 dotnet: /usr/local/share/dotnet/dotnet x86_64 dotnet: /usr/local/share/dotnet/x64/dotnet Then add the dotnet SDK environment variables to your .zprofile.
> 
> ```
> # Add .NET Core SDK tools
> # export PATH="$PATH:/usr/local/share/dotnet"
> export PATH="$PATH:/usr/local/share/dotnet/x64"
> ```
> 
> I will use the x86_64 SDK as default, So here I renamed the arm64 dotnet to dotnet_arm64, which will avoid the conflict of the dotnet environment variables of the two sdk. now arm64 dotnet: /usr/local/share/dotnet/dotnet_arm64
> 
> ```
> lipo -info $(which dotnet)
> Non-fat file: /usr/local/share/dotnet/x64/dotnet is architecture: x86_64
> ```
> 
> Executables compiled with dotnet of x86_64 architecture will reference gtk+3 of x86_64 architecture, so it should work.

@bstrother1 try it!
