### ISSUE TITLE
Gtk.HTML: type or namespace does not exist in the namespace 'Gtk'

### ISSUE THREAD

**Issue by Jakar510** [GtkSharp/GtkSharp#254]
I'm want to use this [html widget](http://www.fifi.org/doc/libgtkhtml-dev/html/gtkhtml.html) but it's not found in the GTK namespace. 

	using System;
	using System.IO;
	using Gtk;
	using UI = Gtk.Builder.ObjectAttribute;

	internal class HtmlWindow : Window
	{
		public HtmlWindow( string[] args ) : base(nameof(HtmlWindow))
		{
			Application.Init();
			var html = new HTML();
			var sw   = new ScrolledWindow();
			Add(sw);
			sw.Add(html);
			HTMLStream s = html.Begin("text/html");

			if ( args.Length > 0 )
			{
				using StreamReader r = File.OpenText(args[0]);

				s.Write(r.ReadToEnd());
			}
			else
			{
				s.Write("<html><body>");
				s.Write("Hello world!");
			}

			html.End(s, HTMLStreamStatus.Ok);
			ShowAll();
		}
	}

![image](https://user-images.githubusercontent.com/49802225/118874301-5e40ec00-b8b0-11eb-93a7-39a6feaef79a.png)

**Comment by zii-dmg** [comment]
GtkHTML library is not part is Gtk. GtkSharp is not wrapping GtkHTML library. Also looks like GtkHTML is old. There is WebKitGTK library (linux only) for showing html, but is is not wrapped by GtkSharp too.
