### ISSUE TITLE
GTK play VLC video, only sound, no image

### ISSUE THREAD

**Issue by bbhxwl** [GtkSharp/GtkSharp#264]
GTK play VLC video, only sound, no image

net core 3.1
`
static void Main(string[] args)
{

        Core.Initialize();

        // Initializes the GTK# app
        Application.Init();

        using var libvlc = new LibVLC(enableDebugLogs: true);
        using var mediaPlayer = new MediaPlayer(libvlc);
        // Create the window in code. This could be done in glade as well, I guess...
        var myWin = new Window("LibVLCSharp.GTK.Sample");
        myWin.Resize(800, 450);
        Frame c = new Frame();
         
        mediaPlayer.Hwnd = c.Handle;
        myWin.Add(c);
        myWin.ShowAll();
        using var media = new Media(libvlc,
            new Uri("https://bj.bcebos.com/kpy-organizations/U2943159/videos/2021062612303528372289135202.mp4"));
        mediaPlayer.Play(media);
        myWin.DeleteEvent += (sender, args) =>
        {
            mediaPlayer.Stop();
            Application.Quit();
        };

        Application.Run();

    }
`

 
![image](https://user-images.githubusercontent.com/26525599/123519413-beac2000-d6dd-11eb-9058-5405c2b6adc3.png)

**Comment by zii-dmg** [comment]
`c.Handle` is returning pointer to native gtk object, not Windows hwnd. If you need hwnd see #257.

**Comment by bbhxwl** [comment]
> `c.Handle` is returning pointer to native gtk object, not Windows hwnd. If you need hwnd see #257.

Can I use GTK to play VLC video in raspberry pie? I failed in the test

**Comment by zii-dmg** [comment]
I don't know.
