### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by Juniorsnet** [GtkSharp/GtkSharp#275]
I got System.AccessViolationException when try to run two instance of a gtk app.

OS: Windows 10 (21H2)
.NET: 5.0.31

Step to reproduce:

Create an gtk app with:
**dotnet new gtkapp**
Build it:
**dotnet build**

Go to: bin/Debug/net5.0 and run the exe file. (via explorer or cmd)

Run the exe again (in the same folder or with another copy).

Result: the app crash with:

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Gtk.Application.AddWindow(Gtk.Window)
   at gtktest.Program.Main(System.String[])

How I can do to run two instance of an GTK app?

Regards

**Comment by zii-dmg** [comment]
Use [this main](https://github.com/GtkSharp/GtkSharp/issues/242#issuecomment-825815208).
Or at least use `GLib.ApplicationFlags.NonUnique` to allow multiple instances of application (works in old template).

**Comment by lytico** [comment]
changing main to this pattern: 

https://github.com/lytico/GtkSharp/blob/95f4c02c59339d8f8c22031a965b80572ae042c4/Source/Samples/Program.cs

and starting twice, doesn't solve the problem. there is no Exception then, but seem to starts into the same instance.

the problem is in [ApplicationId](https://docs.gtk.org/gio/type_func.Application.id_is_valid.html).
you have to set a unique one, eg. like

`            App.ApplicationId = $"{App.ApplicationId}.A{Guid.NewGuid()}";`

**Comment by zii-dmg** [comment]
If you want single instance app you should use `GLib.ApplicationFlags.None`.
If you want multiple instance app you should use `GLib.ApplicationFlags.NonUnique`.
Application id can be same for both variants.

**Comment by lytico** [comment]
>  If you want multiple instance app you should use GLib.ApplicationFlags.NonUnique.

using that proposal, using the pattern above, you have to add

`App.Flags = GLib.ApplicationFlags.NonUnique;  `

**Comment by Juniorsnet** [comment]
Thank you! the flag GLib.ApplicationFlags.NonUnique do the job because i need the app run more than once.

However as i understand [this](https://github.com/lytico/GtkSharp/blob/95f4c02c59339d8f8c22031a965b80572ae042c4/Source/Samples/Program.cs) initializacion pattern is the correct way to create an GTK app?. All building code must be done in the Startup event?

**Comment by lytico** [comment]
@Juniorsnet the 'old' pattern sometimes run into problems: see: https://github.com/GtkSharp/GtkSharp/issues/219
