### ISSUE TITLE
StackSwitcher crashes

### ISSUE THREAD

**Issue by seikosantana** [GtkSharp/GtkSharp#277]
I'm still new to GTK and GTK#.
What i am trying to do is to produce a window with Stack and a StackSwitcher.

Having a Stack does not crash the window. Having a StackSwitcher does not crash the window either. But having them linked with the Stack attribute makes the window crash without any exception on the constructor of the window.

Is this a bug?

**Comment by seikosantana** [comment]
I dont know if this matters, but this is how the widgets are placed and Glade can preview snapshot without any problems
![image](https://user-images.githubusercontent.com/35630407/128910612-2de8a905-602d-4e0a-8572-20e4a791cef0.png)

**Comment by seikosantana** [comment]
I found that if i build the application and run it with dotnet run, then it works as expected.
Seems like it has something to do with debugger?

**Comment by zii-dmg** [comment]
Enable console window (for Windows OS) in csproj:
```xml
<PropertyGroup>
  <OutputType>Exe</OutputType>
</PropertyGroup>
```

GTK can print some useful warnings to console.

**Comment by seikosantana** [comment]
I use Ubuntu and i am developing for Ubuntu. Nothing gets printed to Debug Console or terminal on vscode

**Comment by seikosantana** [comment]
For more information,

This is what gets printed to the debug console.
```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/seikosantana/Tests/gtktest/bin/Debug/net5.0/gtktest.dll'. Symbols loaded.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/seikosantana/Tests/gtktest/bin/Debug/net5.0/GtkSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/seikosantana/Tests/gtktest/bin/Debug/net5.0/GioSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/seikosantana/Tests/gtktest/bin/Debug/net5.0/GLibSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/seikosantana/Tests/gtktest/bin/Debug/net5.0/AtkSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Collections.Specialized.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/seikosantana/Tests/gtktest/bin/Debug/net5.0/GdkSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.IO.FileSystem.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[11125] gtktest.dll' has exited with code 0 (0x0).
```

The second window is coded to be shown on a button click.
```
ConfigurationDialog secondWindow = new ConfigurationDialog();
secondWindow.ShowNow();
```
And this is the constructor of ConfigurationDialog();
```
        public ConfigurationDialog() : this(new Builder("MainWindow.glade")) { }

        private ConfigurationDialog(Builder builder) : base(builder.GetRawOwnedObject("ConfigurationDialog"))
        {
            builder.Autoconnect(this);
            _saveButton.Clicked += SaveSettings;
            _cancelButton.Clicked += Cancel;
        }
```

After the crash, an Ubuntu Error window pops up.

![image](https://user-images.githubusercontent.com/35630407/129305118-9c14f72f-6bb3-42a7-b0d3-79bdb353467b.png)
![image](https://user-images.githubusercontent.com/35630407/129305168-0c1e391a-0705-4c9a-97db-32554c6a104e.png)
![image](https://user-images.githubusercontent.com/35630407/129305262-0d11beb4-e6f2-4877-92b1-205f46ef6804.png)
![image](https://user-images.githubusercontent.com/35630407/129305285-517e1dcd-f61c-48ed-8ecc-95828869248d.png)
![image](https://user-images.githubusercontent.com/35630407/129305323-a38fd9fe-2fa3-4ad1-9527-ea9eb2ed3777.png)
![image](https://user-images.githubusercontent.com/35630407/129305342-37a8afd2-0e13-4963-9e11-8e9f75008c0a.png)

Sorry it was lot of images, i hope the stacktrace could help to at least figure out the problem.

My current workaround is to start the executable built and attach the debugger to the started process. By doing that, the crash does not occur.

**Comment by zii-dmg** [comment]
I don't have much experience with Linux. Strange place in stacktrace: all gtk libs are from "/lib/x86_64-linux-gnu" but "libpixbufloader-png.so" is from "/snap/code/71/...". I suppose you are using snap package of vscode. Maybe it loads incorrect lib from snap (don't know how snap works). Can you try not snap version of vscode?

**Comment by harry-cpp** [comment]
Yep, using code in flatpak/snap format will give you a lot of bugs if you are developing native platform apps.

**Comment by seikosantana** [comment]
Al

> I don't have much experience with Linux. Strange place in stacktrace: all gtk libs are from "/lib/x86_64-linux-gnu" but "libpixbufloader-png.so" is from "/snap/code/71/...". I suppose you are using snap package of vscode. Maybe it loads incorrect lib from snap (don't know how snap works). Can you try not snap version of vscode?

I tried installing the deb package. Now the MainWindow won't even show.

Anyway why is this issue closed?
