### ISSUE TITLE
Resizing the window doesn't work with HeaderBox

### ISSUE THREAD

**Issue by MadBit010** [GtkSharp/GtkSharp#28]
I have discovered the following problem.
When I create a window and replace the decorations with a HeaderBox. I can't change the size of my window with the mouse. The dragging of the window works.
I couldn't find anything on the internet.
I don't know if it's your libs or GtkSharp. win32. Or if it's just me.
The confusing is under Glade as prview everything works.

Thank you.
MadBit

Here's my class I'm trying it with.

    public class TemplateForm0
    {
        //private ApplicationWindow m_AppWindow;
        //private Window m_Window;
        //private Builder m_Builder;

        //[Builder.Object] private Notebook m_NotebookSource;

        //private Button m_Button1;

        public TemplateForm0()
        {
            Application.Init();
            Window win = new Window("Button Tester");
            win.DefaultWidth = 400;
            win.DefaultHeight = 200;
            win.BorderWidth = 10;

            HeaderBar hb = new HeaderBar();
            hb.ShowCloseButton = true;
            hb.Title = "HeaderBar example";
            hb.Subtitle = "An Example of HeaderBar";
            win.Titlebar = hb;

            Button button = new Button();
            Image img = Image.NewFromIconName("mail-send-receive-symbolic", IconSize.Button);
            button.Add(img);
            hb.PackEnd(button);

            Box box = new Box(Orientation.Horizontal, 6);

            button = new Button { new Arrow(ArrowType.Left, ShadowType.None) };
            box.Add(button);

            button = new Button { new Arrow(ArrowType.Right, ShadowType.None) };
            box.Add(button);

            hb.PackStart(box);

            win.Add(new TextView());

            win.DeleteEvent += new DeleteEventHandler(Window_Delete);

            win.ShowAll();

            //m_Builder = new Builder("GTKSharp_Template.AppTemplate.glade");
            //m_AppWindow = (ApplicationWindow)m_Builder.GetObject("m_AppWindowTemplate");

            //m_Builder.Autoconnect(this);

            //ScrolledWindow wnd0 = new ScrolledWindow();
            //TextView txt0 = new TextView();
            //wnd0.Add(new TextView());
            //m_NotebookSource.AppendPage(wnd0, new Label("SourceView0"));

            //Gtk.Settings.Default.XftRgba = "rgb";
            ////Gtk.Settings.Default.XftHinting = 1;
            ////Gtk.Settings.Default.XftHintstyle = "hintfull";

            //m_AppWindow.Resizable = true;

            //m_AppWindow.ShowAll();
        }

        static void btn_click(object obj, EventArgs args)
        {
            Console.WriteLine("Button Clicked");
        }

        static void Window_Delete(object obj, DeleteEventArgs args)
        {
            Application.Quit();
            args.RetVal = true;
        }

        protected void OnLocalDeleteEvent(object sender, DeleteEventArgs a)
        {
            Application.Quit();
            a.RetVal = true;
        }

    }

**Comment by cra0zy** [comment]
Works just fine on Windows, how did you get the win32 libs? Did you use https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Windows

**Comment by MadBit010** [comment]
Thanks for the quick answer.
Okay, that's it. I had only used NuGet packages before. After removing the GtkSharp.win32 entry from the installed NuGet-Packages. Then I adjusted the environment variables. Now everything running fine.

**Comment by cra0zy** [comment]
Side note, I'll try and get native libraries integrated into the nuget this week (see #17).
