### ISSUE TITLE
Error running build.sh

### ISSUE THREAD

**Issue by Dr-Kristau** [GtkSharp/GtkSharp#280]
Using 7995f132, I'm trying to run build.sh on Ubuntu 20.04.2 LTS - the result is:

```bash
:~/GtkSharp$ bash ./build.sh
Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) [0x000d3] in <b606e2bccc5640308485f2a84b00d95b>:0 
Could not restore NuGet packages.
```

**Comment by harry-cpp** [comment]
You have not installed all the needed packages for C#, I believe installing the mono-complete package does that on Ubuntu (+ ofcourse installing dotnet 5 and 3.1 SDKs from Microsofts website).

**Comment by Dr-Kristau** [comment]
I already have .NET installed:

```snap
:~$ sudo dotnet --list-sdks
5.0.400 [/snap/dotnet-sdk/137/sdk]
:~$ sudo dotnet --list-runtimes
Microsoft.AspNetCore.App 5.0.9 [/snap/dotnet-sdk/137/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.9 [/snap/dotnet-sdk/137/shared/Microsoft.NETCore.App]
``` 
So no, that is not the problem. Maybe the problem is related to [this issue](https://github.com/dotnet/runtime/issues/57481).

**Comment by harry-cpp** [comment]
You only have one SDK installed, .NET 5, however its only used to build .NET 5 projects, you need to install other SDK versions if you wish to build projects that are not targeting .NET 5.

In this case you need to install mono related packages as they contain .NET Framework assemblies for Linux.

**Comment by Dr-Kristau** [comment]
Thank you, my mistake - I hadn't appreciated the mono framework dependency.
