### ISSUE TITLE
Drag and Drop event not firing

### ISSUE THREAD

**Issue by nerdunit** [GtkSharp/GtkSharp#281]
Hi, I'm using a Layout inside a Notebook and when I make the DragDrop event call a function using
```
private MainWindow(Builder builder) : base(builder.GetRawOwnedObject("MainWindow"))
{
builder.Autoconnect(this);
_sideloadLayout.DragDrop += SideloadLayout_DragBegin;
}

private void SideloadLayout_DragBegin(object sender, DragDropArgs a)
        {
            Console.WriteLine("drag drop!");
        }
```

**Comment by nerdunit** [comment]
using ```_notebook.DragDrop += SideloadLayout_DragBegin;``` I managed to get drag drop to work on windows, but I need a drag and drop for files, however this is the only Drag event that is triggered

**Comment by PaulIRL** [comment]
And using the exact same code does not work on the linux build

**Comment by harry-cpp** [comment]
You are gonna have to look at a tutorial on how to use Gtk drag and drop, its not as simple as connecting to one event.

Here is a snippet from one of my very old projects that had the functional drag and drop between my application and Nautilus (aka. GNOME Files):

```cs
Drag.SourceSet(this._tree, 0, null, Gdk.DragAction.Move);
Drag.DestSet(this._tree, 0, null, 0);

_tree.DragBegin += Tree_DragBegin;
_tree.DragMotion += Tree_DragMotion;
_tree.DragDrop += Tree_DragDrop;
_tree.DragDataReceived += Tree_DragDataReceived;
_tree.DragEnd += (o, e) => _dragSourceItems.Clear();
```

```cs
private void Tree_DragDataReceived(object o, DragDataReceivedArgs args)
{
    args.RetVal = true;

    if (args.SelectionData.Length > 0 && args.SelectionData.Format == 8)
    {
        var data = args.SelectionData.Data;
        var encoded = System.Text.Encoding.UTF8.GetString(data);
        var paths = new List<string>(encoded.Split('\r', '\n'));

        foreach (var p in paths)
        {
            if (p.StartsWith("file://"))
            {
                _dragSourceItems.Add(new Uri(p).LocalPath);
            }
        }

        DropIt(args.X, args.Y, true);
    }
}
```

**Comment by nerdunit** [comment]
Using the exact code you provided, with a new project using just a window and a tree in it, only the dragmotion event does fire, if the project you made to use gtksharp drag and drop is open source, can you please give me the link to it?

**Comment by harry-cpp** [comment]
It's not open source, you need to fill up all 5 events for it to work as the move event is the important one for accepting dropping iirc, I've only provided the snippet for the final one.

You can also check out: https://github.com/harry-cpp/MonoGame/blob/06ec9e34c9e01a7ab62adee1da29e3bfb03ded1e/Tools/Pipeline/Gtk/Widgets/ProjectView.cs#L69

You'll probably find better information by googling it.
