### ISSUE TITLE
Distribute GtkSharp and GTK runtime

### ISSUE THREAD

**Issue by seikosantana** [GtkSharp/GtkSharp#290]
This is more to a question than an issue.
I've seen that on Windows it downloads the GTK runtimes automatically, saying GTK has not been detected although I have already installed [this GTK Runtime](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer).

I didn't see anything about distributing the runtime for GTKSharp. Is there any guide i can follow? I don't want to install MSYS on target production machine if possible.

Thanks in advance

**Comment by lytico** [comment]
i use 
this https://github.com/GtkSharp/Dependencies & 
this https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

**Comment by dsoronda** [comment]
I found this link [how-to-distribute-a-gtk-application-on-windows](https://stackoverflow.com/questions/49092784/how-to-distribute-a-gtk-application-on-windows), maybe it will help you.

**Comment by seikosantana** [comment]
Thanks. Seems like having GTK installed on MSYS2 and having the runtime at the same time causes some problems. I tried running it and it says some libs are missing, but since i have MSYS2 with GTK3, i removed the windows runtime and the error is gone.

I also tested the runtime lytico mentioned: https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer in Windows Sandbox and confirmed it is the only package to install on target machine.

Thanks a lot @lytico @dsoronda

**Comment by miegir** [comment]
By the way, in addition to that 64-bit GTK installer I created my own fork with 32-bit GTK for windows: https://github.com/miegir/GTK-for-Windows-Runtime-Environment-Installer-32. It contains not all of the libraries (and executables) that 64-bit version contains, but that are sufficient for my application and hopefully for any GtkSharp application.

**Comment by seikosantana** [comment]
> By the way, in addition to that 64-bit GTK installer I created my own fork with 32-bit GTK for windows: https://github.com/miegir/GTK-for-Windows-Runtime-Environment-Installer-32. It contains not all of the libraries (and executables) that 64-bit version contains, but that are sufficient for my application and hopefully for any GtkSharp application.

Cool i was also looking for this.
