### ISSUE TITLE
GtkSwitch StateSet event not firing

### ISSUE THREAD

**Issue by seikosantana** [GtkSharp/GtkSharp#294]
I'm trying to do something when a switch is toggled. Here's what i tried:

```cs
        public LogWindow() : this(new Builder("abs-auto.glade"))
        {
            btnCloseLog.Clicked += CloseWindow;
            this.DeleteEvent += CloseWindow;
            this.switchEnableLog.StateSet += HandleSwitchChanges;
        }

        private void HandleSwitchChanges(object sender, EventArgs e)
        {
            EnableLogsChanged?.Invoke(this, switchEnableLog.Active);
            WriteLog("Logs", $"Enable logging is {switchEnableLog.Active}");
        }
```

The HandleSwitchChanges method is never invoked toggling the switch. Am I not handling the correct event?

**Comment by zii-dmg** [comment]
```csharp
var btn = new Switch();

btn.StateSet += OnStateSet;
// or
btn.AddNotification("active", OnActiveNotify); // recommended in gtk docs

[GLib.ConnectBefore]
void OnStateSet(object o, StateSetArgs args)
{
    Console.WriteLine("StateSet " + args.State);
}

void OnActiveNotify(object o, GLib.NotifyArgs args)
{
    var btn = (Switch)o;
    Console.WriteLine("Active notify " + btn.Active);
}
```

**Comment by seikosantana** [comment]
> some signals only get to your callback if callback connected before default signal handler.

Does that mean I can put the `GLib.ConnectBefore` attribute on every eventhandlers to ensure it always get to callback?

**Comment by zii-dmg** [comment]
Don't know best way, I only add `ConnectBefore` if normal version not worked.

Some info about `ConnectBefore` from old gtksharp 2 faq:

> As of release 0.15, Gtk# started using the CONNECT_AFTER flag when connecting event handlers to signals. This means that the event handlers are not run until after the default signal handlers, which means that the widget will be updated when the event handlers run. A side effect of this change is that in the case where default handlers return true to stop signal propogation, Gtk# events will not be emitted. This is the case for example in Gtk.Button, where the button-press-event default signal handler is overridden to emit Pressed events. TreeView has a similar situation.
>
> While potentially confusing, this is not really a bug. When you use a Gtk.Button, you are getting a widget that emits Pressed events in response to Button1 presses. If you also want your Button to change colors, or popup a context menu on Button3 presses, that's not a Gtk.Button. The correct way to implement such a widget is to subclass Gtk.Button and override the OnButtonPressEvent virtual method to implement the new behaviors you desire.
>
> Many Gtk+ developers have gotten used to being able to do these kind of things via signal handlers since g_signal_connect is typically used without the CONNECT_AFTER flag in C code. If you are convinced that you want to use g_signal_connect to pierce the encapsulation of a Widget and alter its default behavior, you can tag your callback method with the [GLib.ConnectBefore] attribute to force it to run before the default handler. This attribute was added in version 0.18 due to public outcry, but the default behavior is still to run event handlers after the default handler.

**Comment by seikosantana** [comment]
Thanks a lot!
