### ISSUE TITLE
Segmentation fault on Manjaro Linux when used with Microsoft.Data.Sqlite

### ISSUE THREAD

**Issue by jurijr** [GtkSharp/GtkSharp#296]
Following code yields "segmentation fault (core dumped)" when opening sqlite database after Application.Run() is called.
Linux Manjaro XFCE 21.1.6.2, does not seem to replicate on non Arch based Linux distributions.
Did anyone find any workarounds?

Example:

`.net6`
`<OutputType> Exe</OutputType>`
Nugets:
- `GtkSharp 3.24.24.34`
- `Microsoft.Data.Sqlite 6.0.0`

```
using Gtk;
using Microsoft.Data.Sqlite;

Task.Run(() =>
{
    Task.Delay(100).Wait(); //ensures it executes after Application.Run()

    using var connection = new SqliteConnection("Data Source=test.db");
    try
    {
        Console.WriteLine("Opening.");

        connection.Open(); //at this point application crashed with "segmentation fault (core dumped)"

        Console.WriteLine("Opened.");
        connection.Close();
        Console.WriteLine("Closed.");
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
        throw;
    }
});

Application.Init();
Application.Run();
```

**Comment by jurijr** [comment]
Update: last working GtkSharp version seems to be 3.22.24.31

**Comment by harry-cpp** [comment]
If the code above crashes for you, it has nothing to do with GtkSharp, we don't provide any native libraries for Linux, nor has any C# call been made.
