### ISSUE TITLE
A compatible charting library?

### ISSUE THREAD

**Issue by seikosantana** [GtkSharp/GtkSharp#304]
Do we have a charting library like the one in Ubuntu's System Monitor that is compatible with GTKSharp?
![image](https://user-images.githubusercontent.com/35630407/146501785-d787ad90-8a2e-48a7-812e-55c63a5d37fb.png)

**Comment by zii-dmg** [comment]
https://github.com/oxyplot/oxyplot-gtksharp
Nuget is old, but latest source code supports this GtkSharp. Did not test.

**Comment by seikosantana** [comment]
I found this one
https://github.com/tschoonj/gtkmm-plplot

Is there any way to consume this in GtkSharp?

**Comment by zii-dmg** [comment]
No. gtkmm-plplot is С++. gtkmm is C++ wrapper around gtk, plplot is C library for plots. Of course someone can create plplot wrapper to C# + GtkSharp. There is something - https://github.com/surban/PLplotNet but it is not for GtkSharp.

**Comment by lytico** [comment]
there is https://github.com/oxyplot/oxyplot
which has https://github.com/oxyplot/oxyplot/tree/develop/Source/OxyPlot.SkiaSharp
and SkiaSharp has a GtkSharp - Backend:
https://github.com/mono/SkiaSharp/blob/main/source/SkiaSharp.Views/SkiaSharp.Views.Gtk3/SkiaSharp.Views.Gtk3.csproj

maybe this combination can do the job

**Comment by seikosantana** [comment]
> https://github.com/oxyplot/oxyplot-gtksharp Nuget is old, but latest source code supports this GtkSharp. Did not test.

Tried this one and works pretty great, altho didn't test everything but usable for my needs
