### ISSUE TITLE
Check if GTK Runtime is Available before loading application

### ISSUE THREAD

**Issue by seikosantana** [GtkSharp/GtkSharp#305]
Is there any way to get the application to check if GTK Runtime is available before we attempt to load GTK, or intercept it before proceeding?

I'm trying to get and install the runtime if GTK Runtime isn't found.

Thanks in advance

**Comment by zii-dmg** [comment]
Not in nuget:
```csharp
bool found = Gtk.Global.IsSupported
```

Nuget:
```csharp
try {
    var _ = Gtk.Global.MajorVersion;
   // gtk is found
}
catch {
   // gtk is not found
}
```
Not tested.

**Comment by seikosantana** [comment]
Thanks a lot!
