### ISSUE TITLE
DllNotFoundExe

### ISSUE THREAD

**Issue by seikosantana** [GtkSharp/GtkSharp#330]
I'm trying to create a Gtk Application on Windows with .NET Framework and Mono.
When trying to start the application under Visual Studio, I am getting

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Gtk.Application' threw an exception.
  Source=GtkSharp
  StackTrace:
   at Gtk.Application.Init()
   at ABS.Pos.MainClass.Main(String[] args) in D:\Temp\japfa-abs\ABS.Pos\Program.cs:line 9

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll

Under dotnet core everything is running correctly, but not with GtkSharp from nuget.
I have gtk installed in MSYS2 and have installed runtime packages. What could be the problem?

Thanks in advance

**Comment by pedrohex** [comment]
Wrong  repo ... anyway, just install gtksharp MSI from the right one.

**Comment by seikosantana** [comment]
I installed 32 bit runtime of GTK3 and it works.

> Wrong repo
Did I miss something?
