### ISSUE TITLE
Using Hdy-Prefixed Widgets?

### ISSUE THREAD

**Issue by seikosantana** [GtkSharp/GtkSharp#332]
Hi, I have just switched to Flatpak version of Glade after the snap version stops working, and i found out there's many Hdy-prefixed widgets I can use in glade. Is it possible to write GtkSharp application with those widgets?

**Comment by jkarpio** [comment]
I don't think so, you can't use it unless they have a corresponding gtk sharp binding

**Comment by seikosantana** [comment]
I've realized that Hdy comes from libhandy
