### ISSUE TITLE
The "DownloadFile" task was not given a value for the required parameter "DestinationFolder".

### ISSUE THREAD

**Issue by seikosantana** [GtkSharp/GtkSharp#335]
It's my first time working on GtkSharp application on Visual Studio and i got this `The "DownloadFile" task was not given a value for the required parameter "DestinationFolder".` error and I couldn't build.

It doesn't happen with dotnet cli. Does it have to be configured to work with VS?

Thanks in advance

**Comment by zii-dmg** [comment]
I think it is task from GtkSharp nuget package (file GtkSharp.targets). On Windows it tries to download Gtk binaries and unpack somewhere in %LOCALAPPDATA%. This task can be disabled by adding to csproj:
```xml
<PropertyGroup>
  <SkipGtkInstall>true</SkipGtkInstall>
</PropertyGroup>
```

I deleted GtkSharp.targets file in my private fork to disable possible network activity on build. And also I use Gtk binaries from MSYS2 with adding gtk dlls path to %PATH%. Also there is https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer with gtk dlls from MSYS2.

**Comment by seikosantana** [comment]
Thank you that works.

Building with dotnet cli before attempting to Start in Visual Studio also could do it.
