### ISSUE TITLE
no bindings for gdk_cairo_surface_create_from_pixbuf / gdk_pixbuf_get_from_surface

### ISSUE THREAD

**Issue by medovina** [GtkSharp/GtkSharp#347]
GDK includes two useful functions to convert between GDK pixbufs and Cairo surfaces:

* [gdk_cairo_surface_create_from_pixbuf](https://docs.gtk.org/gdk3/func.cairo_surface_create_from_pixbuf.html)
* [gdk_pixbuf_get_from_surface](https://docs.gtk.org/gdk3/func.pixbuf_get_from_surface.html)

Unfortunately it appears that these are not exposed in GtkSharp.

**Comment by cameronwhite** [comment]
`gdk_pixbuf_get_from_surface` should be available as a constructor on `Gdk.Pixbuf` (this was added in #176)
I think `gdk_cairo_surface_create_from_pixbuf` is available as `Gdk.CairoHelper.SurfaceCreateFromPixbuf()` based on https://github.com/GtkSharp/GtkSharp/blob/451755439e50411ac383717884d53bf43c7b2bdb/Source/Libs/GdkSharp/GdkSharp-api.xml#L4533

**Comment by medovina** [comment]
Aha - I had not discovered those methods.  Great, thanks!
