### ISSUE TITLE
Creating and disposing a Pango.Layout leaks GLib.ToggleRef instances

### ISSUE THREAD

**Issue by DoubleOhHarm** [GtkSharp/GtkSharp#361]
Hi maintainers,

Creating and disposing a Pango.Layout leaks GLib.ToggleRef instances. 

To reproduce the issue execute the following code:
```
Gtk.Application.Init();
using Gtk.Window window = new Gtk.Window(Gtk.WindowType.Toplevel);

while (true)
{
	using Pango.Layout pangoLayout = new Pango.Layout(window.PangoContext);
}
```

Using NET6 / GtkSharp 3.24.24.38 / Windows 11. Profiled with JetBrains memory profiler.

I'm new here, if I should report issues different please let me know!

**Comment by lytico** [comment]
see this discussion: https://github.com/GtkSharp/GtkSharp/issues/226
maybe similar problem?
try with gc.collect within the loop
or add a counter, then every 1000 or so counts make a gc collect

something like:

```
Gtk.Application.Init();
using Gtk.Window window = new Gtk.Window(Gtk.WindowType.Toplevel);
var counter = 0;

while (true)
{
	using Pango.Layout pangoLayout = new Pango.Layout(window.PangoContext);
       counter ++;
       if (counter == 1000) {
            GC.Collect();   
       }
}
```

**Comment by DoubleOhHarm** [comment]
Hi!

Comment https://github.com/GtkSharp/GtkSharp/issues/226#issuecomment-802593429 on #226 is definitely related. 

Adding a custom message loop to handle the queued handlers fixes this issue:
`while (Gtk.Application.EventsPending()) Gtk.Application.RunIteration(false);`

I did however found another issue in my quest to find my memory leak. Will link that one after creating it.

Thank you for your respone.
