### ISSUE TITLE
Invalid deprecation

### ISSUE THREAD

**Issue by workgroupengineering** [GtkSharp/GtkSharp#362]
According to [this](https://docs.gtk.org/gtk3/method.Widget.modify_fg.html) documentation.
Widget OverrideColor is marked as obsolete insteand of ModifyFg.
There are other methods that have the same problem.

Affected Nuget version: [3.24.24.34](https://github.com/GtkSharp/GtkSharp/releases/tag/3.24.24.34)

**Comment by zii-dmg** [comment]
[gtk_widget_modify_fg](https://docs.gtk.org/gtk3/method.Widget.modify_fg.html) deprecated since gtk 3.0
[gtk_widget_override_color](https://docs.gtk.org/gtk3/method.Widget.override_color.html) deprecated since gtk 3.16
Both are deprecated in GtkSharp. What's wrong?

**Comment by workgroupengineering** [comment]
> [gtk_widget_override_color](https://docs.gtk.org/gtk3/method.Widget.override_color.html) deprecated since gtk 3.16
> Both are deprecated in GtkSharp. What's wrong?
Sorry it was my mistake
