### ISSUE TITLE
Using Pango.CairoHelper.CreateLayout to create a Pango.Layout leaks unmanaged memory

### ISSUE THREAD

**Issue by DoubleOhHarm** [GtkSharp/GtkSharp#363]
Using Pango.CairoHelper.CreateLayout to create a Pango.Layout leaks unmanaged memory (a lot!). 

Referencing the [GTK docs](https://docs.gtk.org/PangoCairo/func.create_layout.html) reveals that a separate Context is created for each Layout. However, explicitly disposing the Context of the instantiated Layout has no effect.

To reproduce the issue execute the following code:

```
Gtk.Application.Init();

var surface = new Cairo.ImageSurface("image.jpg");
var context = new Cairo.Context(surface);

while (true)
{
	using Pango.Layout pangoLayout = Pango.CairoHelper.CreateLayout(context);

        //(un)commenting the call to Dispose has no effect
	pangoLayout.Context.Dispose();

	while (Gtk.Application.EventsPending()) Gtk.Application.RunIteration(false);
}
```

Using NET6 / GtkSharp 3.24.24.38 / Windows 11. Profiled with JetBrains memory profiler.

**Comment by lytico** [comment]
sample here:
https://github.com/lytico/GtkSharp/blob/lytico/issues/363/Source/Samples/Sections/Miscellaneous/PangoLayoutMemorySection.cs

**Comment by lytico** [comment]
Tests:

a first run with 3 498 228 iterations:

```
GetTotalMemory	before	Loop	1 028 008	before	Arrange	968 928
Leak:	615 312
GetTotalMemory	after	Loop	1 643 320	Loops	3 498 228
```

a second run with 4 220 703 iterations. 
we got a "leak" with 217 896 bytes compared to first run:

```
leakSinceLastRun	217 896
GetTotalMemory	before	Loop	1 187 328	before	Arrange	1 186 824
Leak:	305 552
GetTotalMemory	after	Loop	1 492 880	Loops	4 220 703
```

a third, short run with 37 634 iterations. 
we got a "leak" with 1 424 bytes compared to second run:
```
leakSinceLastRun	1 424
GetTotalMemory	before	Loop	1 188 360	before	Arrange	1 188 248
Leak:	453 384
GetTotalMemory	after	Loop	1 641 744	Loops	37 634
```

all following runs, no matter who much iterations it runs, are "leaking" around 2 000 bytes

```
leakSinceLastRun	1 672
GetTotalMemory	before	Loop	1 192 736	before	Arrange	1 191 672
Leak:	181 128
GetTotalMemory	after	Loop	1 373 864	Loops	2 724 245
```

**Comment by DoubleOhHarm** [comment]
Thank you for your response. I pulled the refered branch and executed the test on my own computer.

In the output I see comparable data as you posted. However, if I profile the test with JetBrains when pressing button twice, I get the following graph:
![afbeelding](https://user-images.githubusercontent.com/89873404/179922264-0d1d4829-028d-4726-95df-5e7946539c58.png)

Reading MSDN on GC.GetTotalMemory it returns: A number that is the best available approximation of the number of bytes currently allocated in managed memory.

So I updated the Loop method in the MemoryLeakWatcher like this (just replacing call to GC.GetTotalMemory with GetMemoryUsage method):

```
public void Loop()
	{
		Process process = Process.GetCurrentProcess();

		long GetMemoryUsage()
		{
			process.Refresh();

			return process.WorkingSet64;
		}

		var count = 0;

		ApplicationOutput.WriteLine(string.Empty);

		var initMem = GetMemoryUsage();

		if (LastInitMem is { })
		{
			var leakSinceLastRun = initMem - LastInitMem;
			ApplicationOutput.WriteLine($"{nameof(leakSinceLastRun)}\t{leakSinceLastRun:N0}");
		}

		LastInitMem = initMem;

		Arrange?.Invoke();

		DispatchPendingEvents();

		var startmem = GetMemoryUsage();
		ApplicationOutput.WriteLine($"{nameof(GC.GetTotalMemory)}\tbefore\t{nameof(Loop)}\t{startmem:N0}\tbefore\t{nameof(Arrange)}\t{initMem:N0}");

		var memAllocated = 0UL;

		while (Running)
		{

			memAllocated += Act.Invoke();

			DispatchPendingEvents();

			count++;

			if (!Running)
				break;

		}

		var endmem = GetMemoryUsage();

		var msg = $"Leak:\t{(endmem - startmem):N0}";

		if (memAllocated > 0)
			msg = $"{msg}\t{nameof(memAllocated)}\t{memAllocated:N0}";

		ApplicationOutput.WriteLine(msg);

		ApplicationOutput.WriteLine($"{nameof(GC.GetTotalMemory)}\tafter\t{nameof(Loop)}\t{endmem:N0}\t{nameof(Loop)}s\t{count:N0}");

		Cleanup?.Invoke();
		DispatchPendingEvents();

		initMem = GetMemoryUsage();
	}
```

When using process.WorkingSet64 or VirtualMemorySize64 you will see the leak:

```
GetTotalMemory	before	Loop	97.038.336	before	Arrange	86.671.360
Leak:	49.221.632
GetTotalMemory	after	Loop	146.259.968	Loops	52.981

leakSinceLastRun	53.501.952
GetTotalMemory	before	Loop	149.094.400	before	Arrange	140.173.312
Leak:	130.998.272
GetTotalMemory	after	Loop	280.092.672	Loops	159.435
```

**Comment by zii-dmg** [comment]
I think return type of `Pango.CairoHelper.CreateLayout` (`pango_cairo_create_layout`) should be `owned="true"` in api xml. Same for `pango_cairo_create_context`.

**Comment by zii-dmg** [comment]
Can someone test my PR for leaks?

**Comment by lytico** [comment]
@zii-dmg yes, i'll test it

**Comment by lytico** [comment]
running sample with pr #365 + added process memory 
```
GetTotalMemory	before	Loop	1 001 576	before	Arrange	949 832
Leak:	managed	739 272	process	13 303 808
GetTotalMemory	after	Loop	1 740 848	Loops	1 407 664

leakSinceLastRun	managed	330 192	process	14 921 728
GetTotalMemory	before	Loop	1 280 152	before	Arrange	1 280 024
Leak:	managed	556 928	process	-626 688
GetTotalMemory	after	Loop	1 837 080	Loops	4 042 324

leakSinceLastRun	managed	1 136	process	-1 241 088
GetTotalMemory	before	Loop	1 281 280	before	Arrange	1 281 160
Leak:	managed	365 880	process	-380 928
GetTotalMemory	after	Loop	1 647 160	Loops	3 543 433

leakSinceLastRun	managed	0	process	-434 176
GetTotalMemory	before	Loop	1 281 272	before	Arrange	1 281 160
Leak:	managed	598 968	process	81 920
GetTotalMemory	after	Loop	1 880 240	Loops	4 570 706

leakSinceLastRun	managed	0	process	-12 288
```

**Comment by lytico** [comment]
@DoubleOhHarm please, post your results. would be interesting.

**Comment by DoubleOhHarm** [comment]
@lytico  @zii-dmg Confirmed!

![afbeelding](https://user-images.githubusercontent.com/89873404/180148500-331459d5-0a83-4d00-bb2d-d1d2e9a59b0d.png)

Thank you for your quick responses.

Greetings from the Netherlands.
