### ISSUE TITLE
The nested type `BoxChild' does not exist in the type `Gtk.Box'

### ISSUE THREAD

**Issue by jordimas** [GtkSharp/GtkSharp#368]
Hello,

I have a project called gbrainy (https://gitlab.gnome.org/GNOME/gbrainy) which I was able to compile with old gtk-sharp (https://github.com/mono/gtk-sharp).

When compiling with GtkSharp throws this error:

/Widgets/Toolbar.cs(88,23): error CS0426: The nested type `BoxChild' does not exist in the type `Gtk.Box'

See: https://gitlab.gnome.org/GNOME/gbrainy/-/blob/master/src/Clients/Classical/Widgets/Toolbar.cs#L88

Does the BoxChild type has been removed by mistake or has been replaced by something else?

Since some Linux distros still distribute https://github.com/mono/gtk-sharp and some may start distributing GtkSharp, it will be great to maintain as much as possible compatibility with the gtk-sharp API.

Thanks

**Comment by lytico** [comment]
BoxChild is still defined in generated Source/Libs/GtkSharp/**Generated**/Gtk/Box.cs

what version of GtkSharp do you use?

>  it will be great to maintain as much as possible compatibility with the gtk-sharp API.

GtkSharp is a wrapper around Gtk 3.22,  so you'll have to migrate to Gtk 3.22 API

We don't support Gtk 2.x

**Comment by jordimas** [comment]
gbrainy is a GTK 3.0 application, not GTK 2.0
GTKSharp used 3.22.2
This application works just fine with gtk-sharp

I have no access right now to a dev box. I will try to get GtkSharp compiled to see why this fails.
