### ISSUE TITLE
How to get the DeltaX and DeltaY from a scroll event ?

### ISSUE THREAD

**Issue by na2axl** [GtkSharp/GtkSharp#37]
It seems that the current version of GtkSharp have not implemented the `delta_x` and `delta_y` values in the `EventScroll` event args, but they exist in the native structure:
```c
struct GdkEventScroll {
  GdkEventType type;
  GdkWindow *window;
  gint8 send_event;
  guint32 time;
  gdouble x;
  gdouble y;
  guint state;
  GdkScrollDirection direction;
  GdkDevice *device;
  gdouble x_root, y_root;
  gdouble delta_x;
  gdouble delta_y;
  guint is_stop : 1;
};
```

So there is another way to get these values ?

**Comment by cra0zy** [comment]
I've fixed this in develop, will publish a new set of nugets on Sunday.

**Comment by cra0zy** [comment]
New nugets are cooking, should be up in an hour, sorry for being late on this.

**Comment by na2axl** [comment]
No problem, I'm just waiting for this :-)

**Comment by cra0zy** [comment]
The nugets are up btw.
