### ISSUE TITLE
Lack of documentation regarding versioning

### ISSUE THREAD

**Issue by myrup** [GtkSharp/GtkSharp#40]
Hey.

I can't seem to find any documentation on GtkSharp versioning, which matters, seeing as GTK+ seems to care little for backward compatibility.

It would be nice if the Readme.md answered the following:
Is GtkSharp currently only supporting Gtk3 or is there still Gtk2 support?

Whats the meaning of the release versioning numbers? How does the latest GtkSharp release version (3.22.24.36) relate to the latest gtk release (3.22.29) ?

Thanks!

**Comment by myrup** [comment]
And it would definitely be nice to add the information from #20  :)

**Comment by cra0zy** [comment]
I will not be adding the info about it to the readme since... I don't know how to nicely phrase this so I'll skip finishing the sentence.

> Is GtkSharp currently only supporting Gtk3 or is there still Gtk2 support?

Gtk 3 only... the API is different between the 2.

> Whats the meaning of the release versioning numbers? How does the latest GtkSharp release version (3.22.24.36) relate to the latest gtk release (3.22.29) ?

 - 3.22.24 - Gtk version the wrappers are generated against
 - 36 - build number
