### ISSUE TITLE
Is this project abandoned? I'm looking for proper documentation.

### ISSUE THREAD

**Issue by gluckez** [GtkSharp/GtkSharp#404]
I'm trying to port a project from GTK2 to GTK3, using GTKSharp, but am constantly running into deprecated symbols that are not documented anywhere as far as I can find.
Is there any proper porting guide that you can point me to?
I found some porting guides but not of them are clear or even complete.

For example: there used to be a method called Style.Light(StateType...) which was removed,
but I don't find any alternative documented anywhere.
Same for the SizeRequested, I know it's supposed to be replaced by the OnGetPreferredWidth/Height methods,
but it's not documented what this means or how these are supposed to be used.
I'm just looking for guidance or some help because I'm pulling my hair out at this point.

If you want to know what project it is, look here:
https://github.com/dotdevelop/dotdevelop/issues/109

**Comment by badcel** [comment]
I only know of the official documentation: https://docs.gtk.org/gtk3/migrating-2to3.html

**Comment by lytico** [comment]
it's not abandoned at all, just take a look at
https://github.com/GtkSharp/GtkSharp/pulls?q=is%3Apr+is%3Aclosed

as of documentation:
see: https://github.com/GtkSharp/GtkSharp/issues/245

documents about migrating gtk2 -> gtk3 is not in the scope of this project
as @badcel mentioned, this should be a scope of the gtk-project

as of using GktSharp in dotdevelop, you can find a GtkSharp-based version of Xwt here:
https://github.com/lytico/xwt/tree/lytico_gtksharp

if you compare the Gtk2-Implementation with the GtkSharp-Implementation in
https://github.com/lytico/xwt/tree/lytico_gtksharp/Xwt.Gtk/Xwt.GtkBackend
you'll find some hints.

As of Style:
a lot of Style features are done with CSS in Gtk3.
you'll find some hints here:
https://github.com/jsuarezruiz/maui-linux/blob/main-linux/src/Core/src/Platform/Gtk/GtkCssExtensions.cs

**Comment by lytico** [comment]
> supposed to be replaced by the OnGetPreferredWidth/Height methods,
> I'm just looking for guidance or some help because I'm pulling my hair out at this point.

this helped me (but lost a lot of hairs too):

https://github.com/lytico/xwt/blob/77f14f8351db3bce4ecab143d32ebf34e690643b/Xwt.Gtk/Xwt.GtkBackend/CanvasBackendGtk2.cs#L33-L38

vs

https://github.com/lytico/xwt/blob/77f14f8351db3bce4ecab143d32ebf34e690643b/Xwt.Gtk/Xwt.GtkBackend/CanvasBackendGtk3.cs#L54-L79

------------------

https://github.com/lytico/xwt/blob/77f14f8351db3bce4ecab143d32ebf34e690643b/Xwt.Gtk/Xwt.GtkBackend/BoxBackendGtk2.cs#L39-L45

vs

https://github.com/lytico/xwt/blob/77f14f8351db3bce4ecab143d32ebf34e690643b/Xwt.Gtk/Xwt.GtkBackend/BoxBackendGtk3.cs#L75-L120
