### ISSUE TITLE
Exception thrown when subclassing Gtk.Window

### ISSUE THREAD

**Issue by myrup** [GtkSharp/GtkSharp#41]
Hey.

I'm experiencing an issue when subclassing `Gtk.Window` running MacOS X .Net Core.

This minimal example launches a window fine:
```c#
public static void Main() {
    Application.Init();
    var window = new Window("Title");
    window.Show();
    Application.Run();
}
```

The same fails if I attempt to subclass `Gtk.Window`:
```c#
class TestWindow : Gtk.Window {
    public TestWindow()
        : base("Title") {
    }
}

public static void Main() {
    Application.Init();
    var window = new TestWindow();
    window.Show();
    Application.Run();
}
```
The error thrown is of type `GLib.MissingIntPtrCtorException`:
"Unable to construct instance of type Test.Program+TestWindow from native object handle. Instance of managed subclass may have been prematurely disposed."

**Comment by cra0zy** [comment]
Hmm, I'm unable to reproduce the error on Linux. Try using `base(WindowType.Toplevel)` and tell me if that works.

**Comment by myrup** [comment]
@cra0zy The same exception is thrown for `base(WindowType.Toplevel)`, but I can confirm it works on raspbian.

**Comment by myrup** [comment]
@cra0zy I've now managed to subclass `Window`on Mac OS X. I'll try to investigate what could be causing the problems and share my findings.

**Comment by myrup** [comment]
Unable to reproduce and I can't tell what was changed in the environment, perhaps a system reboot did the trick. Closing for now. I'll reopen if it comes back. Thanks!
