### ISSUE TITLE
System.AccessViolationException while setting Image.IconName or Label.Text

### ISSUE THREAD

**Issue by terorist** [GtkSharp/GtkSharp#415]
I am getting exception when I am trying to periodically update images. I download data from a device every second and then I refresh Labels and Images according to new values. The exception is:

    Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
    at Gtk.Image.set_IconName(System.String)
    at MainWindow.uiChangeIndicatorState() ...

I am updating about 30 images and about 25 labels. The Exception is thrown in 10 minutes (when I make the refresh interval shorter it appears earlier), when I changed images for labels then the exeption was thrown later. The code updating images looks like this:

    private bool UpdateValues()
    {
        MyDataType data = device.ReadData(); // For now synchronous reading, but async is in progress

        UiChangeIndicatorState(firstIndicator, data?.firstBoolData);
        // Other 30 indicators
        myLabel.Text = data.valueInt.ToString();
        // Other 25 Labels
    }

    private void uiChangeIndicatorState(Image target, bool? state)
    {
        const string indFalse = "dialog-error";
        const string indTrue = "dialog-information";
        const string indDisconnected = "dialog-question";

        if (state.HasValue)
            target.IconName = state.Value ? indTrue : indFalse;
        else
            target.IconName = indDisconnected;
    }

**Comment by lytico** [comment]
Remarks:

https://docs.gtk.org/gtk3/method.Image.get_icon_name.html

https://docs.gtk.org/gtk3/property.Image.icon-name.html

**Comment by lytico** [comment]
@terorist please show the code where you create the Image

**Comment by lytico** [comment]
tested here, no issues found:

https://github.com/lytico/GtkSharp/blob/lytico/issues/415_Image_SetIconName/Source/Samples/Sections/Miscellaneous/Issue415_Section.cs

**Comment by terorist** [comment]
I don't create the Image, I used Glade so it is generated for me:

    public MainWindow() : this(new Builder("MainWindow.glade"))
    {
    }

    private MainWindow(Builder builder) : base(builder.GetRawOwnedObject("MainWindow"))
    {
        builder.Autoconnect(this);
        // rest of constructor
    }

I have created an [question on SO](https://stackoverflow.com/questions/76994862/c-system-accessviolationexception-while-working-with-gtksharp?noredirect=1#comment135733346_76994862), if it still won't help to reproduce the bug, then I'll share whole MainWindow code.

**Comment by lytico** [comment]
as mentioned in your [question on SO](https://stackoverflow.com/questions/76994862/c-system-accessviolationexception-while-working-with-gtksharp?noredirect=1#comment135733346_76994862), the error occurs with Gtk.Label.set_Text(System.String). 

So the error is maybe in 
1) your  device.ReadData(). Show your code.
2) your code in class MainWindow / problem with Glade / Builder

**Comment by lytico** [comment]
i created a test using glade, no errors found:

https://github.com/lytico/GtkSharp/tree/lytico/issues/415_Image_SetIconName/Source/TemplateTest

i can now exclude an error in GtkSharp so far.

**Comment by terorist** [comment]
You are right, it seems that it is my fault. Everything seems working fine when I placed correctly loading values from device and used `Threads.AddIdle(0, UpdateValues)`. Without Threads.AddIdle it can throw the exception. It's just begginers mistake (it's first time I am using GTK).

Thank you for your time and I am sorry for bothering you with such stupid mistake.

I am attaching simple project, where I was able to get the exception. To get the exception comment the line 63 and uncomment line 64 of MainWindow.cs. The 30 ms refresh is fast (can be slower) but with real device the exception was thrown with 1s refresh.

[GTKTestException.zip](https://github.com/GtkSharp/GtkSharp/files/12478442/GTKTestException.zip)

**Comment by lytico** [comment]
threading & GUI is very cumbersome.

GtkSharp is a very thin layer over the Gtk-Libs, so you have to implement everything from the basics.
There is no build-in support for threading at all, like eg. in Blazor, where everything has an async overload.

So your mistake isn't sooo "beginners"
