### ISSUE TITLE
Using GtkSharp with self-built GTK? Keyboard hook issue

### ISSUE THREAD

**Issue by ividyon** [GtkSharp/GtkSharp#422]
Disclaimer: I'm new to wrapper libraries like this, and I have basically no idea how they function.

Users of an app of ours that uses GtkSharp report weird keyboard lag issues when using the program. I have found a [seeming related-looking issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/2015) with GTK and would like to try the solutions presented within, which involve removing a low level keyboard hook in GTK.

However, I'm not directly using GTK; I'm using GtkSharp.

I browsed the repository a little and couldn't find any location where GTK is being built or included, so that I could replace it with my own version. Perhaps that's not even how this works?

Pointers would be appreciated.

EDIT:

For clarity, the question is:

**How to swap out the version of GTK used by GtkSharp for a custom one?**

**Comment by lytico** [comment]
as long as you don't change the signature of the methods - that is, name, parameters and return value - it's no problem.
there are frequently updates to the referenced libs.

**Comment by ividyon** [comment]
@lytico Uhm, this was more of a support request on how to accomplish this...

**Comment by lytico** [comment]
this library is a wrapper; we can't support issues of the wrapped upstream libraries.
we don't ever never build the underlying libs; they are consumed only.
the are distributed by others.

**Comment by ividyon** [comment]
@lytico Again, my question was where exactly the wrapping is done, where the "upstream library" is located, how to swap it out.

This is extremely clear in every message I've written, so I'm increasingly confused as to these responses that keep missing the topic.

**Comment by lytico** [comment]
sorry misunderstanding you; it wasn't clear for me cause of your linked example referring upstream problems,
your topic is about 

 Keyboard hook issue 

and not so clear as you might think

**Comment by ividyon** [comment]
@lytico Please re-open the issue so that somebody else may respond to the original topic.

**Comment by lytico** [comment]
you 'll get your answer, just a little patient ... i am searching it in the code at the moment

**Comment by lytico** [comment]
the locations of the wrapped libs are token with this code:

https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Libs/Shared/GLibrary.cs

https://github.com/GtkSharp/GtkSharp/blob/96f30862e9eea764ea1119c34d401b1c71e7ac57/Source/Libs/Shared/GLibrary.cs#L52-L99

you may also note the other code of the directory
https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Libs/Shared

they together build the funcloader pattern

**Comment by ividyon** [comment]
Thank you!
