### ISSUE TITLE
Clarify the status of this project

### ISSUE THREAD

**Issue by jeremyVignelles** [GtkSharp/GtkSharp#43]
Hello,
I saw nowhere what's the status of this project versus the https://github.com/mono/gtk-sharp repository.

Is that a fork? The new official repository?

When looking on NuGet and on https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new , I was under the impression that this was the official repository, and I was confused later when I found mono/gtk-sharp, which seems to be used by Xamarin.Forms' GTK platform.

Could you clear that up in the readme please?

**Comment by pedrohex** [comment]
Hi Jérémy,

This project is about bindings to the newer versions of Gtk and dotnetcore. Mono/GtkSharp is still using gtk2 bindings and, yes, is supported by Xamarin and used by their mobile platforms.

Future about mono/GtkSharp, in my opinion, will somehow be merged with XamForms. There are some rumors about updating the current bindings, there is some wip but no certains about it.

This project however, goal is clear, will keep providing bindings to the future development of the gtk APIs with Dotnetcore support.

Regards


On 15 Jun 2018, at 13:45, Jérémy VIGNELLES <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I saw nowhere what's the status of this project versus the https://github.com/mono/gtk-sharp repository.

Is that a fork? The new official repository?

When looking on NuGet and on https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new , I was under the impression that this was the official repository, and I was confused later when I found mono/gtk-sharp, which seems to be used by Xamarin.Forms' GTK platform.

Could you clear that up in the readme please?

**Comment by jeremyVignelles** [comment]
Your plans are great, but I think you should make it clear in the front page that this project (and the packages you publish) is not affiliated to the mono/gtk-sharp to avoid confusion.

**Comment by cra0zy** [comment]
> Is that a fork?

Its a fork.

> The new official repository?

Not official.

> When looking on NuGet and on https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new , I was under the impression that this was the official repository, and I was confused later when I found mono/gtk-sharp, which seems to be used by Xamarin.Forms' GTK platform.

Yea, mono guys have been stuck on Gtk 2 for a long time, they have released the 2.99.3 bindings which were meant for Gtk 3, however they have never gotten around to releasing a Gtk 3 stable wrapper or for any future version of Gtk for that matter, so as someone who likes using Gtk I have decided to fork the gtk-sharp repo, and maintain my own set of bindings.

> Could you clear that up in the readme please?

Will leave this issue open and update this as soon as I can.

**Comment by bus710** [comment]
I couldn't really understand what is the difference between this (GtkSharp) and the mono project (gtk-sharp) but after some trial and error I decided to give this project a shot for my next project because this repo (technically the template) gave me a chance to make a good combination of  Dotnet Core + Gtk#3 + Glide + and Rider IDE to kick off my new project.

Since I am a very newbie in the Gtk world, I wish no one would take my comment seriously. 
However, my point is, even though the name can make some people confused, this repo provides a good entry point for newbies (include me!).

And so what? I would like to suggest to the "using the library" section to have some work-flow like description (Maybe I should write and propose...).

**Comment by jeremyVignelles** [comment]
Yeah, this library looks very good, however, I'm trying to build a Xamarin.Forms.Gtk binding for libvlc ( https://github.com/videolan/libvlcsharp ) and using this library is unfortunately impossible as far as I know with X.F . I really don't like this confusion : If I want to support both libraries, how should I name them? It would have been easier if this project was named differently

**Comment by polarapfel** [comment]
I really like the effort around this project, providing a modern Gtk 3 binding to .Net Core. For people just getting into this, it can be confusing though. A one page document, explaining the differences and maybe also going into the limitations of .NET Core versus Mono might help though. .NET Core is not necessarily developed and driven by a desire to enable applications that embed with their native host, many facilities to interact with system devices are simply not available through .NET Core (anything audio for a good example), so choosing .NET Core as your platform for a desktop app really depends on what you need.

@cra0zy I'd also encourage you to actively reach out to @migueldeicaza and get his take, maybe coordinate efforts a little bit.

**Comment by cra0zy** [comment]
> many facilities to interact with system devices are simply not available through .NET Core

.NET Core has as many ways to interact with Audio as .NET Framework... thats such a bad statement.

Also before you say anything: https://www.nuget.org/packages/MonoGame.Framework.DesktopGL.Core/

Yes thats a full game framework without any missing features fully running on .NET Core.

> And so what? I would like to suggest to the "using the library" section to have some work-flow like description (Maybe I should write and propose...).

There was the demo application in this repo I started for this idea. its technically being worked on in my free time.

**Comment by polarapfel** [comment]
> .NET Core has as many ways to interact with Audio as .NET Framework... thats such a bad statement.

Well, [I don't see](https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.1&term=audio) how that's really true. There's NOTHING in .NET Core's API surface for dealing with audio data or devices.

For example, how would you record audio in a .NET Core application?

You'd have to find a third party library that wraps an audio device facility - and that's highly platform dependent. For Windows based apps, most libraries wrap around [IMMDevice interface](https://docs.microsoft.com/en-us/windows/desktop/api/mmdeviceapi/nn-mmdeviceapi-immdevice) - but that will ONLY work on Windows. Say for Linux, you could stumble across libraries such as [this one](https://github.com/atsushieno/alsa-sharp), but mostly they're incomplete, e.g. focus on MIDI output and don't handle mic input.

So, again. Writing a desktop app really depends on what you're trying to achieve. .NET Core does not have wide cross-platform API or library support for a bunch of multimedia use cases.

**Comment by polarapfel** [comment]
> .net core has been thought with Cross-platform in mind.

That's been my point in the beginning. :) So, in other words, other runtime environments with more hooks into a specific platform might be better suited for many desktop apps. For Mono the gstreamer-sharp library is useful. I have no idea if that library would work with .NET Core apps. Most recent Linux distributions use Pulse Audio. I did not come across any .NET based bindings against those libraries.

**Comment by cra0zy** [comment]
> There's NOTHING in .NET Core's API surface for dealing with audio data or devices.

And what was there in .NET Framework that was not a wrapper for a Windows specific API?

**Comment by polarapfel** [comment]
> And what was there in .NET Framework that was not a wrapper for a Windows specific API?

Well, for starters, gstreamer-sharp targeted Mono's .NET Framework equivalent API surface. As far as I can tell, gstreamer-sharp has dependencies on Mono specifically, so will not work with .NET Core.

But if you're aiming at making a point that outside of Windows, audio support around .NET Standard is poor in general, you're probably right.

**Comment by cra0zy** [comment]
> Well, for starters, gstreamer-sharp targeted Mono's .NET Framework equivalent API surface. As far as I can tell, gstreamer-sharp has dependencies on Mono specifically, so will not work with .NET Core.

No true one big. Also that is not part of .NET Framework.

**Comment by nguyenkien** [comment]
Is this project still under development?

**Comment by cra0zy** [comment]
I'm still around maintaining it.

**Comment by nguyenkien** [comment]
Can you point out how to create wrapper for other library?

**Comment by the-black-wolf** [comment]
Is there any way to contribute to this project? We actually started using it for real, but there does not seem to be any list of things to do or any future reference and no way to meaningfully contribute (as far as we see). We really like this project, it allowed us to convert a bunch of Windows workstations into Ubuntu, we would like to see it live and prosper.

**Comment by cra0zy** [comment]
GtkSharp is just a wrapper for a Gtk library, as such there is a limited are of things that need to be done for it. For the most part, the following is the list that needs to be done:
- Fix up any issues other users report: https://github.com/GtkSharp/GtkSharp/issues
- Look at the warnings during generation of partial classes and try to fix them (usually requires adding or removing one line to fix them)
- Write more samples for the Samples app
- Get C# documentation connected to the dlls

The following is also a list of things that need to be done, but these tasks I need to do myself:
- Automatize reading of gapi files
- Connect azure build bot
- Upgrade GtkSharp to Gtk 4 (Gtk 4 is getting released later this year, I'm not rushing in getting this done as most linux distros won't have Gtk 4 so no one is really gonna focus on using it when it gets released)

**Comment by the-black-wolf** [comment]
Thanks for clarifying. 
Though, as I wrote in the cancelled pull request, if assembly signing is the only issue forcing you to Azure build bot, you don't have to. net core 3 supports assembly signing. It might even make more sense to have it built on Linux.
