### ISSUE TITLE
Dark mode troubles

### ISSUE THREAD

**Issue by SuperTavor** [GtkSharp/GtkSharp#435]
I've been trying to get dark mode working in my application. I'm new to GtkSharp and thought this would be the perfect place to seek help from. 
```cs
Application.Init();
Settings settings = Settings.Default;
settings.SetProperty("gtk-application-prefer-dark-theme", new GLib.Value(1));
//... rest of the code
```

The app still appears in light theme, no matter what I do. Any idea why?

**Comment by lytico** [comment]
what OS are you using?

**Comment by SuperTavor** [comment]
Windows 11. Apologies for the late reply

**Comment by SuperTavor** [comment]
To any new people coming to this thread for the same issue - I've figured it out! This works fine.
```cs
var cssProvider = new CssProvider();
cssProvider.LoadFromData(
  @"
  @import url('resource:///org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css');
  "
);
StyleContext.AddProviderForScreen(Gdk.Screen.Default, cssProvider, 800);
  ```
