### ISSUE TITLE
Add a binding for Glade

### ISSUE THREAD

**Issue by ddobrev** [GtkSharp/GtkSharp#44]
The Mono bindings include glade-sharp, a C# binding for Glade. It's needed for interaction with interfaces designed with Glade. So it would nicely complement these bindings.

**Comment by cra0zy** [comment]
You load glade interfaces using `Gtk.Builder` (see [templates](https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Templates/GtkSharp.Template.CSharp/content/GtkSharp.Application.CSharp/MainWindow.cs) for example usage), not sure what other interaction with them is there...

Also I can't find anything on glade-sharp project.

**Comment by cra0zy** [comment]
I'm just gonna close this...

**Comment by gavr123456789** [comment]
Is there a way to add custom widgets to glade itself from CS?   
[Here](https://developer.gnome.org/gladeui/stable/catalog.html) is a guide about adding custom widgets, but I don't quite understand if the same thing is possible from CSharp.  
  
In monodevelop/gui.stetic(GTK 2 gui editor), there was an option to load custom widgets from the dll.  
We are using this now to provide a binding capability for MVVM implementation. (And switching to GTK3 requires the same functionality.)
https://github.com/QualitySolution/GammaBinding/tree/master/GammaBinding
