### ISSUE TITLE
Add support for .NET 4 in the NuGet packages

### ISSUE THREAD

**Issue by ddobrev** [GtkSharp/GtkSharp#45]
When I try installing GtkSharp from its NuGet in a .NET 4 project, I get:

> NU1202: Package GtkSharp 3.22.24.36 is not compatible with net40 (.NETFramework,Version=v4.0) / win-x86. Package GtkSharp 3.22.24.36 supports: netstandard2.0 (.NETStandard,Version=v2.0)

Please add support for .NET 4. It is important because it's the last .NET to run on Windows XP which is still used in many parts of the world. Building the bindings should pose no effort so the only thing to do would be reconfiguring the NuGet.

**Comment by cra0zy** [comment]
MSYS2 (which you need to actually run GTK apps on Windows) does not support Windows XP, GTK also doesn't really support it either, as such neither will this bindings package.

**Comment by ddobrev** [comment]
Wow, I didn't know even GTK+ didn't work on XP any more. Thank you.
