### ISSUE TITLE
Builder.Autoconnect() crashes the app if a (mismatching) signal isn't found

### ISSUE THREAD

**Issue by define-private-public** [GtkSharp/GtkSharp#48]
So in my app, I originally had one glade file per widget, but Glade is able to handle multiple widgets in a single file fine.  So I did a refactor and put all of my widgets into a single `Widgets.glade` file.  Then I refactored the widget's .cs files, so they kind of look like this:

```csharp
public MyMainWindow()
    : this(new Builder("Widgets.glade"))
{
    // ...
}



private MyMainWindow(Builder builder)
    : base(builder.GetObject("MyMainWindow").Handle)
{
    builder.Autoconnect(this);
}

private MyDialog(Builder builder)
    : base(builder.GetObject("MyDialog").Handle)
{
    builder.Autoconnect(this);
}
```

The my `MyDialog` widget/window has some child widgets which are looking for functions e.g. `onOkayPressed()`.  The problem is though that the call to `build.Autoconnect(this)` in `MyMainWindow` is looking for an `onOkayPressed()` method (which isn't supposed to exist for that window).

If you want me to, I can create a project that reproduces this error.

**Comment by cra0zy** [comment]
This is working as expected, `builder.Autoconnect(this)` pretty much automatically connects all widgets/signals in the glade file to the current class. If you want to keep all items in one glade file, than you are gonna have to manually connect each event with `builder.GetObject("Asd")` call.

PS. You usually never wanna put in multiple widgets in one glade file, yes its allowed, however its not very easy to read/edit.

**Comment by cra0zy** [comment]
> PS. You usually never wanna put in multiple widgets in one glade file, yes its allowed, however its not very easy to read/edit.

Also on a related note, you also inflate all your GUIs when you create the builder, so you are keeping all your gui controls inflated all the time.

**Comment by define-private-public** [comment]
1. I think something some be mentioned in the README (or documentation) about how `Autoconnect` works, and how to connect signals & handlers individually.
2. I was putting `MyMainWindow` and `MyDialog` in the same file, since I was getting this error when launching the dialog: `Gtk-Message: 17:13:53.415: GtkDialog mapped without a transient parent. This is discouraged.`, and in the Glade file I wanted to set that transient property, as to get rid of it.
3. What do you mean by "inflate"

**Comment by define-private-public** [comment]
Wondering, wouldn't it be possible to modify the `AutoConnect` code to do what I want?  Or is it not possible?

**Comment by cra0zy** [comment]
> I was putting MyMainWindow and MyDialog in the same file, since I was getting this error when launching the dialog: Gtk-Message: 17:13:53.415: GtkDialog mapped without a transient parent. This is discouraged., and in the Glade file I wanted to set that transient property, as to get rid of it.

You'll get a bunch of warnings from Gtk regarding a bunch of things... you usually just ignore them.

> What do you mean by "inflate"?

Meaning you create all your GUIs, and not just the ones you are showing.

> Wondering, wouldn't it be possible to modify the AutoConnect code to do what I want? Or is it not possible?

It would, however I don't want to encourage this logic for code since its... bad.
