### ISSUE TITLE
How to subclass a DrawingArea to implement a custom a widget

### ISSUE THREAD

**Issue by define-private-public** [GtkSharp/GtkSharp#50]
Sorry keep being a pest on the tracker here, but I'm really interested in using this library. Anyways...

When I was using the Gtk2/Mono, I wanted to use Skia as a rendering backend instead of Cairo.  The `SkiaSharp` project has this thing called `SKWidget`: https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views/SkiaSharp.Views.Gtk/SKWidget.cs  

I was hoping to create my UI in glade, place a `DrawingArea` in that.  Then swap it out with my `SkiaDrawingArea` widget.  The `OnExposed()` virtual method no longer exists in this `DrawingArea`, so I've tried overriding the `OnDrawn()` method, but it's produced no results.

The only example I've see of subclassing a `DrawingArea` is here: https://github.com/GtkSharp/GtkSharp/blob/616f16d083d2c1d4c8d1643c1af5673baf1e41e4/Source/OldStuff/doc/en/Pango/Layout.xml But I also see that it's been marked in the "Old Stuff" section.

**So how can I sublcass `DrawingArea` properly to create a custom widget?**

**Comment by define-private-public** [comment]
Okay, I've got it working.  Would you like me to submit a sample of a subclassed `DrawingArea`?

**Comment by cra0zy** [comment]
Sure, why not.

**Comment by define-private-public** [comment]
I tried grabbing the repo, and then doing a restore and `dotnet run` in the `Source/Samples` directory.  I was getting a lot of errors similar to this:

```
AttrShape.cs(42,16): error CS0234: The type or namespace name 'Rectangle' does not exist in the namespace 'Pango' (are you missing an assembly reference?)
```

Is there something that I'm missing to run the samples (so I can then add a custom drawing area one)?

**Comment by cra0zy** [comment]
Yes, run `build.ps1` or `build.sh` depending on your system, that will generate part of the wrapper.

**Comment by define-private-public** [comment]
Well, if you want to avoid adding in another project, you could also just shove this into a wiki page for the repo:

```csharp
public class MyCustomWidget: Gtk.DrawingArea
{
    public MyCustomWidget() :
        base()
    {
    }

    ~MyCustomWidget()
    {
        Dispose(false);
    }

    protected override bool OnDrawn(Cairo.Context cr)
    {
        // Draw a red background, filling the widget
        cr.SetSourceRGB(1, 0, 0);
        cr.Rectangle(0, 0, Allocation.Width, Allocation.Height);
        cr.Fill();

        return true;
    }
}
```

That is the absolute bare minimum.  Since in my case, I'm also using another rendering system (and rendering resources), I also added in some overriden `Dipose()` calls/methods.  I can provide an example of that too if you want.

**Comment by cra0zy** [comment]
Yea, I'm not gonna add that, that is just common sense.
