### ISSUE TITLE
Can't use Cairo to draw a pixbuf (at the moment)

### ISSUE THREAD

**Issue by define-private-public** [GtkSharp/GtkSharp#52]
I need the `gdk_set_source_pixbuf()` function for something that I'm doing, but I doesn't look like a bound equivalent is available.  This is pretty vital if someone wants to rendering images onto a custom widget.

**Comment by define-private-public** [comment]
Oddly enough, it looks like something is available in the DLL from NuGet:

```
$ strings GdkSharp.dll | sort | uniq | grep SetSource
SetSourceColor
SetSourceDevice
SetSourceEvents
SetSourcePixbuf
SetSourceRgba
SetSourceWindow
```

**Comment by cra0zy** [comment]
```c#
Gdk.CairoHelper.SetSourcePixbuf(...);
```
