### ISSUE TITLE
How to install the Monodevelop addin?

### ISSUE THREAD

**Issue by polarapfel** [GtkSharp/GtkSharp#53]
Hi,

I seem to be a bit thick when it comes to getting the Monodevelop addin to install within Monodevelop.

How would I go about to do that?

thanks,

Tobias

**Comment by cra0zy** [comment]
MonoDevelop addin creation is now connected when making a release and will be available on the Releases page on GitHub: https://github.com/GtkSharp/GtkSharp/releases/latest

Direct link: https://github.com/GtkSharp/GtkSharp/releases/download/3.22.25.24/MonoDevelop.GtkSharp.Addin_3.22.25.24.mpack
