### ISSUE TITLE
Style property properties don't work

### ISSUE THREAD

**Issue by rconde01** [GtkSharp/GtkSharp#54]
var sb = new Gtk.Scrollbar(Gtk.Orientation.Vertical,new Gtk.Adjustment(0,0,10,1,1,1));

//throws "No property with name 'has-backward-stepper' in type 'GtkScrollbar"
var hasit = sb.HasBackwardStepper;

//works
var ppp = sb.StyleGetProperty("has-backward-stepper");

**Comment by cra0zy** [comment]
Hmm, this one is more complex than I thought...
