### ISSUE TITLE
Build requires .Net Core

### ISSUE THREAD

**Issue by ShalokShalom** [GtkSharp/GtkSharp#56]
See here: 
![screenshot_20180828_145202](https://user-images.githubusercontent.com/6344099/44724235-676f4680-aad2-11e8-8a7a-8983fad9cfae.png)

My aim is to build this on Mono.

**Comment by cra0zy** [comment]
To build the repo you need .NET Core, however the resulting assembly can be used with mono and .net framework 4.7.1.
