### ISSUE TITLE
How to block a signal from being emitted

### ISSUE THREAD

**Issue by define-private-public** [GtkSharp/GtkSharp#59]
https://developer.gnome.org/gtk3/stable/GtkEditable.html

I'm trying to do the "Forcing Entry to Uppercase" sample in that page, but I can't seem to find the equivalent call in this Gtk library.  I also did a grep for `BlockByFunc` and I couldn't find anything.

Is there a more "C#-way" of doing this, or has the function not been bound yet?

**Comment by cra0zy** [comment]
Add something along the lines of`e.Handled = true` in your event.

Also make sure its marked with `[Glib.ConnectBefore]` attribute

**Comment by define-private-public** [comment]
```private void onTextInserted(object sender, TextInsertedArgs args)```

That's my event handler signal.  Is `e` meant to be `args` in function?  `Handled` doesn't exist in the `TextInsertedArgs`.

**Comment by pedrohex** [comment]
Try

args.Retval = true;

On 20 Oct 2018, at 17:34, Benjamin Summerton <notifications@github.com<mailto:notifications@github.com>> wrote:


private void onTextInserted(object sender, TextInsertedArgs args)

That's my event handler signal. Is e meant to be args in function? Handled doesn't exist in the TextInsertedArgs.

**Comment by cra0zy** [comment]
> That's my event handler signal. Is `e` meant to be `args` in function?

Yes, `e` is `args`, in C# the 2nd argument of the event is usually either named `e` or `args`, depending on IDE and coding policies.

> `Handled` doesn't exist in the `TextInsertedArgs`.

As @pedrohex pointed out, its `RetVal`, thats why I said along the lines, I don't always remember the exact names of methods/properties.

**Comment by cspaniard** [comment]
Hello everyone,

I am also brand new... but I still cannot make this work. I followed the instructions by @cra0zy and @pedrohex, but still no dice.

in the `insert-text` ---> `Entry_InsertText` event handler:

- `[Glib.ConnectBefore]` attribute and
- `args.RetVal = true`

fire the event perfectly, but do not prevent the character from being inserted into the `Entry` field.

Please, any help would be greatly appreciated.
TIA,
David

**Comment by cra0zy** [comment]
I think you need to override key down event.

**Comment by cspaniard** [comment]
Thank you @cra0zy 

However, the key-down event does not fire inside an `Entry` field. If only fires for keys like `Ctrl`, `Alt`, etc... but it does nothing on regular keys.

It would ideal, since that event does have a `Event` field that allows cancelling it. However, it does not fire for regular keys... a real pitty.

Any ideas ?
TIA,
David

**Comment by barrkel** [comment]
This is still an open problem, AFAIK - there is no way of generally intercepting key strokes to text views in GtkSharp.
