### ISSUE TITLE
PopupMenu with Actions/Accel and glade

### ISSUE THREAD

**Issue by wolfgangmauer** [GtkSharp/GtkSharp#62]
I try to make a popupmenu with actions and accel using the glade designer with no success,
the entry's always stay gray!

A lot of examples uses deprecated functions and i don't know what's the "right" way.
Please give me a hand!

**Comment by cra0zy** [comment]
You can see example on how to do it here: https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Samples/Program.cs#L25

**Comment by wolfgangmauer** [comment]
Thank' a lot, so not working with glade anymore?!

**Comment by cra0zy** [comment]
> Thank' a lot, so not working with glade anymore?!

Its working with glade, I just pointed you to the code where you can see how GLib.Actions are connected. You can just replace the GLib.Menu creation code with Gtk.Builder inflation code and you'd get the same result.
