### ISSUE TITLE
Can't build from git

### ISSUE THREAD

**Issue by wolfgangmauer** [GtkSharp/GtkSharp#64]
What are the system requirements to build with Ubuntu 18.04?
Which executable is missing?
I tried to build from git with follow error:

```sh
Feeds used:
  /home/wolfgang/.nuget/packages/
  https://api.nuget.org/v3/index.json

Alle in "/home/wolfgang/GtkSharp/tools/packages.config" aufgeführten Pakete sind bereits installiert.
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...

========================================
Init
========================================
Executing task: Init
Finished executing task: Init

========================================
Clean
========================================
Executing task: Clean
Finished executing task: Clean

========================================
Prepare
========================================
Executing task: Prepare
An error occurred when executing task 'Prepare'.
**Error: One or more errors occurred.
	.NET Core CLI: Could not locate executable.**
```

**Comment by cra0zy** [comment]
> .NET Core CLI: Could not locate executable.**

You are missing .NET Core, the message tells you:
https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current

You should also installed the proper mono package as well:
https://www.mono-project.com/download/stable/#download-lin-ubuntu

On a related note the README does tell you that you need those:

> Pre requirements for building from source are that you have .Net Core and msbuild installed on the system.

**Comment by wolfgangmauer** [comment]
Thanks a lot
