### ISSUE TITLE
SimpleAction with parameter "VariantType" failed

### ISSUE THREAD

**Issue by wolfgangmauer** [GtkSharp/GtkSharp#71]
I try to pass a value with a action, i have this
...
action = new GLib.SimpleAction("MyAction", GLib.VariantType.Int32);
action.Activated += OnMyAction;
but all the static members of "GLib.VariantType" are null !!!

If i use a "new GLib.VariantType("i")" i get 
Object reference not set to an instance of an object
at GLib.VariantType..ctor (System.String type_string) [0x0000d] in <c00d5e4d00034a84be676c68138aa1a3>:0 
  at GLib.VariantType..cctor () [0x00000] in <c00d5e4d00034a84be676c68138aa1a3>:0  

What i'm doing wrong, or is there a other way to pass a value with an action?!

**Comment by cra0zy** [comment]
Ah, I did not make a new set of nugets, this has been fixed in #63, I'll start up the build bot and new nugets with the fix should be available in an hour or two.
