### ISSUE TITLE
Xamarin.Forms support

### ISSUE THREAD

**Issue by mfkl** [GtkSharp/GtkSharp#72]
Hi,

Any plans to make this binding a Xamarin.Forms compatible backend?

Happy new year!

Cheers.

**Comment by cra0zy** [comment]
I will say that you are asking about this in the wrong repo as I and this repo have nothing to do with Xamarin.Forms stuff.

**Comment by jeremyVignelles** [comment]
I guess that what @mfkl meant was : Does it make sense to have an alternative to xamarin's official xamarin.forms.gtk, but instead of being based on mono/gtk-sharp, based on your project?
Would you be interested in providing that?

On our side, at videolan/libvlcsharp, would it be interesting to provide both integrations? This one would clearly have an advantage in that it can be installed through nuget and that it supports gtk3

**Comment by cra0zy** [comment]
> Does it make sense to have an alternative to xamarin's official xamarin.forms.gtk, but instead of being based on mono/gtk-sharp, based on your project?

I actually barely used Xamarin.Forms so I wouldn't be able to answer this question.

> Would you be interested in providing that?

I would not be interested in providing that. I do not use Xamarin.Forms. I however use Eto.Forms and the original reason of me doing and maintaining this fork is so Eto.Forms could have proper Gtk backend.

Eto.Forms is also a cross platform GUI framework and I highly recommend checking it out: https://github.com/picoe/Eto

> This one would clearly have an advantage in that it can be installed through nuget and that it supports gtk3

Also does not use any native glue libraries, one of the thing that was actually pretty annoying for Eto.Forms before this fork (as the end application would require you to actually install the `gtk-sharp` package...).

> On our side, at videolan/libvlcsharp, would it be interesting to provide both integrations?

That would be nice.

**Comment by jeremyVignelles** [comment]
For cross-reference, there is a discussion around that on MAUI (the successor of Xamarin.Forms) to use this project as a MAUI backend instead of mono/gtk-sharp: https://github.com/dotnet/maui/issues/71
