### ISSUE TITLE
customize glade with css?

### ISSUE THREAD

**Issue by nodew** [GtkSharp/GtkSharp#79]
I'd wonder how to write individual css for gtk application with gtkSharp?

**Comment by define-private-public** [comment]
Are you looking to style an individual widget or the whole Gtk app?  Oddly enough I was playing with this a few days ago.  This is a small example of how to apply two different style sheets to style the whole app.

```
string css1 = @"
label {
    color: red;
}";
string css2 = @"
button {
    background: blue;
} ";

CssProvider cssProvider1 = new CssProvider();
cssProvider1.LoadFromData(css1);

CssProvider cssProvider2 = new CssProvider();
cssProvider2.LoadFromData(css2);

StyleContext.AddProviderForScreen(Gdk.Screen.Default, cssProvider1, 800);
StyleContext.AddProviderForScreen(Gdk.Screen.Default, cssProvider2, 800);
```

If you're looking to target a specific instance of a widget, you need to set the `objectName` and add `#<id_name>` rule matching that name in the CSS.

**Comment by define-private-public** [comment]
On a side note, I'm using `800` instead of `GTK_STYLE_PROVIDER_PRIORITY_USER` since I can't find it in GtkSharp.  I'd feel more comfortable if this constant was defined somewhere.

**Comment by cra0zy** [comment]
> On a side note, I'm using `800` instead of `GTK_STYLE_PROVIDER_PRIORITY_USER` since I can't find it in GtkSharp.

https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Libs/GtkSharp/StyleProviderPriority.cs#L11
