### ISSUE TITLE
Build fails on .NET Core 3 preview

### ISSUE THREAD

**Issue by cejpmart** [GtkSharp/GtkSharp#80]
build.sh:
```
...
Copying file GioSharp-api.xml to Source/Libs/GioSharp/Generated/GioSharp-api.xml
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /opt/dotnet-sdk/
  - The .NET Core Runtime and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      3.0.0-preview3-27503-5 at [/opt/dotnet-sdk/shared/Microsoft.NETCore.App]
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?linkid=2063370
An error occurred when executing task 'Prepare'.
Error: One or more errors occurred. (.NET Core CLI: Process returned an error (exit code 150).)
	.NET Core CLI: Process returned an error (exit code 150).
```

I haven't been able to figure out if and where the required version is hardcoded.

**Comment by cra0zy** [comment]
All the .csproj file specify the version of .NET Core that they require, there are a lot: https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Libs/AtkSharp/AtkSharp.csproj#L4

That being said, I will not update the versions as you can reference a .NET Standard 2.0 assembly from both .NET Core app 2.0 and 3.0 apps, and there is no advantage to updating the target framework.

**Comment by cejpmart** [comment]
I understand that `netstandard2.0` is available on .NET Core 2.0 and later. That doesn't seem to be the problem.

This issue is about failing to build the libraries on .NET Core 3. Is that a _WONTFIX_ then?

**Comment by cra0zy** [comment]
You need .NET Core 2.0 SDK to build a .NET Standard 2.0 project...

**Comment by cejpmart** [comment]
According to what? Projects that don't need preprocessing (CairoSharp) build and run flawlessly, it's the pre-build code generation that crashes and burns.

**Comment by cra0zy** [comment]
As stated in the original comment, a lot of .csproj files have specified version that they require, stuff like CairoSharp does not need GapiCodegen compiled to run, as such, they do not require the following .csproj file to be compiled: https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Tools/GapiCodegen/GapiCodegen.csproj#L5

Interesting tho is that it seems you can build .NET Standard 2.X can be build from .NET Core SDK 3.X, but the same does not apply to netcoreapp2.X.

Yes, this won't be fixed, .NET Core 2 Sdk will be a requirement for building from source for some time.

**Comment by cejpmart** [comment]
FWIW, locally changing netcoreapp2.0 to 3.0 in GapiCodegen.csproj and GapiFixup.csproj is a suitable workaround.
If somebody gets bored, there is a more graceful solution at https://github.com/dotnet/machinelearning/commit/fcea146add5e8b9c3197f800b7201b333ab5ae3e.

**Comment by jcbritobr** [comment]
> 
> 
> FWIW, locally changing netcoreapp2.0 to 3.0 in GapiCodegen.csproj and GapiFixup.csproj is a suitable workaround.
> If somebody gets bored, there is a more graceful solution at [dotnet/machinelearning@fcea146](https://github.com/dotnet/machinelearning/commit/fcea146add5e8b9c3197f800b7201b333ab5ae3e).
Thank you. This info help me a lot.
