### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by mikkeljohnsen** [GtkSharp/GtkSharp#82]
We have a fairly large product written in GtkSharp using Mono (Linux and macOS) and .NET Framework (Windows).

We have been using Gtk3 for a very long time, but our application is now becoming very unstable because of memory leaks. GtkSharp is simple not able to release native memory.

I will upload test applications later. We have testet with native C gtk3 program, simple creating 1000 dialog boxes and calling Hide and Destroy on them. Valgrind is reporting no memory leaks. The same program creating 1000 dialogs using C#, valgrind is reporting massive native memory leaks, as do Memory Profiler on Windows.

We have been trying to solve this for some time, but have trouble finding the cause.

I hope that someone in here is able to help us, finding this bug in the GtkSharp (wrapper).

**Comment by cra0zy** [comment]
Yikes, I'll look into it as soon as I can.

**Comment by cra0zy** [comment]
Quick test reveals this, creating a bunch of buttons or anything a like has memory leak, however manually calling dispose on each button has no memory leak. I suspect something regarding finalizer.

**Comment by mikkeljohnsen** [comment]
Could you try with a dialog ?
I think simple widget is working when calling Dispose.

**Comment by cra0zy** [comment]
Okey, I have at least narrowed down what I have to look at:
- It exist before my "WIP CAKE + .Net Core" commit (6926c9cbf2c82272ff88e918d780eb0894b78be7)
- Based on what you said it does not exist before "Include debugging symbols in nupkg" commit (b6260e8865dd09a50d41abe157e348618d5a733e)

**Comment by mikkeljohnsen** [comment]
I'm not sure why you say it do not exist before "Include debugging symbols in nupkg". I think the problem has always been there (meybe not in Gtk#-2). The reason we see it now, is that a new customer of ours is running on very old hardware.

**Comment by cra0zy** [comment]
Oh, misunderstood you there, I though we introduced it... welp turns out it exist in Gtk 2 as well...

**Comment by cra0zy** [comment]
PS. Yes, with dialogs the `Dispose` does not work properly.

**Comment by mikkeljohnsen** [comment]
We have been trying to solve this for some time. But there seems to always be some ToogleRef hanging around, keeping them from being freed properly.

**Comment by mikkeljohnsen** [comment]
I suspect that all containers are not being freed properly.

**Comment by mikkeljohnsen** [comment]
I also strongly believe that we should include the Destroy in Dispose. It should not be necessary to call both Destroy and Dispose.

**Comment by mikkeljohnsen** [comment]
@cra0zy What can we do to fix this huge problem with memory ?

We do not have the expertise to resolve this our self. But we do have the means to (maybe) finans it, if someone is able to work on the problem ?

Do you have any idea if you or someone else could solve it ?

**Comment by cra0zy** [comment]
I'll have time to explore this later this week and during next week, I'll see if I can find whats wrong. I'm assuming its the finalizers.

**Comment by mikkeljohnsen** [comment]
@cra0zy  Not to put any presure on you. But have you been able to find some time to look at this ?

**Comment by cra0zy** [comment]
Haven't had the time, tho I would recommend we complain on the mono/gtk-sharp repo as well, considering the memory leak exists with gtk# 2 as well.

**Comment by stsundermann** [comment]
Can you upload a simple test program?

**Comment by mikkeljohnsen** [comment]
This is a C version, where no memory is leaked.
[GtkMemory.tar.gz](https://github.com/GtkSharp/GtkSharp/files/3134145/GtkMemory.tar.gz)

This is the C# version where there is native memory leak.
[GtkSharpMemory.tar.gz](https://github.com/GtkSharp/GtkSharp/files/3134146/GtkSharpMemory.tar.gz)

**Comment by cra0zy** [comment]
https://gist.github.com/cra0zy/ac6ca4c2cebb4e5f2cf316a6d92e32db

**Comment by stsundermann** [comment]
I can't test right now, but you're not calling Destroy() on your dialog. The native example does that.

**Comment by cra0zy** [comment]
Nah, that still makes a memory leak, I just quickly created an example, if you are talking about my gist.

**Comment by stsundermann** [comment]
You need to call both Destroy() and Dispose(). I've hooked up into Object.cs to see reference counts before managed side decides to delete the object. If you're not calling Destroy() before Dispose() you will end up leaking a reference. If you call Destroy() before Dispose() at least the reference count from the dialog goes to 0 which clears the object on the native side. I do still see some memory leak occur but it's not from the dialog itself.

**Comment by stsundermann** [comment]
Anyway, I do also agree that the user should not need to call both Destroy() and Dispose() as it is quite inconvenient. In case of a Destroy() method being present, the Dispose() function should call Destroy() internally.

**Comment by cra0zy** [comment]
Yup, you are completely right. Never realized you needed to call both of em one after another for a proper destruction of a gtk object...

**Comment by stsundermann** [comment]
Dispose shouldn't be needed as it is called from the destructor when the GC kicks in. But calling it anyway is best practice since the GC cleanup is non deterministic.

**Comment by stsundermann** [comment]
Actually it seems an explicit Destroy() is needed in cases where you want to cleanup the dialog before the attached toplevel window is destroyed. As adviced by the gtk folks it is not recommended to do this cleanup automatically since weird stuff might happen.

**Comment by cra0zy** [comment]
I'm gonna close this as it turns out the wrapper is working as expected.

**Comment by mikkeljohnsen** [comment]
@cra0zy If you look at this patch: https://github.com/mono/gtk-sharp/commit/9f40d6c2516c54e730b52b7326287ddbb603ab5c#diff-ceb73ace5d4318a3141b31d265100c75 where is the *.custom files in your source ?

**Comment by stsundermann** [comment]
Custom files have been replaced with partial classes.

**Comment by mikkeljohnsen** [comment]
We now have two branches we are testing (in production):

This branch is a attempt to move patches from the 2.12 branch to 3.22 branch. We had this in testing (in production) for 2 weeks and we say multiple exceptions with cast to ToggleRef and other unexpected behaviors:
https://github.com/GSharpKit/GtkSharp/tree/migrate_2.12_memory_patches

This is a simple patch/branch to only fix the memory leaks and we have that in testing from today (in production). I will comment later when we have more data:
https://github.com/GSharpKit/GtkSharp/tree/2.12_memory_patches_minimal

I hope that someone will look at these branches and can help out.

**Comment by mikkeljohnsen** [comment]
With this patch we see good results. We have fewer crashes (duo to memory limit).

https://github.com/GSharpKit/GtkSharp/tree/2.12_memory_patches_minimal

It would be great to have the FastActivator in patch 1 aswell, but wee need to work more on that.

**Comment by cra0zy** [comment]
Submit a PR. I'll merge them ASAP.

**Comment by cra0zy** [comment]
I have merged your commits to develop branch.

**Comment by knocte** [comment]
> I have merged your commits to develop branch.

Just curious, since this message was written, has the develop branch been merged to master? All in all, is the current version in nuget including these fixes?

**Comment by harry-cpp** [comment]
It does.

**Comment by knocte** [comment]
So why is this issue not closed? Not 100% fixed?

**Comment by mikkeljohnsen** [comment]
Anyone following gstreamer-sharp: https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/-/issues/10#note_495748

They are discussing memory leaks and also GtkSharp memory handling.

**Comment by jcbritobr** [comment]
I think we can close this issue. It had a long time was opened and it was fixed.

**Comment by mikkeljohnsen** [comment]
Will be fixed by: https://github.com/GtkSharp/GtkSharp/pull/198
