### ISSUE TITLE
Is it possible to access glade files from another folder?

### ISSUE THREAD

**Issue by sirfaceless** [GtkSharp/GtkSharp#85]
Say I have all of my glade files in `Layouts` is it possible to access them from another folder

```
- app
    - Layouts
        - Window.glade
        - AWidget.glade
    - Window.cs

```

I have tried to add the builder pointing to the Layouts folder, but that doesn't work:

```
        public MainWindow() : this(
            new Builder("Layouts/Window.glade")
        ) { }
```

> Unhandled Exception: System.ArgumentException: Cannot get resource file 'Layouts/Window.glade'

Any ideas how to achieve this?

**Comment by cra0zy** [comment]
It takes in embedded resource name / resource id as the parameter, not filepath, tho there is an override for a filestream or something like that.
