### ISSUE TITLE
Monodevelop build error:  Could not resolve type with token 01000027 

### ISSUE THREAD

**Issue by awittaker** [GtkSharp/GtkSharp#86]
Hi. I'm new to mono/Ubuntu from .Net/Windows, and can't get the basic gtkapp template to build in monodevelop 7.8.2.

I've installed [dotnet-sdk-2.2](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current) and libgtk-3-dev.

I've cloned & built GtkSharp (no errors, but 100s of warnings - is this expected?).

The templates installed & generated without error:
```
dotnet new --install GtkSharp.Template.CSharp
dotnet new gtkapp
```
I can then build and run from the command line (Hello World!!)...
```
dotnet build test01.csproj
dotnet run
```
However when I open test01.csproj in monodevelop & build, it loads the packages OK, but fails shortly thereafter:
`'Microsoft.NET.Build.Tasks.DependencyContextBuilder:_filteredPackages' (12) due to: Could not resolve type with token 01000027 from typeref (expected class 'NuGet.Packaging.Core.PackageIdentity' in assembly 'NuGet.Packaging, Version=5.0.0.6, Culture=neutral, PublicKeyToken=31bf3856ad364e35') `

I think it's some kind of package version conflict, but I'm unclear how to troubleshoot further?

Here are some related "initial setup" questions that might help me...

Do I need to build GtkSharp from git, or is the `dotnet new --install GtkSharp.Template.CSharp` command enough to use GtkSharp?

What is the gtksharp monodevelop addin?
Is it required to build GtkSharp template in monodevelop?

I get a warning from `dotnet build MonoDevelop.GtkSharp.Addin.csproj` since it targets 4.6.1, so it will "target MonoDevelop's framework v4.7.1"... then I get an error that 4.7.1 was not found! (I have mono 5.18 which I believe targets 4.7.2).

I tried editing MonoDevelop.GtkSharp.Addin.csproj to use net472, but it still complains about 461/471. I removed obj folder, so I am not sure why it's still looking for 461!

Any advice appreciated.

**Comment by cra0zy** [comment]
This actually isn't a GtkSharp bug, see the following issues for more details:
- https://github.com/dotnet/core/issues/2540
- https://github.com/NuGet/Home/issues/7956

Also I have no workaround besides downgrading the dotnet so far.

**Comment by awittaker** [comment]
Thanks cra0zy for prompt response. Will follow the listed bugs.

**Comment by awittaker** [comment]
Removed dotnet-sdk-2.2 (2.2.203) and manually installed v2.2.106 and can now "Hello World" from monodevelop! Cheers.
