### ISSUE TITLE
Can not compile under fedora 29

### ISSUE THREAD

**Issue by badcel** [GtkSharp/GtkSharp#87]
Hey,

I can not compile GtkSharp with fedora 29. The error message is:

> ./build.sh 
> Could not load file or assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
>   Could not load file or assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

It is the same error like starting the nuget.exe with mono:

> $ mono tools/nuget.exe 
> Could not load file or assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

**Comment by cra0zy** [comment]
99% sure your C# dev environment is incorrectly setup, like not installing full mono runtime from the official website or such.

Anyway closing this as compiling from source functions correctly under Arch Linux and Ubuntu.

**Comment by badcel** [comment]
You were right, it works with the mono-complete package directly from the mono project.
