### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by bh1rio** [GtkSharp/GtkSharp#88]
some error: after 'dotnet run', without display or forms
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name="Application Error" /> 
        <EventID Qualifiers="0">1000</EventID> 
        <Level>2</Level> 
        <Task>100</Task> 
        <Keywords>0x80000000000000</Keywords> 
        <TimeCreated SystemTime="2019-05-07T09:00:33.608147500Z" /> 
        <EventRecordID>25145</EventRecordID> 
        <Channel>Application</Channel> 
        <Computer>gene</Computer> 
        <Security /> 
    </System>
    <EventData>
        <Data>dotnet.exe</Data> 
        <Data>3.0.27626.15</Data> 
        <Data>5cc3d457</Data> 
        <Data>ntdll.dll</Data> 
        <Data>10.0.17763.475</Data> 
        <Data>3230aa04</Data> 
        <Data>c0000005</Data> 
        <Data>000000000000481c</Data> 
        <Data>2104</Data> 
        <Data>01d504b35414a1f8</Data> 
        <Data>C:\Program Files\dotnet\dotnet.exe</Data> 
        <Data>C:\Windows\SYSTEM32\ntdll.dll</Data> 
        <Data>02526c47-777f-41f2-a220-3599e60ff3c4</Data> 
        <Data /> 
        <Data /> 
    </EventData>
</Event>
```

**Comment by cra0zy** [comment]
What error do you get in console?

**Comment by bh1rio** [comment]
> 
> 
> What error do you get in console?

none output，none display，none form

**Comment by bh1rio** [comment]
random three cases：
1. none output，none display，none form
 with the event log on top
2. can‘t load libpng16-16.dll
![微信截图_20190507163555](https://user-images.githubusercontent.com/12414463/57343250-25c09080-7175-11e9-97c6-5b5e1cfe8593.png)
 
3. can‘t init Gtk.Application
![微信截图_20190508093551](https://user-images.githubusercontent.com/12414463/57343266-3113bc00-7175-11e9-9262-0879a8ce14f9.png)

**Comment by cra0zy** [comment]
Assuming you already did https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Windows, try manually installing libpng in the msys2 console, should be something like:

```sh
pacman -S libpng
# or
pacman -S libpng12
```

**Comment by bh1rio** [comment]
I test it in a new env, only dotnet core sdk 2.2.203. And there none error.

So I think it cause by installed 2.2.203 and 3.0.100-preview5 same time.

**Comment by bh1rio** [comment]
I test it in a new env, only dotnet core sdk 2.2.203. And there none error.

So I think it cause by installed 2.2.203 and 3.0.100-preview5 same time.

**Comment by bh1rio** [comment]
I re-run the command ``` pacman -S mingw-w64-x86_64-gtk3 ``` in MSYS2 Shell， than there none error.
I only run ··· pacman -S mingw-w64-x86_64-gtk3 ··· in MYSYS2 64bit shell before.

Is there some difference between MSYS2 shell and mingw 64bit shell ?
