### ISSUE TITLE
Mono GTK# 3

### ISSUE THREAD

**Issue by knuxbbs** [GtkSharp/GtkSharp#89]
Why the _mono/gtksharp_ version of Gtk# 3 has never officially released?

**Comment by cra0zy** [comment]
I don't know, you would need to ask the devs of that project, but for the most part, I assume its because MonoDevelop uses gtk 2 and porting it to use gtk 3 is not an easy process, as such, they never had a reason to officially support gtk 3.

**Comment by lextm** [comment]
Some additional background.

Miguel de Icaza criticized the design of GTK 3, and also when GTK 3 was out, the power behind Mono/GTK# no longer existed. Therefore, all efforts were shifted to mobile and Mac, and Xamarin was founded on that.
