### ISSUE TITLE
What is the command line to execute a gtk3 program?

### ISSUE THREAD

**Issue by Hamam-S** [GtkSharp/GtkSharp#92]
I'm trying to execute an example of a gtk 3.0 program, but I'm getting these error : 

> g++: error: `pkg-config: No such file or directory
> g++: error: gtkmm-3.0: No such file or directory
> g++: error: unrecognized command line option '--cflags'
> g++: error: unrecognized command line option '--libs`'

the command line I tried is thise : 
> g++ simple.cc -o simple `pkg-config gtkmm-3.0 --cflags --libs`

I did add the path to the environmenet variable

<img width="839" alt="ming" src="https://user-images.githubusercontent.com/51049600/58839007-a2556a80-8660-11e9-9599-93ce5c6858a2.PNG">

**Comment by cra0zy** [comment]
You added the wrong bin folder: https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Windows

**Comment by Hamam-S** [comment]
> You added the wrong bin folder: https://github.com/GtkSharp/GtkSharp/wiki/Installing-Gtk-on-Windows

Look at the last one at the bottom.

**Comment by cra0zy** [comment]
Oh, nvm than, have no idea.

Also gonna close this as its not a question about gtksharp.
